version: '3'

services:
  swift-api:
    container_name: swiftfiat_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - redis
    networks:
      - swiftfiat-network

  bitgo:
    container_name: swiftfiat_bitgo
    image: bitgo/express:latest
    ports:
      - "3080:3080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3080/api/v2/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - swiftfiat-network

  redis:
    container_name: swiftfiat_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --protected-mode no  # Disable protected mode for Docker network access
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - swiftfiat-network

volumes:
  redis_data:

networks:
  swiftfiat-network:
    driver: bridge