// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditEventCategory string

const (
	AuditEventCategoryAuthentication  AuditEventCategory = "authentication"
	AuditEventCategoryAuthorization   AuditEventCategory = "authorization"
	AuditEventCategoryAccount         AuditEventCategory = "account"
	AuditEventCategoryTransaction     AuditEventCategory = "transaction"
	AuditEventCategoryKyc             AuditEventCategory = "kyc"
	AuditEventCategoryCard            AuditEventCategory = "card"
	AuditEventCategorySecurity        AuditEventCategory = "security"
	AuditEventCategoryCompliance      AuditEventCategory = "compliance"
	AuditEventCategorySystem          AuditEventCategory = "system"
	AuditEventCategoryVault           AuditEventCategory = "vault"
	AuditEventCategoryGiftcard        AuditEventCategory = "giftcard"
	AuditEventCategoryRapidRamp       AuditEventCategory = "rapid_ramp"
	AuditEventCategoryRateManager     AuditEventCategory = "rate_manager"
	AuditEventCategoryStreaks         AuditEventCategory = "streaks"
	AuditEventCategoryCrypto          AuditEventCategory = "crypto"
	AuditEventCategorySmartConversion AuditEventCategory = "smart_conversion"
	AuditEventCategorySupport         AuditEventCategory = "support"
	AuditEventCategoryRewards         AuditEventCategory = "rewards"
)

func (e *AuditEventCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditEventCategory(s)
	case string:
		*e = AuditEventCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditEventCategory: %T", src)
	}
	return nil
}

type NullAuditEventCategory struct {
	AuditEventCategory AuditEventCategory `json:"audit_event_category"`
	Valid              bool               `json:"valid"` // Valid is true if AuditEventCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditEventCategory) Scan(value interface{}) error {
	if value == nil {
		ns.AuditEventCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditEventCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditEventCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditEventCategory), nil
}

type AuditSeverity string

const (
	AuditSeverityInfo     AuditSeverity = "info"
	AuditSeverityWarning  AuditSeverity = "warning"
	AuditSeverityError    AuditSeverity = "error"
	AuditSeverityCritical AuditSeverity = "critical"
)

func (e *AuditSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditSeverity(s)
	case string:
		*e = AuditSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditSeverity: %T", src)
	}
	return nil
}

type NullAuditSeverity struct {
	AuditSeverity AuditSeverity `json:"audit_severity"`
	Valid         bool          `json:"valid"` // Valid is true if AuditSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.AuditSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditSeverity), nil
}

type ActiveSubscriptionSetting struct {
	SettingKey   string         `json:"setting_key"`
	SettingValue string         `json:"setting_value"`
	SettingType  string         `json:"setting_type"`
	Description  sql.NullString `json:"description"`
	Category     string         `json:"category"`
	IntValue     interface{}    `json:"int_value"`
	DecimalValue interface{}    `json:"decimal_value"`
	BoolValue    interface{}    `json:"bool_value"`
}

type AdminAlert struct {
	ID             int64          `json:"id"`
	Severity       string         `json:"severity"`
	Title          string         `json:"title"`
	Message        string         `json:"message"`
	Source         sql.NullString `json:"source"`
	Acknowledged   bool           `json:"acknowledged"`
	AcknowledgedAt sql.NullTime   `json:"acknowledged_at"`
	AcknowledgedBy int64          `json:"acknowledged_by"`
	CreatedAt      time.Time      `json:"created_at"`
}

type AgentMetric struct {
	ID                        int64          `json:"id"`
	SupportAdminID            int64          `json:"support_admin_id"`
	TicketsHandled            int32          `json:"tickets_handled"`
	TicketsResolved           int32          `json:"tickets_resolved"`
	AverageResolutionTime     sql.NullInt32  `json:"average_resolution_time"`
	AverageResponseTime       sql.NullInt32  `json:"average_response_time"`
	CustomerSatisfactionScore sql.NullString `json:"customer_satisfaction_score"`
	Date                      time.Time      `json:"date"`
	CreatedAt                 time.Time      `json:"created_at"`
}

// Historical log of when alerts were triggered
type AlertTriggerHistory struct {
	ID                    int64          `json:"id"`
	AlertID               uuid.UUID      `json:"alert_id"`
	UserID                int64          `json:"user_id"`
	TriggeredAt           time.Time      `json:"triggered_at"`
	CurrentRate           string         `json:"current_rate"`
	PreviousRate          sql.NullString `json:"previous_rate"`
	ChangePercent         sql.NullString `json:"change_percent"`
	AlertCondition        string         `json:"alert_condition"`
	TargetRate            sql.NullString `json:"target_rate"`
	PushNotificationSent  sql.NullBool   `json:"push_notification_sent"`
	InAppNotificationSent sql.NullBool   `json:"in_app_notification_sent"`
	NotificationError     sql.NullString `json:"notification_error"`
	CreatedAt             time.Time      `json:"created_at"`
}

type Attachment struct {
	ID        int64     `json:"id"`
	MessageID int64     `json:"message_id"`
	FileUrl   string    `json:"file_url"`
	FileName  string    `json:"file_name"`
	FileSize  int32     `json:"file_size"`
	MimeType  string    `json:"mime_type"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

// Immutable audit trail for all critical system operations
type AuditLog struct {
	ID int64 `json:"id"`
	// High-level categorization for filtering
	EventCategory AuditEventCategory `json:"event_category"`
	// Specific event identifier (e.g., user.login.success)
	EventType  string         `json:"event_type"`
	Severity   AuditSeverity  `json:"severity"`
	ActorID    sql.NullInt64  `json:"actor_id"`
	ActorType  string         `json:"actor_type"`
	ActorEmail sql.NullString `json:"actor_email"`
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	IpAddress  pqtype.Inet    `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	// Trace ID for correlating logs across microservices
	RequestID   sql.NullString        `json:"request_id"`
	Action      string                `json:"action"`
	Description string                `json:"description"`
	OldValues   pqtype.NullRawMessage `json:"old_values"`
	NewValues   pqtype.NullRawMessage `json:"new_values"`
	// Flexible JSON storage for event-specific context
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	Success      bool                  `json:"success"`
	ErrorMessage sql.NullString        `json:"error_message"`
	CreatedAt    time.Time             `json:"created_at"`
}

type AuditLogs202412 struct {
	ID int64 `json:"id"`
	// High-level categorization for filtering
	EventCategory AuditEventCategory `json:"event_category"`
	// Specific event identifier (e.g., user.login.success)
	EventType  string         `json:"event_type"`
	Severity   AuditSeverity  `json:"severity"`
	ActorID    sql.NullInt64  `json:"actor_id"`
	ActorType  string         `json:"actor_type"`
	ActorEmail sql.NullString `json:"actor_email"`
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	IpAddress  pqtype.Inet    `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	// Trace ID for correlating logs across microservices
	RequestID   sql.NullString        `json:"request_id"`
	Action      string                `json:"action"`
	Description string                `json:"description"`
	OldValues   pqtype.NullRawMessage `json:"old_values"`
	NewValues   pqtype.NullRawMessage `json:"new_values"`
	// Flexible JSON storage for event-specific context
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	Success      bool                  `json:"success"`
	ErrorMessage sql.NullString        `json:"error_message"`
	CreatedAt    time.Time             `json:"created_at"`
}

type AuditLogs202501 struct {
	ID int64 `json:"id"`
	// High-level categorization for filtering
	EventCategory AuditEventCategory `json:"event_category"`
	// Specific event identifier (e.g., user.login.success)
	EventType  string         `json:"event_type"`
	Severity   AuditSeverity  `json:"severity"`
	ActorID    sql.NullInt64  `json:"actor_id"`
	ActorType  string         `json:"actor_type"`
	ActorEmail sql.NullString `json:"actor_email"`
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	IpAddress  pqtype.Inet    `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	// Trace ID for correlating logs across microservices
	RequestID   sql.NullString        `json:"request_id"`
	Action      string                `json:"action"`
	Description string                `json:"description"`
	OldValues   pqtype.NullRawMessage `json:"old_values"`
	NewValues   pqtype.NullRawMessage `json:"new_values"`
	// Flexible JSON storage for event-specific context
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	Success      bool                  `json:"success"`
	ErrorMessage sql.NullString        `json:"error_message"`
	CreatedAt    time.Time             `json:"created_at"`
}

type AuditLogs202502 struct {
	ID int64 `json:"id"`
	// High-level categorization for filtering
	EventCategory AuditEventCategory `json:"event_category"`
	// Specific event identifier (e.g., user.login.success)
	EventType  string         `json:"event_type"`
	Severity   AuditSeverity  `json:"severity"`
	ActorID    sql.NullInt64  `json:"actor_id"`
	ActorType  string         `json:"actor_type"`
	ActorEmail sql.NullString `json:"actor_email"`
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	IpAddress  pqtype.Inet    `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	// Trace ID for correlating logs across microservices
	RequestID   sql.NullString        `json:"request_id"`
	Action      string                `json:"action"`
	Description string                `json:"description"`
	OldValues   pqtype.NullRawMessage `json:"old_values"`
	NewValues   pqtype.NullRawMessage `json:"new_values"`
	// Flexible JSON storage for event-specific context
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	Success      bool                  `json:"success"`
	ErrorMessage sql.NullString        `json:"error_message"`
	CreatedAt    time.Time             `json:"created_at"`
}

type AuditLogsDefault struct {
	ID int64 `json:"id"`
	// High-level categorization for filtering
	EventCategory AuditEventCategory `json:"event_category"`
	// Specific event identifier (e.g., user.login.success)
	EventType  string         `json:"event_type"`
	Severity   AuditSeverity  `json:"severity"`
	ActorID    sql.NullInt64  `json:"actor_id"`
	ActorType  string         `json:"actor_type"`
	ActorEmail sql.NullString `json:"actor_email"`
	EntityType string         `json:"entity_type"`
	EntityID   string         `json:"entity_id"`
	IpAddress  pqtype.Inet    `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	// Trace ID for correlating logs across microservices
	RequestID   sql.NullString        `json:"request_id"`
	Action      string                `json:"action"`
	Description string                `json:"description"`
	OldValues   pqtype.NullRawMessage `json:"old_values"`
	NewValues   pqtype.NullRawMessage `json:"new_values"`
	// Flexible JSON storage for event-specific context
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	Success      bool                  `json:"success"`
	ErrorMessage sql.NullString        `json:"error_message"`
	CreatedAt    time.Time             `json:"created_at"`
}

// Defines achievement badges with unlock requirements
type Badge struct {
	ID                 int64          `json:"id"`
	Name               string         `json:"name"`
	Description        string         `json:"description"`
	IconUrl            sql.NullString `json:"icon_url"`
	RequiredStreakDays int32          `json:"required_streak_days"`
	TierLevel          int32          `json:"tier_level"`
	IsActive           bool           `json:"is_active"`
	DisplayOrder       int32          `json:"display_order"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

// User bank accounts for withdrawals and QR payments - users can have multiple accounts with one default
type BankAccount struct {
	ID                    uuid.UUID      `json:"id"`
	UserID                int64          `json:"user_id"`
	AccountName           string         `json:"account_name"`
	AccountNumber         string         `json:"account_number"`
	BankCode              string         `json:"bank_code"`
	BankName              string         `json:"bank_name"`
	AccountType           sql.NullString `json:"account_type"`
	Currency              string         `json:"currency"`
	IsVerified            bool           `json:"is_verified"`
	VerifiedAt            sql.NullTime   `json:"verified_at"`
	VerificationMethod    sql.NullString `json:"verification_method"`
	VerificationReference sql.NullString `json:"verification_reference"`
	IsDefault             bool           `json:"is_default"`
	IsActive              bool           `json:"is_active"`
	Status                string         `json:"status"`
	Label                 sql.NullString `json:"label"`
	Description           sql.NullString `json:"description"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	DeletedAt             sql.NullTime   `json:"deleted_at"`
}

type BankTransferMetadatum struct {
	ID                   uuid.UUID      `json:"id"`
	Amount               string         `json:"amount"`
	ServiceCharge        string         `json:"service_charge"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	AccountName          string         `json:"account_name"`
	AccountNumber        string         `json:"account_number"`
	ServiceProvider      sql.NullString `json:"service_provider"`
	Type                 string         `json:"type"`
	ServiceTransactionID sql.NullString `json:"service_transaction_id"`
	Status               string         `json:"status"`
	Date                 time.Time      `json:"date"`
	AmountPaid           string         `json:"amount_paid"`
	PointsEarned         sql.NullString `json:"points_earned"`
}

type Beneficiary struct {
	ID              uuid.UUID     `json:"id"`
	UserID          sql.NullInt64 `json:"user_id"`
	BankCode        string        `json:"bank_code"`
	AccountNumber   string        `json:"account_number"`
	BeneficiaryName string        `json:"beneficiary_name"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type Brand struct {
	ID        int32          `json:"id"`
	BrandID   int64          `json:"brand_id"`
	BrandName sql.NullString `json:"brand_name"`
}

type CannedResponse struct {
	ID         int64          `json:"id"`
	Title      string         `json:"title"`
	Content    string         `json:"content"`
	Shortcut   sql.NullString `json:"shortcut"`
	Category   sql.NullString `json:"category"`
	UsageCount int32          `json:"usage_count"`
	CreatedBy  sql.NullInt64  `json:"created_by"`
	IsActive   bool           `json:"is_active"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type CardBillingHistory struct {
	ID                 uuid.UUID      `json:"id"`
	TransactionID      uuid.UUID      `json:"transaction_id"`
	CardID             uuid.UUID      `json:"card_id"`
	UserID             int64          `json:"user_id"`
	CardPlanID         int64          `json:"card_plan_id"`
	BillingType        string         `json:"billing_type"`
	Amount             string         `json:"amount"`
	Currency           string         `json:"currency"`
	BillingPeriodStart time.Time      `json:"billing_period_start"`
	BillingPeriodEnd   time.Time      `json:"billing_period_end"`
	SourceWalletID     uuid.UUID      `json:"source_wallet_id"`
	Status             string         `json:"status"`
	FailureReason      sql.NullString `json:"failure_reason"`
	CreatedAt          time.Time      `json:"created_at"`
	ProcessedAt        sql.NullTime   `json:"processed_at"`
}

type CardFundingHistory struct {
	ID                      uuid.UUID      `json:"id"`
	TransactionID           uuid.UUID      `json:"transaction_id"`
	CardID                  uuid.UUID      `json:"card_id"`
	UserID                  int64          `json:"user_id"`
	SourceWalletID          uuid.UUID      `json:"source_wallet_id"`
	Amount                  string         `json:"amount"`
	Currency                string         `json:"currency"`
	SourceCurrency          string         `json:"source_currency"`
	ExchangeRate            sql.NullString `json:"exchange_rate"`
	BridgecardTransactionID sql.NullString `json:"bridgecard_transaction_id"`
	FundingType             string         `json:"funding_type"`
	InitiatedBy             string         `json:"initiated_by"`
	Status                  string         `json:"status"`
	FailureReason           sql.NullString `json:"failure_reason"`
	CreatedAt               time.Time      `json:"created_at"`
	CompletedAt             sql.NullTime   `json:"completed_at"`
}

type CardPlan struct {
	ID                       int64          `json:"id"`
	Name                     string         `json:"name"`
	Description              sql.NullString `json:"description"`
	IsActive                 bool           `json:"is_active"`
	CreationFee              string         `json:"creation_fee"`
	MonthlyMaintenanceFee    string         `json:"monthly_maintenance_fee"`
	MonthlySpendingLimit     string         `json:"monthly_spending_limit"`
	TransactionLimit         string         `json:"transaction_limit"`
	DailySpendingLimit       sql.NullString `json:"daily_spending_limit"`
	CardLimit                sql.NullString `json:"card_limit"`
	MaxCardsPerUser          int32          `json:"max_cards_per_user"`
	FailedTxCountBeforeBlock sql.NullInt32  `json:"failed_tx_count_before_block"`
	CreatedAt                time.Time      `json:"created_at"`
	UpdatedAt                time.Time      `json:"updated_at"`
	DeletedAt                sql.NullTime   `json:"deleted_at"`
}

type CardSpendingSummary struct {
	CardID                   uuid.UUID `json:"card_id"`
	UserID                   int64     `json:"user_id"`
	CardName                 string    `json:"card_name"`
	Transactions30d          int64     `json:"transactions_30d"`
	Spend30d                 int64     `json:"spend_30d"`
	UniqueMerchants30d       int64     `json:"unique_merchants_30d"`
	SubscriptionTransactions int64     `json:"subscription_transactions"`
}

type CardTransaction struct {
	ID                      uuid.UUID             `json:"id"`
	TransactionID           uuid.UUID             `json:"transaction_id"`
	CardID                  uuid.UUID             `json:"card_id"`
	UserID                  int64                 `json:"user_id"`
	BridgecardTransactionID string                `json:"bridgecard_transaction_id"`
	TransactionType         string                `json:"transaction_type"`
	MerchantName            sql.NullString        `json:"merchant_name"`
	MerchantCategory        sql.NullString        `json:"merchant_category"`
	MerchantCategoryCode    sql.NullString        `json:"merchant_category_code"`
	Amount                  int64                 `json:"amount"`
	Fee                     int64                 `json:"fee"`
	Currency                string                `json:"currency"`
	BillingAmount           sql.NullInt64         `json:"billing_amount"`
	BillingCurrency         sql.NullString        `json:"billing_currency"`
	Status                  string                `json:"status"`
	DeclineReason           sql.NullString        `json:"decline_reason"`
	IsRecurringMerchant     bool                  `json:"is_recurring_merchant"`
	SubscriptionID          uuid.NullUUID         `json:"subscription_id"`
	BalanceAfter            sql.NullString        `json:"balance_after"`
	WebhookReceivedAt       sql.NullTime          `json:"webhook_received_at"`
	RawWebhookData          pqtype.NullRawMessage `json:"raw_webhook_data"`
	Mode                    bool                  `json:"mode"`
	TransactionDate         time.Time             `json:"transaction_date"`
	TransactionTimestamp    time.Time             `json:"transaction_timestamp"`
	CreatedAt               time.Time             `json:"created_at"`
}

type Category struct {
	ID         int32  `json:"id"`
	CategoryID int64  `json:"category_id"`
	Name       string `json:"name"`
}

type ChatMessage struct {
	ID                int64                 `json:"id"`
	TicketID          int64                 `json:"ticket_id"`
	SenderID          int64                 `json:"sender_id"`
	SenderType        string                `json:"sender_type"`
	MessageText       string                `json:"message_text"`
	AiConfidenceScore sql.NullString        `json:"ai_confidence_score"`
	Metadata          pqtype.NullRawMessage `json:"metadata"`
	IsEdited          bool                  `json:"is_edited"`
	EditedAt          sql.NullTime          `json:"edited_at"`
	CreatedAt         time.Time             `json:"created_at"`
}

// Complete audit trail of all conversion executions
type ConversionHistory struct {
	ID                       uuid.UUID      `json:"id"`
	ConversionRuleID         uuid.NullUUID  `json:"conversion_rule_id"`
	UserID                   int64          `json:"user_id"`
	TransactionID            uuid.NullUUID  `json:"transaction_id"`
	SourceCurrency           string         `json:"source_currency"`
	TargetCurrency           string         `json:"target_currency"`
	SourceWalletID           uuid.NullUUID  `json:"source_wallet_id"`
	TargetWalletID           uuid.NullUUID  `json:"target_wallet_id"`
	TriggerRate              sql.NullString `json:"trigger_rate"`
	ExecutedRate             string         `json:"executed_rate"`
	RateDifferencePercentage sql.NullString `json:"rate_difference_percentage"`
	RateProvider             sql.NullString `json:"rate_provider"`
	SourceAmount             string         `json:"source_amount"`
	TargetAmount             string         `json:"target_amount"`
	Fees                     sql.NullString `json:"fees"`
	NetAmount                string         `json:"net_amount"`
	SourceBalanceBefore      sql.NullString `json:"source_balance_before"`
	SourceBalanceAfter       sql.NullString `json:"source_balance_after"`
	TargetBalanceBefore      sql.NullString `json:"target_balance_before"`
	TargetBalanceAfter       sql.NullString `json:"target_balance_after"`
	ExecutionType            string         `json:"execution_type"`
	TriggerType              sql.NullString `json:"trigger_type"`
	Status                   string         `json:"status"`
	FailureReason            sql.NullString `json:"failure_reason"`
	ExecutedAt               time.Time      `json:"executed_at"`
	CreatedAt                time.Time      `json:"created_at"`
}

// User-defined automated conversion rules with rate-based and scheduled triggers
type ConversionRule struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              int64          `json:"user_id"`
	SourceCurrency      string         `json:"source_currency"`
	TargetCurrency      string         `json:"target_currency"`
	SourceWalletID      uuid.NullUUID  `json:"source_wallet_id"`
	TargetWalletID      uuid.NullUUID  `json:"target_wallet_id"`
	TriggerRate         sql.NullString `json:"trigger_rate"`
	TriggerType         string         `json:"trigger_type"`
	TriggerCondition    sql.NullString `json:"trigger_condition"`
	PercentageThreshold sql.NullString `json:"percentage_threshold"`
	ConversionType      string         `json:"conversion_type"`
	FixedAmount         sql.NullString `json:"fixed_amount"`
	Percentage          sql.NullString `json:"percentage"`
	ScheduleFrequency   sql.NullString `json:"schedule_frequency"`
	ScheduleDayOfWeek   sql.NullInt32  `json:"schedule_day_of_week"`
	ScheduleDayOfMonth  sql.NullInt32  `json:"schedule_day_of_month"`
	ScheduleTime        sql.NullTime   `json:"schedule_time"`
	NextExecutionAt     sql.NullTime   `json:"next_execution_at"`
	Timezone            sql.NullString `json:"timezone"`
	Status              string         `json:"status"`
	IsActive            bool           `json:"is_active"`
	LastTriggeredAt     sql.NullTime   `json:"last_triggered_at"`
	LastTriggerRate     sql.NullString `json:"last_trigger_rate"`
	ExecutionCount      int32          `json:"execution_count"`
	MaxExecutions       sql.NullInt32  `json:"max_executions"`
	FailureCount        int32          `json:"failure_count"`
	LastFailureReason   sql.NullString `json:"last_failure_reason"`
	Description         sql.NullString `json:"description"`
	Label               sql.NullString `json:"label"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

type Country struct {
	ID      int32          `json:"id"`
	IsoName sql.NullString `json:"iso_name"`
	Name    sql.NullString `json:"name"`
	FlagUrl sql.NullString `json:"flag_url"`
}

type CryptoAddress struct {
	ID         uuid.UUID      `json:"id"`
	CustomerID sql.NullInt64  `json:"customer_id"`
	AddressID  string         `json:"address_id"`
	Coin       string         `json:"coin"`
	Balance    sql.NullString `json:"balance"`
	Status     string         `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// Metadata for cryptocurrency transactions
type CryptoTransactionMetadatum struct {
	ID                   uuid.UUID      `json:"id"`
	DestinationWallet    uuid.NullUUID  `json:"destination_wallet"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	Coin                 string         `json:"coin"`
	SourceHash           sql.NullString `json:"source_hash"`
	Rate                 sql.NullString `json:"rate"`
	Fees                 sql.NullString `json:"fees"`
	ReceivedAmount       sql.NullString `json:"received_amount"`
	SentAmount           sql.NullString `json:"sent_amount"`
	ServiceProvider      string         `json:"service_provider"`
	OrderID              string         `json:"order_id"`
	ServiceTransactionID sql.NullString `json:"service_transaction_id"`
}

type CryptoTransactionTrail struct {
	ID              uuid.UUID      `json:"id"`
	AddressID       string         `json:"address_id"`
	OrderID         string         `json:"order_id"`
	TransactionHash sql.NullString `json:"transaction_hash"`
	Amount          sql.NullString `json:"amount"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type CryptomusAddress struct {
	ID          uuid.UUID      `json:"id"`
	CustomerID  sql.NullInt64  `json:"customer_id"`
	WalletUuid  string         `json:"wallet_uuid"`
	Uuid        string         `json:"uuid"`
	Address     string         `json:"address"`
	Network     string         `json:"network"`
	Currency    string         `json:"currency"`
	OrderID     string         `json:"order_id"`
	PaymentUrl  sql.NullString `json:"payment_url"`
	CallbackUrl sql.NullString `json:"callback_url"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type CustomSubscriptionsSummary struct {
	UserID                  int64 `json:"user_id"`
	CustomSubscriptionCount int64 `json:"custom_subscription_count"`
	ActiveCustomCount       int64 `json:"active_custom_count"`
	TotalCustomSpend        int64 `json:"total_custom_spend"`
	DailySubscriptions      int64 `json:"daily_subscriptions"`
	MonthlySubscriptions    int64 `json:"monthly_subscriptions"`
	YearlySubscriptions     int64 `json:"yearly_subscriptions"`
}

type DataAirtimePurchaseMetadatum struct {
	ID            uuid.UUID      `json:"id"`
	TransactionID uuid.UUID      `json:"transaction_id"`
	Amount        string         `json:"amount"`
	PointsUsed    sql.NullString `json:"points_used"`
	Type          string         `json:"type"`
	AmountPaid    string         `json:"amount_paid"`
	PointsEarned  sql.NullString `json:"points_earned"`
	PhoneNumber   string         `json:"phone_number"`
	Plan          sql.NullString `json:"plan"`
	Reference     string         `json:"reference"`
	RequestID     string         `json:"request_id"`
	ServiceCharge sql.NullString `json:"service_charge"`
	Status        string         `json:"status"`
	Date          time.Time      `json:"date"`
}

type ElectricityPurchaseMetadatum struct {
	ID              uuid.UUID      `json:"id"`
	TransactionID   uuid.UUID      `json:"transaction_id"`
	Amount          string         `json:"amount"`
	PointsUsed      sql.NullString `json:"points_used"`
	AmountPaid      string         `json:"amount_paid"`
	Token           sql.NullString `json:"token"`
	CustomerName    sql.NullString `json:"customer_name"`
	CustomerAddress sql.NullString `json:"customer_address"`
	Units           sql.NullString `json:"units"`
	MeterNumber     sql.NullString `json:"meter_number"`
	Tax             sql.NullString `json:"tax"`
	Debt            sql.NullString `json:"debt"`
	PointsEarned    sql.NullString `json:"points_earned"`
	PhoneNumber     string         `json:"phone_number"`
	Reference       string         `json:"reference"`
	RequestID       string         `json:"request_id"`
	ServiceCharge   sql.NullString `json:"service_charge"`
	Status          string         `json:"status"`
	Date            time.Time      `json:"date"`
}

type ExchangeRate struct {
	ID            int64     `json:"id"`
	BaseCurrency  string    `json:"base_currency"`
	QuoteCurrency string    `json:"quote_currency"`
	Rate          string    `json:"rate"`
	EffectiveTime time.Time `json:"effective_time"`
	Source        string    `json:"source"`
	CreatedAt     time.Time `json:"created_at"`
}

type FaqDocument struct {
	ID           int64          `json:"id"`
	Title        string         `json:"title"`
	Content      string         `json:"content"`
	Category     sql.NullString `json:"category"`
	Tags         []string       `json:"tags"`
	EmbeddingID  sql.NullString `json:"embedding_id"`
	IsActive     bool           `json:"is_active"`
	ViewCount    int32          `json:"view_count"`
	HelpfulCount int32          `json:"helpful_count"`
	CreatedBy    sql.NullInt64  `json:"created_by"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	Tsv          interface{}    `json:"tsv"`
}

type GiftCard struct {
	ID                       int32                 `json:"id"`
	ProductID                int64                 `json:"product_id"`
	ProductName              sql.NullString        `json:"product_name"`
	DenominationType         sql.NullString        `json:"denomination_type"`
	DiscountPercentage       sql.NullFloat64       `json:"discount_percentage"`
	MaxRecipientDenomination sql.NullFloat64       `json:"max_recipient_denomination"`
	MinRecipientDenomination sql.NullFloat64       `json:"min_recipient_denomination"`
	MaxSenderDenomination    sql.NullFloat64       `json:"max_sender_denomination"`
	MinSenderDenomination    sql.NullFloat64       `json:"min_sender_denomination"`
	Global                   sql.NullBool          `json:"global"`
	Metadata                 pqtype.NullRawMessage `json:"metadata"`
	RecipientCurrencyCode    sql.NullString        `json:"recipient_currency_code"`
	SenderCurrencyCode       sql.NullString        `json:"sender_currency_code"`
	SenderFee                sql.NullFloat64       `json:"sender_fee"`
	SenderFeePercentage      sql.NullFloat64       `json:"sender_fee_percentage"`
	SupportsPreOrder         sql.NullBool          `json:"supports_pre_order"`
	BrandID                  sql.NullInt64         `json:"brand_id"`
	CategoryID               sql.NullInt64         `json:"category_id"`
	CountryID                sql.NullInt64         `json:"country_id"`
}

type GiftCardDenominationMap struct {
	ID                    int32           `json:"id"`
	GiftCardID            sql.NullInt64   `json:"gift_card_id"`
	RecipientCurrencyCode sql.NullString  `json:"recipient_currency_code"`
	SenderCurrencyValue   sql.NullFloat64 `json:"sender_currency_value"`
}

type GiftCardFixedDenomination struct {
	ID           int32           `json:"id"`
	GiftCardID   sql.NullInt64   `json:"gift_card_id"`
	Type         sql.NullString  `json:"type"`
	Denomination sql.NullFloat64 `json:"denomination"`
}

type GiftCardLogoUrl struct {
	ID         int32          `json:"id"`
	GiftCardID sql.NullInt64  `json:"gift_card_id"`
	LogoUrl    sql.NullString `json:"logo_url"`
}

// Metadata for giftcard purchases
type GiftcardTransactionMetadatum struct {
	ID                   uuid.UUID      `json:"id"`
	SourceWallet         uuid.NullUUID  `json:"source_wallet"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	Rate                 sql.NullString `json:"rate"`
	ReceivedAmount       sql.NullString `json:"received_amount"`
	SentAmount           sql.NullString `json:"sent_amount"`
	Fees                 sql.NullString `json:"fees"`
	ServiceProvider      string         `json:"service_provider"`
	ServiceTransactionID sql.NullString `json:"service_transaction_id"`
}

type Kyc struct {
	ID                 int64                 `json:"id"`
	UserID             int32                 `json:"user_id"`
	Status             string                `json:"status"`
	VerificationDate   sql.NullTime          `json:"verification_date"`
	FullName           sql.NullString        `json:"full_name"`
	PhoneNumber        sql.NullString        `json:"phone_number"`
	Email              sql.NullString        `json:"email"`
	Gender             sql.NullString        `json:"gender"`
	SelfieUrl          sql.NullString        `json:"selfie_url"`
	Bvn                sql.NullString        `json:"bvn"`
	Nin                sql.NullString        `json:"nin"`
	IDType             sql.NullString        `json:"id_type"`
	IDNumber           sql.NullString        `json:"id_number"`
	IDImageUrl         sql.NullString        `json:"id_image_url"`
	State              sql.NullString        `json:"state"`
	Lga                sql.NullString        `json:"lga"`
	HouseNumber        sql.NullString        `json:"house_number"`
	StreetName         sql.NullString        `json:"street_name"`
	NearestLandmark    sql.NullString        `json:"nearest_landmark"`
	PostalCode         sql.NullString        `json:"postal_code"`
	Country            sql.NullString        `json:"country"`
	ProofOfAddressType sql.NullString        `json:"proof_of_address_type"`
	ProofOfAddressUrl  sql.NullString        `json:"proof_of_address_url"`
	ProofOfAddressDate sql.NullTime          `json:"proof_of_address_date"`
	CreatedAt          time.Time             `json:"created_at"`
	UpdatedAt          time.Time             `json:"updated_at"`
	AdditionalInfo     pqtype.NullRawMessage `json:"additional_info"`
}

type LedgerEntry struct {
	ID               uuid.UUID     `json:"id"`
	TransactionID    uuid.NullUUID `json:"transaction_id"`
	WalletID         uuid.NullUUID `json:"wallet_id"`
	EntryType        string        `json:"entry_type"`
	Amount           string        `json:"amount"`
	SourceType       string        `json:"source_type"`
	DestinationType  string        `json:"destination_type"`
	CreatedAt        time.Time     `json:"created_at"`
	DeletedAccountID uuid.NullUUID `json:"deleted_account_id"`
}

type Notification struct {
	ID            int64                 `json:"id"`
	SenderAdminID sql.NullInt64         `json:"sender_admin_id"`
	Source        string                `json:"source"`
	Title         sql.NullString        `json:"title"`
	Message       string                `json:"message"`
	Metadata      pqtype.NullRawMessage `json:"metadata"`
	CreatedAt     time.Time             `json:"created_at"`
}

type NotificationRecipient struct {
	ID             int64        `json:"id"`
	NotificationID int64        `json:"notification_id"`
	UserID         int64        `json:"user_id"`
	Read           bool         `json:"read"`
	ReadAt         sql.NullTime `json:"read_at"`
	CreatedAt      time.Time    `json:"created_at"`
}

type Otp struct {
	ID        int64     `json:"id"`
	UserID    int32     `json:"user_id"`
	Otp       string    `json:"otp"`
	Expired   bool      `json:"expired"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Stores user-configured price alerts for cryptocurrency-to-fiat rate monitoring
type PriceAlert struct {
	ID             uuid.UUID `json:"id"`
	UserID         int64     `json:"user_id"`
	SourceCurrency string    `json:"source_currency"`
	TargetCurrency string    `json:"target_currency"`
	// Type of price condition: above, below, equals, percent_up, percent_down, range, breakout
	AlertCondition string `json:"alert_condition"`
	// Alert behavior: one_time (trigger once), recurring (trigger multiple times), trailing (dynamic stop-loss/buy)
	AlertType        string         `json:"alert_type"`
	Priority         string         `json:"priority"`
	TargetRate       sql.NullString `json:"target_rate"`
	PercentageChange sql.NullString `json:"percentage_change"`
	RangeMin         sql.NullString `json:"range_min"`
	RangeMax         sql.NullString `json:"range_max"`
	BaselineRate     sql.NullString `json:"baseline_rate"`
	// For trailing alerts: percentage distance from peak/trough (e.g., 5 for 5%)
	TrailingDistance sql.NullString `json:"trailing_distance"`
	MaxTrailingRate  sql.NullString `json:"max_trailing_rate"`
	MinTrailingRate  sql.NullString `json:"min_trailing_rate"`
	Description      sql.NullString `json:"description"`
	Label            sql.NullString `json:"label"`
	IsActive         bool           `json:"is_active"`
	TriggeredCount   int32          `json:"triggered_count"`
	LastTriggeredAt  sql.NullTime   `json:"last_triggered_at"`
	LastCheckedAt    sql.NullTime   `json:"last_checked_at"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	NotifyPush       bool           `json:"notify_push"`
	NotifyInApp      bool           `json:"notify_in_app"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
}

type ProofOfAddressImage struct {
	ID         int32        `json:"id"`
	UserID     int32        `json:"user_id"`
	Filename   string       `json:"filename"`
	ProofType  string       `json:"proof_type"`
	ImageData  []byte       `json:"image_data"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	Verified   bool         `json:"verified"`
	VerifiedAt sql.NullTime `json:"verified_at"`
}

// Generated QR codes for receiving crypto via Cryptomus with auto-conversion to fiat
type QrCode struct {
	ID                  uuid.UUID      `json:"id"`
	Token               uuid.UUID      `json:"token"`
	UserID              int64          `json:"user_id"`
	QrType              string         `json:"qr_type"`
	CurrencyPreference  string         `json:"currency_preference"`
	ConversionMode      string         `json:"conversion_mode"`
	Network             string         `json:"network"`
	CryptoCurrency      string         `json:"crypto_currency"`
	CryptomusAddressID  uuid.NullUUID  `json:"cryptomus_address_id"`
	LinkedWalletID      uuid.NullUUID  `json:"linked_wallet_id"`
	LinkedBankAccountID uuid.NullUUID  `json:"linked_bank_account_id"`
	Amount              string         `json:"amount"`
	QrCodeData          string         `json:"qr_code_data"`
	QrCodeImageUrl      sql.NullString `json:"qr_code_image_url"`
	Description         sql.NullString `json:"description"`
	Label               sql.NullString `json:"label"`
	Status              string         `json:"status"`
	UsageLimit          sql.NullInt32  `json:"usage_limit"`
	UsageCount          int32          `json:"usage_count"`
	ExpiresAt           sql.NullTime   `json:"expires_at"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	LastUsedAt          sql.NullTime   `json:"last_used_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

// Complete lifecycle tracking of QR payments: Received → Converted → Paid Out
type QrTransaction struct {
	ID                     uuid.UUID             `json:"id"`
	QrCodeID               uuid.UUID             `json:"qr_code_id"`
	TransactionID          uuid.NullUUID         `json:"transaction_id"`
	UserID                 int64                 `json:"user_id"`
	CryptomusTransactionID sql.NullString        `json:"cryptomus_transaction_id"`
	CryptomusOrderID       sql.NullString        `json:"cryptomus_order_id"`
	CryptomusUuid          sql.NullString        `json:"cryptomus_uuid"`
	OrderID                sql.NullString        `json:"order_id"`
	CryptomusAddressID     uuid.NullUUID         `json:"cryptomus_address_id"`
	WebhookData            pqtype.NullRawMessage `json:"webhook_data"`
	CryptoCurrency         string                `json:"crypto_currency"`
	CryptoNetwork          string                `json:"crypto_network"`
	CryptoAmount           string                `json:"crypto_amount"`
	CryptoAmountUsd        sql.NullString        `json:"crypto_amount_usd"`
	TransactionHash        sql.NullString        `json:"transaction_hash"`
	ConversionRate         sql.NullString        `json:"conversion_rate"`
	FiatCurrency           sql.NullString        `json:"fiat_currency"`
	FiatAmount             sql.NullString        `json:"fiat_amount"`
	ConversionFees         string                `json:"conversion_fees"`
	PlatformFees           string                `json:"platform_fees"`
	NetworkFees            string                `json:"network_fees"`
	TotalFees              string                `json:"total_fees"`
	NetAmount              sql.NullString        `json:"net_amount"`
	BankAccountID          uuid.NullUUID         `json:"bank_account_id"`
	BankAccountName        sql.NullString        `json:"bank_account_name"`
	BankAccountNumber      sql.NullString        `json:"bank_account_number"`
	BankCode               sql.NullString        `json:"bank_code"`
	PayoutReference        sql.NullString        `json:"payout_reference"`
	PayoutProvider         sql.NullString        `json:"payout_provider"`
	PayoutProviderResponse pqtype.NullRawMessage `json:"payout_provider_response"`
	Status                 string                `json:"status"`
	PaymentReceivedAt      sql.NullTime          `json:"payment_received_at"`
	PaymentConfirmedAt     sql.NullTime          `json:"payment_confirmed_at"`
	ConversionStartedAt    sql.NullTime          `json:"conversion_started_at"`
	ConversionCompletedAt  sql.NullTime          `json:"conversion_completed_at"`
	PayoutInitiatedAt      sql.NullTime          `json:"payout_initiated_at"`
	PayoutCompletedAt      sql.NullTime          `json:"payout_completed_at"`
	FailureReason          sql.NullString        `json:"failure_reason"`
	FailureStage           sql.NullString        `json:"failure_stage"`
	RetryCount             int32                 `json:"retry_count"`
	LastRetryAt            sql.NullTime          `json:"last_retry_at"`
	MaxRetries             sql.NullInt32         `json:"max_retries"`
	CreatedAt              time.Time             `json:"created_at"`
	UpdatedAt              time.Time             `json:"updated_at"`
}

// Automatic rate mark-up rules for different VIP levels
type RateAdjustmentRule struct {
	ID                  uuid.UUID      `json:"id"`
	RuleName            string         `json:"rule_name"`
	RuleDescription     sql.NullString `json:"rule_description"`
	VipLevelID          uuid.NullUUID  `json:"vip_level_id"`
	IsGlobalRule        bool           `json:"is_global_rule"`
	SourceCurrency      string         `json:"source_currency"`
	TargetCurrency      string         `json:"target_currency"`
	AdjustmentType      string         `json:"adjustment_type"`
	AdjustmentValue     string         `json:"adjustment_value"`
	AdjustmentDirection string         `json:"adjustment_direction"`
	Priority            int32          `json:"priority"`
	MinConversionAmount sql.NullString `json:"min_conversion_amount"`
	MaxConversionAmount sql.NullString `json:"max_conversion_amount"`
	ValidFrom           sql.NullTime   `json:"valid_from"`
	ValidUntil          sql.NullTime   `json:"valid_until"`
	IsActive            bool           `json:"is_active"`
	CreatedBy           sql.NullInt64  `json:"created_by"`
	UpdatedBy           sql.NullInt64  `json:"updated_by"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

// Admin notifications for rate-related events
type RateAdminNotification struct {
	ID                uuid.UUID             `json:"id"`
	NotificationType  string                `json:"notification_type"`
	Severity          string                `json:"severity"`
	Title             string                `json:"title"`
	Message           string                `json:"message"`
	RelatedEntityType sql.NullString        `json:"related_entity_type"`
	RelatedEntityID   sql.NullString        `json:"related_entity_id"`
	Metadata          pqtype.NullRawMessage `json:"metadata"`
	IsRead            bool                  `json:"is_read"`
	ReadAt            sql.NullTime          `json:"read_at"`
	ReadBy            sql.NullInt64         `json:"read_by"`
	CreatedAt         time.Time             `json:"created_at"`
}

// Audit trail for all rate adjustments and applications
type RateChangeHistory struct {
	ID               uuid.UUID      `json:"id"`
	SourceCurrency   string         `json:"source_currency"`
	TargetCurrency   string         `json:"target_currency"`
	BaseRate         string         `json:"base_rate"`
	AdjustedRate     string         `json:"adjusted_rate"`
	AdjustmentAmount string         `json:"adjustment_amount"`
	RuleID           uuid.NullUUID  `json:"rule_id"`
	RuleName         sql.NullString `json:"rule_name"`
	VipLevelID       uuid.NullUUID  `json:"vip_level_id"`
	VipLevelName     sql.NullString `json:"vip_level_name"`
	RateProvider     sql.NullString `json:"rate_provider"`
	AppliedToUserID  sql.NullInt64  `json:"applied_to_user_id"`
	ConversionID     uuid.NullUUID  `json:"conversion_id"`
	ChangeReason     sql.NullString `json:"change_reason"`
	ChangedBy        sql.NullInt64  `json:"changed_by"`
	CreatedAt        time.Time      `json:"created_at"`
}

type RecentCriticalEvent struct {
	ID            int64              `json:"id"`
	EventCategory AuditEventCategory `json:"event_category"`
	EventType     string             `json:"event_type"`
	Severity      AuditSeverity      `json:"severity"`
	ActorEmail    sql.NullString     `json:"actor_email"`
	EntityType    string             `json:"entity_type"`
	EntityID      string             `json:"entity_id"`
	Description   string             `json:"description"`
	IpAddress     pqtype.Inet        `json:"ip_address"`
	CreatedAt     time.Time          `json:"created_at"`
}

type RedeemInstruction struct {
	ID                  int32          `json:"id"`
	GiftCardID          sql.NullInt64  `json:"gift_card_id"`
	Concise             sql.NullString `json:"concise"`
	DetailedInstruction sql.NullString `json:"detailed_instruction"`
}

type Referral struct {
	ID          int64     `json:"id"`
	UserID      int32     `json:"user_id"`
	ReferralKey string    `json:"referral_key"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ReferralConfig struct {
	ID                                    int64     `json:"id"`
	ReferralAmount                        string    `json:"referral_amount"`
	ReferralPercentageEarnedPerConversion string    `json:"referral_percentage_earned_per_conversion"`
	Singleton                             bool      `json:"singleton"`
	CreatedAt                             time.Time `json:"created_at"`
	UpdatedAt                             time.Time `json:"updated_at"`
}

type ReferralEarning struct {
	ID               int64     `json:"id"`
	UserID           int32     `json:"user_id"`
	TotalEarned      string    `json:"total_earned"`
	AvailableBalance string    `json:"available_balance"`
	WithdrawnBalance string    `json:"withdrawn_balance"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type ReferralEntry struct {
	ID             int64        `json:"id"`
	ReferralKey    string       `json:"referral_key"`
	Referrer       int32        `json:"referrer"`
	Referee        int32        `json:"referee"`
	ReferralDetail string       `json:"referral_detail"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

type ReferralTransaction struct {
	ID              int64         `json:"id"`
	UserID          int32         `json:"user_id"`
	Amount          string        `json:"amount"`
	TransactionID   uuid.NullUUID `json:"transaction_id"`
	TransactionType string        `json:"transaction_type"`
	Reference       string        `json:"reference"`
	Status          string        `json:"status"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

// Admin-defined reward rate configurations
type RewardConfiguration struct {
	ID         int64  `json:"id"`
	ConfigName string `json:"config_name"`
	// Percentage of transaction amount earned as reward (e.g., 0.01 = 1%)
	RewardRate string `json:"reward_rate"`
	// Type of transaction eligible for rewards (e.g., bill_payment)
	TransactionType string `json:"transaction_type"`
	// Minimum transaction amount to earn rewards (Naira)
	MinTransactionAmount string `json:"min_transaction_amount"`
	// Maximum reward points per single transaction
	MaxPointsPerTransaction sql.NullString `json:"max_points_per_transaction"`
	IsActive                bool           `json:"is_active"`
	ValidFrom               time.Time      `json:"valid_from"`
	ValidUntil              sql.NullTime   `json:"valid_until"`
	CreatedBy               sql.NullInt32  `json:"created_by"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

// Detailed records of reward point redemptions on bill payments
type RewardRedemption struct {
	ID                       int64     `json:"id"`
	RewardTransactionID      int64     `json:"reward_transaction_id"`
	UserID                   int32     `json:"user_id"`
	BillPaymentTransactionID uuid.UUID `json:"bill_payment_transaction_id"`
	// Reward points redeemed (₦ value)
	PointsRedeemed string `json:"points_redeemed"`
	// Discount applied to bill payment (₦ value)
	DiscountAmount     string         `json:"discount_amount"`
	OriginalBillAmount string         `json:"original_bill_amount"`
	FinalAmountPaid    string         `json:"final_amount_paid"`
	ServiceType        sql.NullString `json:"service_type"`
	ServiceProvider    sql.NullString `json:"service_provider"`
	RedeemedAt         time.Time      `json:"redeemed_at"`
	CreatedAt          time.Time      `json:"created_at"`
}

// Complete history of reward points earned and redeemed
type RewardTransaction struct {
	ID            int64         `json:"id"`
	UserID        int64         `json:"user_id"`
	TransactionID uuid.NullUUID `json:"transaction_id"`
	// Type: earned or redeemed
	TransactionType       string         `json:"transaction_type"`
	SourceTransactionType sql.NullString `json:"source_transaction_type"`
	TransactionAmount     sql.NullString `json:"transaction_amount"`
	// Reward points involved in transaction
	PointsAmount string `json:"points_amount"`
	// Equivalent Naira value (1 point = ₦1)
	NairaValue     string         `json:"naira_value"`
	RewardConfigID sql.NullInt64  `json:"reward_config_id"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	// User reward balance after this transaction
	BalanceAfter string                `json:"balance_after"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

// Metadata for service purchases like airtime and TV subscriptions
type ServicesMetadatum struct {
	ID                   uuid.UUID      `json:"id"`
	SourceWallet         uuid.NullUUID  `json:"source_wallet"`
	Rate                 sql.NullString `json:"rate"`
	ReceivedAmount       sql.NullString `json:"received_amount"`
	SentAmount           sql.NullString `json:"sent_amount"`
	Fees                 sql.NullString `json:"fees"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	ServiceType          string         `json:"service_type"`
	ServiceProvider      sql.NullString `json:"service_provider"`
	ServiceID            sql.NullString `json:"service_id"`
	ServiceStatus        string         `json:"service_status"`
	ServiceTransactionID sql.NullString `json:"service_transaction_id"`
}

type SubscriptionMerchant struct {
	ID               int64          `json:"id"`
	MerchantName     string         `json:"merchant_name"`
	DisplayName      string         `json:"display_name"`
	Aliases          []string       `json:"aliases"`
	Category         string         `json:"category"`
	Subcategory      sql.NullString `json:"subcategory"`
	LogoUrl          sql.NullString `json:"logo_url"`
	Website          sql.NullString `json:"website"`
	Description      sql.NullString `json:"description"`
	MerchantCountry  sql.NullString `json:"merchant_country"`
	TypicalIntervals []int32        `json:"typical_intervals"`
	TypicalAmounts   []int64        `json:"typical_amounts"`
	MccCodes         []string       `json:"mcc_codes"`
	MatchConfidence  string         `json:"match_confidence"`
	IsActive         bool           `json:"is_active"`
	AutoDetect       bool           `json:"auto_detect"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type SubscriptionReminder struct {
	ID             uuid.UUID      `json:"id"`
	SubscriptionID uuid.UUID      `json:"subscription_id"`
	UserID         int64          `json:"user_id"`
	ReminderType   string         `json:"reminder_type"`
	ScheduledFor   time.Time      `json:"scheduled_for"`
	SentAt         sql.NullTime   `json:"sent_at"`
	Title          string         `json:"title"`
	Message        string         `json:"message"`
	ActionUrl      sql.NullString `json:"action_url"`
	Channels       []string       `json:"channels"`
	Status         string         `json:"status"`
	CreatedAt      time.Time      `json:"created_at"`
}

type SubscriptionSystemSetting struct {
	ID           int64          `json:"id"`
	SettingKey   string         `json:"setting_key"`
	SettingValue string         `json:"setting_value"`
	SettingType  string         `json:"setting_type"`
	Description  sql.NullString `json:"description"`
	Category     string         `json:"category"`
	IsActive     bool           `json:"is_active"`
	UpdatedBy    sql.NullInt64  `json:"updated_by"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type SupportAdmin struct {
	ID                   int64     `json:"id"`
	UserID               int64     `json:"user_id"`
	Status               string    `json:"status"`
	ActiveTicketCount    int32     `json:"active_ticket_count"`
	MaxConcurrentTickets int32     `json:"max_concurrent_tickets"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

// Metadata for wallet-to-wallet transfers and swaps
type SwapTransferMetadatum struct {
	ID                uuid.UUID      `json:"id"`
	Currency          string         `json:"currency"`
	TransactionID     uuid.UUID      `json:"transaction_id"`
	TransferType      string         `json:"transfer_type"`
	Description       sql.NullString `json:"description"`
	SourceWallet      uuid.NullUUID  `json:"source_wallet"`
	DestinationWallet uuid.NullUUID  `json:"destination_wallet"`
	UserTag           sql.NullString `json:"user_tag"`
	Rate              sql.NullString `json:"rate"`
	Fees              sql.NullString `json:"fees"`
	ReceivedAmount    sql.NullString `json:"received_amount"`
	SentAmount        sql.NullString `json:"sent_amount"`
}

type SwiftWallet struct {
	ID         uuid.UUID      `json:"id"`
	CustomerID int64          `json:"customer_id"`
	Type       string         `json:"type"`
	Currency   string         `json:"currency"`
	Balance    sql.NullString `json:"balance"`
	Status     string         `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// System-wide metrics for monitoring alert system health
type SystemAlertMetric struct {
	TotalAlerts         int64   `json:"total_alerts"`
	ActiveAlerts        int64   `json:"active_alerts"`
	InactiveAlerts      int64   `json:"inactive_alerts"`
	UniqueUsers         int64   `json:"unique_users"`
	UniqueCurrencyPairs int64   `json:"unique_currency_pairs"`
	AvgTriggersPerAlert float64 `json:"avg_triggers_per_alert"`
	OneTimeAlerts       int64   `json:"one_time_alerts"`
	RecurringAlerts     int64   `json:"recurring_alerts"`
	TrailingAlerts      int64   `json:"trailing_alerts"`
	CriticalAlerts      int64   `json:"critical_alerts"`
	HighPriorityAlerts  int64   `json:"high_priority_alerts"`
	ExpiredAlerts       int64   `json:"expired_alerts"`
}

type SystemSetting struct {
	ID                      int32        `json:"id"`
	RewardsEnabled          sql.NullBool `json:"rewards_enabled"`
	VaultsEnabled           sql.NullBool `json:"vaults_enabled"`
	SmartConversionsEnabled sql.NullBool `json:"smart_conversions_enabled"`
	RapidRampEnabled        sql.NullBool `json:"rapid_ramp_enabled"`
	CreatedAt               sql.NullTime `json:"created_at"`
	UpdatedAt               sql.NullTime `json:"updated_at"`
}

type Ticket struct {
	ID                  int64          `json:"id"`
	UserID              int64          `json:"user_id"`
	Status              string         `json:"status"`
	AssignedTo          sql.NullInt64  `json:"assigned_to"`
	EscalationReason    sql.NullString `json:"escalation_reason"`
	Priority            string         `json:"priority"`
	Category            sql.NullString `json:"category"`
	ResolvedAt          sql.NullTime   `json:"resolved_at"`
	FirstResponseAt     sql.NullTime   `json:"first_response_at"`
	AverageResponseTime sql.NullInt32  `json:"average_response_time"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type TicketAssignmentHistory struct {
	ID           int64          `json:"id"`
	TicketID     int64          `json:"ticket_id"`
	AssignedFrom sql.NullInt64  `json:"assigned_from"`
	AssignedTo   sql.NullInt64  `json:"assigned_to"`
	AssignedBy   int64          `json:"assigned_by"`
	Reason       sql.NullString `json:"reason"`
	CreatedAt    time.Time      `json:"created_at"`
}

// Core transaction table storing all financial transactions
type Transaction struct {
	ID                   uuid.UUID      `json:"id"`
	UserID               int64          `json:"user_id"`
	Type                 string         `json:"type"`
	Description          sql.NullString `json:"description"`
	TransactionFlow      string         `json:"transaction_flow"`
	Amount               string         `json:"amount"`
	IdempotencyKey       string         `json:"idempotency_key"`
	TFrom                string         `json:"t_from"`
	TTo                  string         `json:"t_to"`
	Direction            string         `json:"direction"`
	Currency             string         `json:"currency"`
	AmountUsd            string         `json:"amount_usd"`
	Status               string         `json:"status"`
	RiskScore            sql.NullInt32  `json:"risk_score"`
	FraudStatus          sql.NullString `json:"fraud_status"`
	FlaggedAt            sql.NullTime   `json:"flagged_at"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedFromAccountID uuid.NullUUID  `json:"deleted_from_account_id"`
	DeletedToAccountID   uuid.NullUUID  `json:"deleted_to_account_id"`
}

type TransactionFee struct {
	ID              int64          `json:"id"`
	TransactionType string         `json:"transaction_type"`
	FeePercentage   sql.NullString `json:"fee_percentage"`
	MaxFee          sql.NullString `json:"max_fee"`
	FlatFee         sql.NullString `json:"flat_fee"`
	EffectiveTime   time.Time      `json:"effective_time"`
	Source          string         `json:"source"`
	CreatedAt       time.Time      `json:"created_at"`
}

// Tracks daily transaction streak metrics per user
type TransactionStreak struct {
	ID                   int64        `json:"id"`
	UserID               int64        `json:"user_id"`
	CurrentStreak        int32        `json:"current_streak"`
	BestStreak           int32        `json:"best_streak"`
	TotalTransactionDays int32        `json:"total_transaction_days"`
	LastTransactionDate  sql.NullTime `json:"last_transaction_date"`
	StreakStartedAt      sql.NullTime `json:"streak_started_at"`
	CreatedAt            time.Time    `json:"created_at"`
	UpdatedAt            time.Time    `json:"updated_at"`
}

// Audit log of all streak changes
type TransactionStreakHistory struct {
	ID              int64                 `json:"id"`
	UserID          int64                 `json:"user_id"`
	TransactionID   uuid.NullUUID         `json:"transaction_id"`
	PreviousStreak  int32                 `json:"previous_streak"`
	NewStreak       int32                 `json:"new_streak"`
	TransactionDate time.Time             `json:"transaction_date"`
	EventType       string                `json:"event_type"`
	Metadata        pqtype.NullRawMessage `json:"metadata"`
	CreatedAt       time.Time             `json:"created_at"`
}

type User struct {
	ID                           int64          `json:"id"`
	AvatarUrl                    sql.NullString `json:"avatar_url"`
	AvatarBlob                   []byte         `json:"avatar_blob"`
	FirstName                    sql.NullString `json:"first_name"`
	LastName                     sql.NullString `json:"last_name"`
	Email                        string         `json:"email"`
	HashedPassword               sql.NullString `json:"hashed_password"`
	HashedPasscode               sql.NullString `json:"hashed_passcode"`
	HashedPin                    sql.NullString `json:"hashed_pin"`
	PhoneNumber                  string         `json:"phone_number"`
	Role                         string         `json:"role"`
	Verified                     bool           `json:"verified"`
	IsKycVerified                bool           `json:"is_kyc_verified"`
	BridgecardVerificationStatus sql.NullString `json:"bridgecard_verification_status"`
	BridgecardCardholderID       sql.NullString `json:"bridgecard_cardholder_id"`
	IsRapidRampOn                bool           `json:"is_rapid_ramp_on"`
	HasCompletedFirstConversion  sql.NullBool   `json:"has_completed_first_conversion"`
	FirstConversionID            uuid.NullUUID  `json:"first_conversion_id"`
	FirstConversionAt            sql.NullTime   `json:"first_conversion_at"`
	Frozen                       sql.NullBool   `json:"frozen"`
	FrozenReason                 sql.NullString `json:"frozen_reason"`
	FrozenAt                     sql.NullTime   `json:"frozen_at"`
	CreatedAt                    time.Time      `json:"created_at"`
	UpdatedAt                    time.Time      `json:"updated_at"`
	DeletedAt                    sql.NullTime   `json:"deleted_at"`
	HasWallets                   bool           `json:"has_wallets"`
	UserTag                      sql.NullString `json:"user_tag"`
	FreshChatID                  sql.NullString `json:"fresh_chat_id"`
	IsActive                     bool           `json:"is_active"`
	TwofaSecret                  sql.NullString `json:"twofa_secret"`
	TwofaEnabled                 sql.NullBool   `json:"twofa_enabled"`
	// Current available reward points balance (₦ value)
	RewardBalance string `json:"reward_balance"`
	// Lifetime total reward points earned
	TotalRewardEarned string `json:"total_reward_earned"`
	// Lifetime total reward points redeemed
	TotalRewardRedeemed    string         `json:"total_reward_redeemed"`
	TotalConversionVolume  sql.NullString `json:"total_conversion_volume"`
	TotalTransactionVolume sql.NullString `json:"total_transaction_volume"`
	CurrentVipLevelID      uuid.NullUUID  `json:"current_vip_level_id"`
}

type UserActivityTimeline struct {
	UserID      sql.NullInt64  `json:"user_id"`
	Email       sql.NullString `json:"email"`
	EventType   string         `json:"event_type"`
	EntityType  string         `json:"entity_type"`
	EntityID    string         `json:"entity_id"`
	Action      string         `json:"action"`
	Description string         `json:"description"`
	Success     bool           `json:"success"`
	IpAddress   pqtype.Inet    `json:"ip_address"`
	CreatedAt   time.Time      `json:"created_at"`
}

// Aggregated statistics per user for alert usage
type UserAlertStat struct {
	UserID          int64       `json:"user_id"`
	TotalAlerts     int64       `json:"total_alerts"`
	ActiveAlerts    int64       `json:"active_alerts"`
	PausedAlerts    int64       `json:"paused_alerts"`
	TotalTriggers   int64       `json:"total_triggers"`
	UniquePairs     int64       `json:"unique_pairs"`
	LastTriggerTime interface{} `json:"last_trigger_time"`
}

// Junction table tracking which badges users have earned
type UserBadge struct {
	ID             int64     `json:"id"`
	UserID         int64     `json:"user_id"`
	BadgeID        int64     `json:"badge_id"`
	EarnedAt       time.Time `json:"earned_at"`
	StreakAtUnlock int32     `json:"streak_at_unlock"`
}

type UserReferral struct {
	ID           int32     `json:"id"`
	ReferrerID   int32     `json:"referrer_id"`
	RefereeID    int32     `json:"referee_id"`
	EarnedAmount string    `json:"earned_amount"`
	CreatedAt    time.Time `json:"created_at"`
	Status       string    `json:"status"`
}

type UserSubscription struct {
	ID                      uuid.UUID      `json:"id"`
	UserID                  int64          `json:"user_id"`
	CardID                  uuid.UUID      `json:"card_id"`
	MerchantID              sql.NullInt64  `json:"merchant_id"`
	MerchantName            string         `json:"merchant_name"`
	DisplayName             string         `json:"display_name"`
	Category                sql.NullString `json:"category"`
	Amount                  int64          `json:"amount"`
	Currency                string         `json:"currency"`
	BillingIntervalDays     int32          `json:"billing_interval_days"`
	FirstChargeDate         time.Time      `json:"first_charge_date"`
	LastChargeDate          time.Time      `json:"last_charge_date"`
	NextEstimatedChargeDate time.Time      `json:"next_estimated_charge_date"`
	Status                  string         `json:"status"`
	ConfidenceScore         string         `json:"confidence_score"`
	TotalCharges            int32          `json:"total_charges"`
	FailedCharges           int32          `json:"failed_charges"`
	LastFailedDate          sql.NullTime   `json:"last_failed_date"`
	LastFailureReason       sql.NullString `json:"last_failure_reason"`
	ReminderEnabled         bool           `json:"reminder_enabled"`
	ReminderDaysBefore      int32          `json:"reminder_days_before"`
	UserConfirmed           bool           `json:"user_confirmed"`
	CustomName              sql.NullString `json:"custom_name"`
	IsCustom                bool           `json:"is_custom"`
	CustomBillingCycle      sql.NullString `json:"custom_billing_cycle"`
	CustomAmountOverride    bool           `json:"custom_amount_override"`
	AutoTopupBufferPercent  sql.NullString `json:"auto_topup_buffer_percent"`
	CustomReminderTiming    sql.NullInt32  `json:"custom_reminder_timing"`
	Notes                   sql.NullString `json:"notes"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	CancelledAt             sql.NullTime   `json:"cancelled_at"`
}

type UserSubscriptionSummary struct {
	UserID              int64       `json:"user_id"`
	ActiveSubscriptions int64       `json:"active_subscriptions"`
	FailedSubscriptions int64       `json:"failed_subscriptions"`
	TotalMonthlySpend   int64       `json:"total_monthly_spend"`
	Categories          interface{} `json:"categories"`
	NextChargeDate      interface{} `json:"next_charge_date"`
}

type UserToken struct {
	ID         int32          `json:"id"`
	UserID     int64          `json:"user_id"`
	Token      string         `json:"token"`
	Provider   string         `json:"provider"`
	DeviceUuid sql.NullString `json:"device_uuid"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// Tracks individual transaction volumes for VIP level evaluation
type UserTransactionVolume struct {
	ID              int64     `json:"id"`
	UserID          int64     `json:"user_id"`
	TransactionType string    `json:"transaction_type"`
	Amount          string    `json:"amount"`
	Currency        string    `json:"currency"`
	TransactionDate time.Time `json:"transaction_date"`
	DailyVolume     string    `json:"daily_volume"`
	DailyCount      int32     `json:"daily_count"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// User VIP level assignments and tier progression tracking
type UserVipAssignment struct {
	ID                    uuid.UUID     `json:"id"`
	UserID                int64         `json:"user_id"`
	VipLevelID            uuid.UUID     `json:"vip_level_id"`
	AssignedAt            time.Time     `json:"assigned_at"`
	AssignedBy            sql.NullInt64 `json:"assigned_by"`
	AssignmentType        string        `json:"assignment_type"`
	TotalConversionVolume string        `json:"total_conversion_volume"`
	IsActive              bool          `json:"is_active"`
	ExpiresAt             sql.NullTime  `json:"expires_at"`
	CreatedAt             time.Time     `json:"created_at"`
	UpdatedAt             time.Time     `json:"updated_at"`
}

// Historical record of VIP level changes
type UserVipLevelHistory struct {
	ID                      uuid.UUID      `json:"id"`
	UserID                  int64          `json:"user_id"`
	PreviousLevelID         uuid.NullUUID  `json:"previous_level_id"`
	PreviousLevelName       sql.NullString `json:"previous_level_name"`
	NewLevelID              uuid.NullUUID  `json:"new_level_id"`
	NewLevelName            sql.NullString `json:"new_level_name"`
	ChangeReason            string         `json:"change_reason"`
	ChangeType              string         `json:"change_type"`
	TotalVolumeAtChange     sql.NullString `json:"total_volume_at_change"`
	ConversionCountAtChange sql.NullInt32  `json:"conversion_count_at_change"`
	ChangedBy               sql.NullInt64  `json:"changed_by"`
	ChangedByType           sql.NullString `json:"changed_by_type"`
	ChangedAt               time.Time      `json:"changed_at"`
}

// Cached aggregated metrics for fast VIP level queries
type UserVipMetricsCache struct {
	UserID                 int64          `json:"user_id"`
	TotalTransactionVolume string         `json:"total_transaction_volume"`
	TotalConversionCount   int32          `json:"total_conversion_count"`
	MonthlyVolume          string         `json:"monthly_volume"`
	MonthlyCount           int32          `json:"monthly_count"`
	WeeklyVolume           string         `json:"weekly_volume"`
	WeeklyCount            int32          `json:"weekly_count"`
	CurrentVipLevelID      uuid.NullUUID  `json:"current_vip_level_id"`
	CurrentVipLevelName    sql.NullString `json:"current_vip_level_name"`
	CurrentVipLevelRank    sql.NullInt32  `json:"current_vip_level_rank"`
	LastTransactionDate    sql.NullTime   `json:"last_transaction_date"`
	FirstTransactionDate   sql.NullTime   `json:"first_transaction_date"`
	LastCalculatedAt       time.Time      `json:"last_calculated_at"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type VaultSaving struct {
	ID                   uuid.UUID             `json:"id"`
	UserID               int64                 `json:"user_id"`
	VaultName            string                `json:"vault_name"`
	Description          sql.NullString        `json:"description"`
	GoalAmount           sql.NullString        `json:"goal_amount"`
	CurrentBalance       sql.NullString        `json:"current_balance"`
	Category             string                `json:"category"`
	Currency             string                `json:"currency"`
	AutoSaveEnabled      bool                  `json:"auto_save_enabled"`
	AutoSaveFrequency    sql.NullString        `json:"auto_save_frequency"`
	AutoSaveAmount       sql.NullString        `json:"auto_save_amount"`
	NextAutoSave         sql.NullTime          `json:"next_auto_save"`
	RecurringRule        pqtype.NullRawMessage `json:"recurring_rule"`
	TotalYieldEarned     sql.NullString        `json:"total_yield_earned"`
	NextYieldCalculation sql.NullTime          `json:"next_yield_calculation"`
	LastYieldCalculation sql.NullTime          `json:"last_yield_calculation"`
	Status               string                `json:"status"`
	VaultType            string                `json:"vault_type"`
	CreatedAt            time.Time             `json:"created_at"`
	UpdatedAt            time.Time             `json:"updated_at"`
	CompletedAt          sql.NullTime          `json:"completed_at"`
}

type VaultTransaction struct {
	ID                uuid.UUID             `json:"id"`
	UserID            int64                 `json:"user_id"`
	VaultID           uuid.UUID             `json:"vault_id"`
	TransactionType   string                `json:"transaction_type"`
	TransactionID     uuid.NullUUID         `json:"transaction_id"`
	Amount            string                `json:"amount"`
	Currency          string                `json:"currency"`
	SourceWallet      uuid.NullUUID         `json:"source_wallet"`
	DestinationWallet uuid.NullUUID         `json:"destination_wallet"`
	BalanceBefore     string                `json:"balance_before"`
	BalanceAfter      string                `json:"balance_after"`
	Reference         sql.NullString        `json:"reference"`
	Description       sql.NullString        `json:"description"`
	Metadata          pqtype.NullRawMessage `json:"metadata"`
	Status            sql.NullString        `json:"status"`
	Requires2fa       sql.NullBool          `json:"requires_2fa"`
	TwoFaVerifiedAt   sql.NullTime          `json:"two_fa_verified_at"`
	CompletedAt       sql.NullTime          `json:"completed_at"`
	CreatedAt         time.Time             `json:"created_at"`
}

type VaultYield struct {
	ID                     uuid.UUID      `json:"id"`
	UserID                 int64          `json:"user_id"`
	VaultID                uuid.UUID      `json:"vault_id"`
	YieldAmount            string         `json:"yield_amount"`
	YieldRate              string         `json:"yield_rate"`
	CalculationPeriodStart time.Time      `json:"calculation_period_start"`
	CalculationPeriodEnd   time.Time      `json:"calculation_period_end"`
	VaultBalanceSnapshot   string         `json:"vault_balance_snapshot"`
	Status                 sql.NullString `json:"status"`
	CreditedAt             sql.NullTime   `json:"credited_at"`
	CreatedAt              time.Time      `json:"created_at"`
}

type VaultYieldConfig struct {
	ID                 uuid.UUID      `json:"id"`
	Currency           string         `json:"currency"`
	ApyRate            string         `json:"apy_rate"`
	MinBalanceForYield string         `json:"min_balance_for_yield"`
	CompoundFrequency  sql.NullString `json:"compound_frequency"`
	IsActive           bool           `json:"is_active"`
	EffectiveFrom      time.Time      `json:"effective_from"`
	EffectiveUntil     sql.NullTime   `json:"effective_until"`
	Notes              sql.NullString `json:"notes"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

// VIP tier definitions with transaction volume thresholds
type VipLevel struct {
	ID                  uuid.UUID      `json:"id"`
	LevelName           string         `json:"level_name"`
	LevelCode           string         `json:"level_code"`
	LevelRank           int32          `json:"level_rank"`
	MinConversionVolume string         `json:"min_conversion_volume"`
	Description         sql.NullString `json:"description"`
	BenefitsDescription sql.NullString `json:"benefits_description"`
	BadgeColor          sql.NullString `json:"badge_color"`
	IconUrl             sql.NullString `json:"icon_url"`
	IsActive            bool           `json:"is_active"`
	IsDefault           bool           `json:"is_default"`
	CreatedBy           sql.NullInt64  `json:"created_by"`
	UpdatedBy           sql.NullInt64  `json:"updated_by"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

type VirtualCard struct {
	ID                      uuid.UUID      `json:"id"`
	UserID                  int64          `json:"user_id"`
	CardPlanID              int64          `json:"card_plan_id"`
	BridgecardCardID        string         `json:"bridgecard_card_id"`
	CardName                string         `json:"card_name"`
	CardColor               sql.NullString `json:"card_color"`
	Currency                string         `json:"currency"`
	CurrentMonthSpend       sql.NullInt64  `json:"current_month_spend"`
	CurrentDaySpend         sql.NullInt64  `json:"current_day_spend"`
	SpendingMonth           sql.NullString `json:"spending_month"`
	SpendingDay             sql.NullString `json:"spending_day"`
	Status                  string         `json:"status"`
	StatusReason            sql.NullString `json:"status_reason"`
	AutoTopupEnabled        bool           `json:"auto_topup_enabled"`
	AutoTopupThreshold      sql.NullInt64  `json:"auto_topup_threshold"`
	AutoTopupAmount         sql.NullInt64  `json:"auto_topup_amount"`
	AutoTopupSourceWalletID uuid.NullUUID  `json:"auto_topup_source_wallet_id"`
	NextBillingDate         sql.NullTime   `json:"next_billing_date"`
	LastBillingDate         sql.NullTime   `json:"last_billing_date"`
	LastTransactionAt       sql.NullTime   `json:"last_transaction_at"`
	TotalTransactionsCount  int64          `json:"total_transactions_count"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
	TerminatedAt            sql.NullTime   `json:"terminated_at"`
}

// Current distribution of users across VIP levels
type VwVipDistribution struct {
	VipLevelID       uuid.UUID   `json:"vip_level_id"`
	LevelName        string      `json:"level_name"`
	LevelCode        string      `json:"level_code"`
	LevelRank        int32       `json:"level_rank"`
	UserCount        int64       `json:"user_count"`
	TotalVolume      interface{} `json:"total_volume"`
	AvgVolumePerUser interface{} `json:"avg_volume_per_user"`
	MonthlyVolume    interface{} `json:"monthly_volume"`
	Percentage       float64     `json:"percentage"`
}

// Users eligible for VIP level upgrades
type VwVipUpgradeCandidate struct {
	UserID                 int64          `json:"user_id"`
	Email                  string         `json:"email"`
	PhoneNumber            string         `json:"phone_number"`
	CurrentVipLevelName    sql.NullString `json:"current_vip_level_name"`
	CurrentVipLevelRank    sql.NullInt32  `json:"current_vip_level_rank"`
	TotalTransactionVolume string         `json:"total_transaction_volume"`
	TotalConversionCount   int32          `json:"total_conversion_count"`
	MonthlyVolume          string         `json:"monthly_volume"`
	EligibleLevelName      string         `json:"eligible_level_name"`
	EligibleLevelRank      int32          `json:"eligible_level_rank"`
	EligibleLevelID        uuid.UUID      `json:"eligible_level_id"`
	VolumeToNextLevel      int32          `json:"volume_to_next_level"`
}

type WalletTransferMetadatum struct {
	ID            uuid.UUID      `json:"id"`
	Currency      string         `json:"currency"`
	Type          string         `json:"type"`
	TransactionID uuid.UUID      `json:"transaction_id"`
	Sender        string         `json:"sender"`
	Recipient     string         `json:"recipient"`
	ServiceCharge sql.NullString `json:"service_charge"`
	Amount        string         `json:"amount"`
	AmountPaid    sql.NullString `json:"amount_paid"`
	BonusEarned   sql.NullString `json:"bonus_earned"`
	Reference     string         `json:"reference"`
	Description   string         `json:"description"`
	Status        string         `json:"status"`
	Date          time.Time      `json:"date"`
}
