// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"user_id"`
	Action    string         `json:"action"`
	CreatedAt time.Time      `json:"created_at"`
	Ip        sql.NullString `json:"ip"`
	UserAgent sql.NullString `json:"user_agent"`
}

type AutoTopupLog struct {
	ID                  uuid.UUID             `json:"id"`
	UserID              int64                 `json:"user_id"`
	CardID              uuid.UUID             `json:"card_id"`
	SubscriptionID      uuid.NullUUID         `json:"subscription_id"`
	TopupAmount         string                `json:"topup_amount"`
	WalletBalanceBefore sql.NullString        `json:"wallet_balance_before"`
	WalletBalanceAfter  sql.NullString        `json:"wallet_balance_after"`
	CardBalanceBefore   sql.NullString        `json:"card_balance_before"`
	CardBalanceAfter    sql.NullString        `json:"card_balance_after"`
	Status              string                `json:"status"`
	FailureReason       sql.NullString        `json:"failure_reason"`
	TransactionID       uuid.NullUUID         `json:"transaction_id"`
	Metadata            pqtype.NullRawMessage `json:"metadata"`
	CreatedAt           sql.NullTime          `json:"created_at"`
}

type AutoTopupSetting struct {
	ID                       uuid.UUID      `json:"id"`
	UserID                   int64          `json:"user_id"`
	Enabled                  sql.NullBool   `json:"enabled"`
	DefaultCardID            uuid.NullUUID  `json:"default_card_id"`
	TopupStrategy            sql.NullString `json:"topup_strategy"`
	FixedAmount              sql.NullString `json:"fixed_amount"`
	BufferPercentage         sql.NullString `json:"buffer_percentage"`
	BufferFixedAmount        sql.NullString `json:"buffer_fixed_amount"`
	MinWalletBalanceRequired sql.NullString `json:"min_wallet_balance_required"`
	CheckTimeHoursBefore     sql.NullInt32  `json:"check_time_hours_before"`
	MaxTopupPerDay           sql.NullString `json:"max_topup_per_day"`
	DailyTopupCount          sql.NullInt32  `json:"daily_topup_count"`
	LastTopupDate            sql.NullTime   `json:"last_topup_date"`
	CreatedAt                sql.NullTime   `json:"created_at"`
	UpdatedAt                sql.NullTime   `json:"updated_at"`
}

type Beneficiary struct {
	ID              uuid.UUID     `json:"id"`
	UserID          sql.NullInt64 `json:"user_id"`
	BankCode        string        `json:"bank_code"`
	AccountNumber   string        `json:"account_number"`
	BeneficiaryName string        `json:"beneficiary_name"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

type Brand struct {
	ID        int32          `json:"id"`
	BrandID   int64          `json:"brand_id"`
	BrandName sql.NullString `json:"brand_name"`
}

type CardFundingHistory struct {
	ID            uuid.UUID             `json:"id"`
	UserID        int64                 `json:"user_id"`
	CardID        uuid.UUID             `json:"card_id"`
	WalletID      uuid.UUID             `json:"wallet_id"`
	Amount        string                `json:"amount"`
	Currency      string                `json:"currency"`
	FundingType   string                `json:"funding_type"`
	TransactionID uuid.NullUUID         `json:"transaction_id"`
	LedgerEntryID uuid.NullUUID         `json:"ledger_entry_id"`
	Status        string                `json:"status"`
	FailureReason sql.NullString        `json:"failure_reason"`
	Metadata      pqtype.NullRawMessage `json:"metadata"`
	CreatedAt     sql.NullTime          `json:"created_at"`
}

type Category struct {
	ID         int32  `json:"id"`
	CategoryID int64  `json:"category_id"`
	Name       string `json:"name"`
}

type Country struct {
	ID      int32          `json:"id"`
	IsoName sql.NullString `json:"iso_name"`
	Name    sql.NullString `json:"name"`
	FlagUrl sql.NullString `json:"flag_url"`
}

type CryptoAddress struct {
	ID         uuid.UUID      `json:"id"`
	CustomerID sql.NullInt64  `json:"customer_id"`
	AddressID  string         `json:"address_id"`
	Coin       string         `json:"coin"`
	Balance    sql.NullString `json:"balance"`
	Status     string         `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// Metadata for cryptocurrency transactions
type CryptoTransactionMetadatum struct {
	ID                   uuid.UUID      `json:"id"`
	DestinationWallet    uuid.NullUUID  `json:"destination_wallet"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	Coin                 string         `json:"coin"`
	SourceHash           sql.NullString `json:"source_hash"`
	Rate                 sql.NullString `json:"rate"`
	Fees                 sql.NullString `json:"fees"`
	ReceivedAmount       sql.NullString `json:"received_amount"`
	SentAmount           sql.NullString `json:"sent_amount"`
	ServiceProvider      string         `json:"service_provider"`
	ServiceTransactionID sql.NullString `json:"service_transaction_id"`
}

type CryptoTransactionTrail struct {
	ID              uuid.UUID      `json:"id"`
	AddressID       string         `json:"address_id"`
	TransactionHash string         `json:"transaction_hash"`
	Amount          sql.NullString `json:"amount"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type CryptomusAddress struct {
	ID          uuid.UUID      `json:"id"`
	CustomerID  sql.NullInt64  `json:"customer_id"`
	WalletUuid  string         `json:"wallet_uuid"`
	Uuid        string         `json:"uuid"`
	Address     string         `json:"address"`
	Network     string         `json:"network"`
	Currency    string         `json:"currency"`
	OrderID     string         `json:"order_id"`
	PaymentUrl  sql.NullString `json:"payment_url"`
	CallbackUrl sql.NullString `json:"callback_url"`
	Status      string         `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ExchangeRate struct {
	ID            int64     `json:"id"`
	BaseCurrency  string    `json:"base_currency"`
	QuoteCurrency string    `json:"quote_currency"`
	Rate          string    `json:"rate"`
	EffectiveTime time.Time `json:"effective_time"`
	Source        string    `json:"source"`
	CreatedAt     time.Time `json:"created_at"`
}

// Metadata for fiat currency withdrawals
type FiatWithdrawalMetadatum struct {
	ID                   uuid.UUID      `json:"id"`
	SourceWallet         uuid.NullUUID  `json:"source_wallet"`
	Rate                 sql.NullString `json:"rate"`
	ReceivedAmount       sql.NullString `json:"received_amount"`
	SentAmount           sql.NullString `json:"sent_amount"`
	Fees                 sql.NullString `json:"fees"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	AccountName          sql.NullString `json:"account_name"`
	BankCode             sql.NullString `json:"bank_code"`
	AccountNumber        sql.NullString `json:"account_number"`
	ServiceProvider      sql.NullString `json:"service_provider"`
	ServiceTransactionID sql.NullString `json:"service_transaction_id"`
}

type GiftCard struct {
	ID                       int32                 `json:"id"`
	ProductID                int64                 `json:"product_id"`
	ProductName              sql.NullString        `json:"product_name"`
	DenominationType         sql.NullString        `json:"denomination_type"`
	DiscountPercentage       sql.NullFloat64       `json:"discount_percentage"`
	MaxRecipientDenomination sql.NullFloat64       `json:"max_recipient_denomination"`
	MinRecipientDenomination sql.NullFloat64       `json:"min_recipient_denomination"`
	MaxSenderDenomination    sql.NullFloat64       `json:"max_sender_denomination"`
	MinSenderDenomination    sql.NullFloat64       `json:"min_sender_denomination"`
	Global                   sql.NullBool          `json:"global"`
	Metadata                 pqtype.NullRawMessage `json:"metadata"`
	RecipientCurrencyCode    sql.NullString        `json:"recipient_currency_code"`
	SenderCurrencyCode       sql.NullString        `json:"sender_currency_code"`
	SenderFee                sql.NullFloat64       `json:"sender_fee"`
	SenderFeePercentage      sql.NullFloat64       `json:"sender_fee_percentage"`
	SupportsPreOrder         sql.NullBool          `json:"supports_pre_order"`
	BrandID                  sql.NullInt64         `json:"brand_id"`
	CategoryID               sql.NullInt64         `json:"category_id"`
	CountryID                sql.NullInt64         `json:"country_id"`
}

type GiftCardDenominationMap struct {
	ID                    int32           `json:"id"`
	GiftCardID            sql.NullInt64   `json:"gift_card_id"`
	RecipientCurrencyCode sql.NullString  `json:"recipient_currency_code"`
	SenderCurrencyValue   sql.NullFloat64 `json:"sender_currency_value"`
}

type GiftCardFixedDenomination struct {
	ID           int32           `json:"id"`
	GiftCardID   sql.NullInt64   `json:"gift_card_id"`
	Type         sql.NullString  `json:"type"`
	Denomination sql.NullFloat64 `json:"denomination"`
}

type GiftCardLogoUrl struct {
	ID         int32          `json:"id"`
	GiftCardID sql.NullInt64  `json:"gift_card_id"`
	LogoUrl    sql.NullString `json:"logo_url"`
}

// Metadata for giftcard purchases
type GiftcardTransactionMetadatum struct {
	ID                   uuid.UUID      `json:"id"`
	SourceWallet         uuid.NullUUID  `json:"source_wallet"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	Rate                 sql.NullString `json:"rate"`
	ReceivedAmount       sql.NullString `json:"received_amount"`
	SentAmount           sql.NullString `json:"sent_amount"`
	Fees                 sql.NullString `json:"fees"`
	ServiceProvider      string         `json:"service_provider"`
	ServiceTransactionID sql.NullString `json:"service_transaction_id"`
}

type Kyc struct {
	ID                    int64                 `json:"id"`
	UserID                int32                 `json:"user_id"`
	Tier                  int32                 `json:"tier"`
	DailyTransferLimitNgn sql.NullString        `json:"daily_transfer_limit_ngn"`
	WalletBalanceLimitNgn sql.NullString        `json:"wallet_balance_limit_ngn"`
	Status                string                `json:"status"`
	VerificationDate      sql.NullTime          `json:"verification_date"`
	FullName              sql.NullString        `json:"full_name"`
	PhoneNumber           sql.NullString        `json:"phone_number"`
	Email                 sql.NullString        `json:"email"`
	Bvn                   sql.NullString        `json:"bvn"`
	Nin                   sql.NullString        `json:"nin"`
	Gender                sql.NullString        `json:"gender"`
	SelfieUrl             sql.NullString        `json:"selfie_url"`
	IDType                sql.NullString        `json:"id_type"`
	IDNumber              sql.NullString        `json:"id_number"`
	IDImageUrl            sql.NullString        `json:"id_image_url"`
	State                 sql.NullString        `json:"state"`
	Lga                   sql.NullString        `json:"lga"`
	HouseNumber           sql.NullString        `json:"house_number"`
	StreetName            sql.NullString        `json:"street_name"`
	NearestLandmark       sql.NullString        `json:"nearest_landmark"`
	ProofOfAddressType    sql.NullString        `json:"proof_of_address_type"`
	ProofOfAddressUrl     sql.NullString        `json:"proof_of_address_url"`
	ProofOfAddressDate    sql.NullTime          `json:"proof_of_address_date"`
	CreatedAt             time.Time             `json:"created_at"`
	UpdatedAt             time.Time             `json:"updated_at"`
	AdditionalInfo        pqtype.NullRawMessage `json:"additional_info"`
}

type LedgerEntry struct {
	ID               uuid.UUID     `json:"id"`
	TransactionID    uuid.NullUUID `json:"transaction_id"`
	WalletID         uuid.NullUUID `json:"wallet_id"`
	Type             string        `json:"type"`
	Amount           string        `json:"amount"`
	Balance          string        `json:"balance"`
	CreatedAt        time.Time     `json:"created_at"`
	SourceType       string        `json:"source_type"`
	DestinationType  string        `json:"destination_type"`
	DeletedAccountID uuid.NullUUID `json:"deleted_account_id"`
}

type Notification struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	Message   string        `json:"message"`
	Read      sql.NullBool  `json:"read"`
	CreatedAt sql.NullTime  `json:"created_at"`
	Title     string        `json:"title"`
}

type Otp struct {
	ID        int64     `json:"id"`
	UserID    int32     `json:"user_id"`
	Otp       string    `json:"otp"`
	Expired   bool      `json:"expired"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProofOfAddressImage struct {
	ID         int32        `json:"id"`
	UserID     int32        `json:"user_id"`
	Filename   string       `json:"filename"`
	ProofType  string       `json:"proof_type"`
	ImageData  []byte       `json:"image_data"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	Verified   bool         `json:"verified"`
	VerifiedAt sql.NullTime `json:"verified_at"`
}

type RedeemInstruction struct {
	ID                  int32          `json:"id"`
	GiftCardID          sql.NullInt64  `json:"gift_card_id"`
	Concise             sql.NullString `json:"concise"`
	DetailedInstruction sql.NullString `json:"detailed_instruction"`
}

type Referral struct {
	ID          int64     `json:"id"`
	UserID      int32     `json:"user_id"`
	ReferralKey string    `json:"referral_key"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ReferralEarning struct {
	ID               int64     `json:"id"`
	UserID           int32     `json:"user_id"`
	TotalEarned      string    `json:"total_earned"`
	AvailableBalance string    `json:"available_balance"`
	WithdrawnBalance string    `json:"withdrawn_balance"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type ReferralEntry struct {
	ID             int64        `json:"id"`
	ReferralKey    string       `json:"referral_key"`
	Referrer       int32        `json:"referrer"`
	Referee        int32        `json:"referee"`
	ReferralDetail string       `json:"referral_detail"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	DeletedAt      sql.NullTime `json:"deleted_at"`
}

// Admin-defined reward rate configurations
type RewardConfiguration struct {
	ID         int64  `json:"id"`
	ConfigName string `json:"config_name"`
	// Percentage of transaction amount earned as reward (e.g., 0.01 = 1%)
	RewardRate string `json:"reward_rate"`
	// Type of transaction eligible for rewards (e.g., bill_payment)
	TransactionType string `json:"transaction_type"`
	// Minimum transaction amount to earn rewards (Naira)
	MinTransactionAmount string `json:"min_transaction_amount"`
	// Maximum reward points per single transaction
	MaxPointsPerTransaction sql.NullString `json:"max_points_per_transaction"`
	IsActive                bool           `json:"is_active"`
	ValidFrom               time.Time      `json:"valid_from"`
	ValidUntil              sql.NullTime   `json:"valid_until"`
	CreatedBy               sql.NullInt32  `json:"created_by"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}

// Detailed records of reward point redemptions on bill payments
type RewardRedemption struct {
	ID                       int64     `json:"id"`
	RewardTransactionID      int64     `json:"reward_transaction_id"`
	UserID                   int32     `json:"user_id"`
	BillPaymentTransactionID uuid.UUID `json:"bill_payment_transaction_id"`
	// Reward points redeemed (₦ value)
	PointsRedeemed string `json:"points_redeemed"`
	// Discount applied to bill payment (₦ value)
	DiscountAmount     string         `json:"discount_amount"`
	OriginalBillAmount string         `json:"original_bill_amount"`
	FinalAmountPaid    string         `json:"final_amount_paid"`
	ServiceType        sql.NullString `json:"service_type"`
	ServiceProvider    sql.NullString `json:"service_provider"`
	RedeemedAt         time.Time      `json:"redeemed_at"`
	CreatedAt          time.Time      `json:"created_at"`
}

// Complete history of reward points earned and redeemed
type RewardTransaction struct {
	ID            int64         `json:"id"`
	UserID        int64         `json:"user_id"`
	TransactionID uuid.NullUUID `json:"transaction_id"`
	// Type: earned or redeemed
	TransactionType       string         `json:"transaction_type"`
	SourceTransactionType sql.NullString `json:"source_transaction_type"`
	TransactionAmount     sql.NullString `json:"transaction_amount"`
	// Reward points involved in transaction
	PointsAmount string `json:"points_amount"`
	// Equivalent Naira value (1 point = ₦1)
	NairaValue     string         `json:"naira_value"`
	RewardConfigID sql.NullInt64  `json:"reward_config_id"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	// User reward balance after this transaction
	BalanceAfter string                `json:"balance_after"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

// Metadata for service purchases like airtime and TV subscriptions
type ServicesMetadatum struct {
	ID                   uuid.UUID      `json:"id"`
	SourceWallet         uuid.NullUUID  `json:"source_wallet"`
	Rate                 sql.NullString `json:"rate"`
	ReceivedAmount       sql.NullString `json:"received_amount"`
	SentAmount           sql.NullString `json:"sent_amount"`
	Fees                 sql.NullString `json:"fees"`
	TransactionID        uuid.UUID      `json:"transaction_id"`
	ServiceType          string         `json:"service_type"`
	ServiceProvider      sql.NullString `json:"service_provider"`
	ServiceID            sql.NullString `json:"service_id"`
	ServiceStatus        string         `json:"service_status"`
	ServiceTransactionID sql.NullString `json:"service_transaction_id"`
}

type Subscription struct {
	ID                       uuid.UUID             `json:"id"`
	UserID                   int64                 `json:"user_id"`
	CardID                   uuid.UUID             `json:"card_id"`
	MerchantID               uuid.NullUUID         `json:"merchant_id"`
	MerchantName             string                `json:"merchant_name"`
	Amount                   string                `json:"amount"`
	Currency                 string                `json:"currency"`
	FirstTransactionDate     time.Time             `json:"first_transaction_date"`
	LastTransactionDate      sql.NullTime          `json:"last_transaction_date"`
	NextEstimatedRenewalDate time.Time             `json:"next_estimated_renewal_date"`
	RenewalIntervalDays      sql.NullInt32         `json:"renewal_interval_days"`
	Status                   string                `json:"status"`
	ConfidenceScore          sql.NullString        `json:"confidence_score"`
	TotalSpend               sql.NullString        `json:"total_spend"`
	TransactionCount         sql.NullInt32         `json:"transaction_count"`
	FailedPaymentCount       sql.NullInt32         `json:"failed_payment_count"`
	LastFailedPaymentDate    sql.NullTime          `json:"last_failed_payment_date"`
	CancellationDate         sql.NullTime          `json:"cancellation_date"`
	CancellationReason       sql.NullString        `json:"cancellation_reason"`
	Metadata                 pqtype.NullRawMessage `json:"metadata"`
	CreatedAt                sql.NullTime          `json:"created_at"`
	UpdatedAt                sql.NullTime          `json:"updated_at"`
}

type SubscriptionCategory struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	IconUrl      sql.NullString `json:"icon_url"`
	DisplayOrder sql.NullInt32  `json:"display_order"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type SubscriptionMerchant struct {
	ID                 uuid.UUID             `json:"id"`
	MerchantName       string                `json:"merchant_name"`
	MerchantIdentifier string                `json:"merchant_identifier"`
	CategoryID         uuid.NullUUID         `json:"category_id"`
	LogoUrl            sql.NullString        `json:"logo_url"`
	Description        sql.NullString        `json:"description"`
	WebsiteUrl         sql.NullString        `json:"website_url"`
	DefaultRenewalDays sql.NullInt32         `json:"default_renewal_days"`
	CommonAmounts      []string              `json:"common_amounts"`
	IsActive           sql.NullBool          `json:"is_active"`
	Metadata           pqtype.NullRawMessage `json:"metadata"`
	CreatedAt          sql.NullTime          `json:"created_at"`
	UpdatedAt          sql.NullTime          `json:"updated_at"`
}

type SubscriptionNotification struct {
	ID               uuid.UUID             `json:"id"`
	UserID           int64                 `json:"user_id"`
	SubscriptionID   uuid.NullUUID         `json:"subscription_id"`
	NotificationType string                `json:"notification_type"`
	Title            string                `json:"title"`
	Message          string                `json:"message"`
	ActionUrl        sql.NullString        `json:"action_url"`
	Priority         sql.NullString        `json:"priority"`
	SentAt           sql.NullTime          `json:"sent_at"`
	ReadAt           sql.NullTime          `json:"read_at"`
	ClickedAt        sql.NullTime          `json:"clicked_at"`
	DeliveryStatus   sql.NullString        `json:"delivery_status"`
	DeliveryChannel  sql.NullString        `json:"delivery_channel"`
	Metadata         pqtype.NullRawMessage `json:"metadata"`
	CreatedAt        sql.NullTime          `json:"created_at"`
}

type SubscriptionSpendingAnalytic struct {
	UserID               int64          `json:"user_id"`
	Month                int64          `json:"month"`
	CategoryName         sql.NullString `json:"category_name"`
	ActiveSubscriptions  int64          `json:"active_subscriptions"`
	TotalTransactions    int64          `json:"total_transactions"`
	TotalSpent           int64          `json:"total_spent"`
	FailedTransactions   int64          `json:"failed_transactions"`
	AvgTransactionAmount float64        `json:"avg_transaction_amount"`
}

type SubscriptionTransaction struct {
	ID                       uuid.UUID             `json:"id"`
	SubscriptionID           uuid.UUID             `json:"subscription_id"`
	TransactionID            uuid.NullUUID         `json:"transaction_id"`
	FlutterwaveTransactionID sql.NullString        `json:"flutterwave_transaction_id"`
	Amount                   string                `json:"amount"`
	Currency                 string                `json:"currency"`
	TransactionDate          time.Time             `json:"transaction_date"`
	Status                   string                `json:"status"`
	FailureReason            sql.NullString        `json:"failure_reason"`
	MerchantDescriptor       sql.NullString        `json:"merchant_descriptor"`
	IsRenewal                sql.NullBool          `json:"is_renewal"`
	Metadata                 pqtype.NullRawMessage `json:"metadata"`
	CreatedAt                sql.NullTime          `json:"created_at"`
}

// Metadata for wallet-to-wallet transfers and swaps
type SwapTransferMetadatum struct {
	ID                uuid.UUID      `json:"id"`
	Currency          string         `json:"currency"`
	TransactionID     uuid.UUID      `json:"transaction_id"`
	TransferType      string         `json:"transfer_type"`
	Description       sql.NullString `json:"description"`
	SourceWallet      uuid.NullUUID  `json:"source_wallet"`
	DestinationWallet uuid.NullUUID  `json:"destination_wallet"`
	UserTag           sql.NullString `json:"user_tag"`
	Rate              sql.NullString `json:"rate"`
	Fees              sql.NullString `json:"fees"`
	ReceivedAmount    sql.NullString `json:"received_amount"`
	SentAmount        sql.NullString `json:"sent_amount"`
}

type SwiftWallet struct {
	ID         uuid.UUID      `json:"id"`
	CustomerID int64          `json:"customer_id"`
	Type       string         `json:"type"`
	Currency   string         `json:"currency"`
	Balance    sql.NullString `json:"balance"`
	Status     string         `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// Core transaction table storing all financial transactions
type Transaction struct {
	ID                   uuid.UUID      `json:"id"`
	Type                 string         `json:"type"`
	Description          sql.NullString `json:"description"`
	TransactionFlow      sql.NullString `json:"transaction_flow"`
	Status               string         `json:"status"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedFromAccountID uuid.NullUUID  `json:"deleted_from_account_id"`
	DeletedToAccountID   uuid.NullUUID  `json:"deleted_to_account_id"`
}

type TransactionFee struct {
	ID              int64          `json:"id"`
	TransactionType string         `json:"transaction_type"`
	FeePercentage   sql.NullString `json:"fee_percentage"`
	MaxFee          sql.NullString `json:"max_fee"`
	FlatFee         sql.NullString `json:"flat_fee"`
	EffectiveTime   time.Time      `json:"effective_time"`
	Source          string         `json:"source"`
	CreatedAt       time.Time      `json:"created_at"`
}

type User struct {
	ID             int64          `json:"id"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	AvatarBlob     []byte         `json:"avatar_blob"`
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	Email          string         `json:"email"`
	HashedPassword sql.NullString `json:"hashed_password"`
	HashedPasscode sql.NullString `json:"hashed_passcode"`
	HashedPin      sql.NullString `json:"hashed_pin"`
	PhoneNumber    string         `json:"phone_number"`
	Role           string         `json:"role"`
	Verified       bool           `json:"verified"`
	IsKycVerified  bool           `json:"is_kyc_verified"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	HasWallets     bool           `json:"has_wallets"`
	UserTag        sql.NullString `json:"user_tag"`
	FreshChatID    sql.NullString `json:"fresh_chat_id"`
	IsActive       bool           `json:"is_active"`
	TwofaSecret    sql.NullString `json:"twofa_secret"`
	TwofaEnabled   sql.NullBool   `json:"twofa_enabled"`
	// Current available reward points balance (₦ value)
	RewardBalance string `json:"reward_balance"`
	// Lifetime total reward points earned
	TotalRewardEarned string `json:"total_reward_earned"`
	// Lifetime total reward points redeemed
	TotalRewardRedeemed string `json:"total_reward_redeemed"`
}

type UserReferral struct {
	ID           int32     `json:"id"`
	ReferrerID   int32     `json:"referrer_id"`
	RefereeID    int32     `json:"referee_id"`
	EarnedAmount string    `json:"earned_amount"`
	CreatedAt    time.Time `json:"created_at"`
	Status       string    `json:"status"`
}

type UserToken struct {
	ID         int32          `json:"id"`
	UserID     int64          `json:"user_id"`
	Token      string         `json:"token"`
	Provider   string         `json:"provider"`
	DeviceUuid sql.NullString `json:"device_uuid"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type VaultSaving struct {
	ID                   uuid.UUID             `json:"id"`
	UserID               int64                 `json:"user_id"`
	VaultName            string                `json:"vault_name"`
	Description          sql.NullString        `json:"description"`
	GoalAmount           sql.NullString        `json:"goal_amount"`
	CurrentBalance       sql.NullString        `json:"current_balance"`
	Category             string                `json:"category"`
	Currency             string                `json:"currency"`
	AutoSaveEnabled      bool                  `json:"auto_save_enabled"`
	AutoSaveFrequency    sql.NullString        `json:"auto_save_frequency"`
	AutoSaveAmount       sql.NullString        `json:"auto_save_amount"`
	NextAutoSave         sql.NullTime          `json:"next_auto_save"`
	RecurringRule        pqtype.NullRawMessage `json:"recurring_rule"`
	TotalYieldEarned     sql.NullString        `json:"total_yield_earned"`
	NextYieldCalculation sql.NullTime          `json:"next_yield_calculation"`
	LastYieldCalculation sql.NullTime          `json:"last_yield_calculation"`
	Status               string                `json:"status"`
	VaultType            string                `json:"vault_type"`
	CreatedAt            time.Time             `json:"created_at"`
	UpdatedAt            time.Time             `json:"updated_at"`
	CompletedAt          sql.NullTime          `json:"completed_at"`
}

type VaultTransaction struct {
	ID                uuid.UUID             `json:"id"`
	UserID            int64                 `json:"user_id"`
	VaultID           uuid.UUID             `json:"vault_id"`
	TransactionType   string                `json:"transaction_type"`
	Amount            string                `json:"amount"`
	Currency          string                `json:"currency"`
	SourceWallet      uuid.NullUUID         `json:"source_wallet"`
	DestinationWallet uuid.NullUUID         `json:"destination_wallet"`
	BalanceBefore     string                `json:"balance_before"`
	BalanceAfter      string                `json:"balance_after"`
	Reference         sql.NullString        `json:"reference"`
	Description       sql.NullString        `json:"description"`
	Metadata          pqtype.NullRawMessage `json:"metadata"`
	Status            sql.NullString        `json:"status"`
	Requires2fa       sql.NullBool          `json:"requires_2fa"`
	TwoFaVerifiedAt   sql.NullTime          `json:"two_fa_verified_at"`
	CompletedAt       sql.NullTime          `json:"completed_at"`
	CreatedAt         time.Time             `json:"created_at"`
}

type VaultYield struct {
	ID                     uuid.UUID      `json:"id"`
	UserID                 int64          `json:"user_id"`
	VaultID                uuid.UUID      `json:"vault_id"`
	YieldAmount            string         `json:"yield_amount"`
	YieldRate              string         `json:"yield_rate"`
	CalculationPeriodStart time.Time      `json:"calculation_period_start"`
	CalculationPeriodEnd   time.Time      `json:"calculation_period_end"`
	VaultBalanceSnapshot   string         `json:"vault_balance_snapshot"`
	Status                 sql.NullString `json:"status"`
	CreditedAt             sql.NullTime   `json:"credited_at"`
	CreatedAt              time.Time      `json:"created_at"`
}

type VaultYieldConfig struct {
	ID                 uuid.UUID      `json:"id"`
	Currency           string         `json:"currency"`
	ApyRate            string         `json:"apy_rate"`
	MinBalanceForYield string         `json:"min_balance_for_yield"`
	CompoundFrequency  sql.NullString `json:"compound_frequency"`
	IsActive           bool           `json:"is_active"`
	EffectiveFrom      time.Time      `json:"effective_from"`
	EffectiveUntil     sql.NullTime   `json:"effective_until"`
	Notes              sql.NullString `json:"notes"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type VirtualCard struct {
	ID                uuid.UUID             `json:"id"`
	UserID            int64                 `json:"user_id"`
	FlutterwaveCardID string                `json:"flutterwave_card_id"`
	CardPanLast4      sql.NullString        `json:"card_pan_last4"`
	CardBrand         sql.NullString        `json:"card_brand"`
	CardType          sql.NullString        `json:"card_type"`
	Balance           string                `json:"balance"`
	Currency          string                `json:"currency"`
	NameOnCard        sql.NullString        `json:"name_on_card"`
	ExpiryMonth       sql.NullString        `json:"expiry_month"`
	ExpiryYear        sql.NullString        `json:"expiry_year"`
	CvvEncrypted      sql.NullString        `json:"cvv_encrypted"`
	Status            string                `json:"status"`
	BillingAddress    pqtype.NullRawMessage `json:"billing_address"`
	Metadata          pqtype.NullRawMessage `json:"metadata"`
	IsFrozen          sql.NullBool          `json:"is_frozen"`
	FreezeReason      sql.NullString        `json:"freeze_reason"`
	CreatedAt         sql.NullTime          `json:"created_at"`
	UpdatedAt         sql.NullTime          `json:"updated_at"`
	DeletedAt         sql.NullTime          `json:"deleted_at"`
}

type WithdrawalRequest struct {
	ID        int64     `json:"id"`
	UserID    int32     `json:"user_id"`
	Amount    string    `json:"amount"`
	WalletID  uuid.UUID `json:"wallet_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
