// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price_alert.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createAlertTriggerHistory = `-- name: CreateAlertTriggerHistory :one
INSERT INTO alert_trigger_history (
    alert_id,
    user_id,
    current_rate,
    previous_rate,
    change_percent,
    alert_condition,
    target_rate,
    push_notification_sent,
    in_app_notification_sent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, alert_id, user_id, triggered_at, current_rate, previous_rate, change_percent, alert_condition, target_rate, push_notification_sent, in_app_notification_sent, notification_error, created_at
`

type CreateAlertTriggerHistoryParams struct {
	AlertID               uuid.UUID      `json:"alert_id"`
	UserID                uuid.UUID      `json:"user_id"`
	CurrentRate           string         `json:"current_rate"`
	PreviousRate          sql.NullString `json:"previous_rate"`
	ChangePercent         sql.NullString `json:"change_percent"`
	AlertCondition        string         `json:"alert_condition"`
	TargetRate            sql.NullString `json:"target_rate"`
	PushNotificationSent  sql.NullBool   `json:"push_notification_sent"`
	InAppNotificationSent sql.NullBool   `json:"in_app_notification_sent"`
}

func (q *Queries) CreateAlertTriggerHistory(ctx context.Context, arg CreateAlertTriggerHistoryParams) (AlertTriggerHistory, error) {
	row := q.db.QueryRowContext(ctx, createAlertTriggerHistory,
		arg.AlertID,
		arg.UserID,
		arg.CurrentRate,
		arg.PreviousRate,
		arg.ChangePercent,
		arg.AlertCondition,
		arg.TargetRate,
		arg.PushNotificationSent,
		arg.InAppNotificationSent,
	)
	var i AlertTriggerHistory
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.UserID,
		&i.TriggeredAt,
		&i.CurrentRate,
		&i.PreviousRate,
		&i.ChangePercent,
		&i.AlertCondition,
		&i.TargetRate,
		&i.PushNotificationSent,
		&i.InAppNotificationSent,
		&i.NotificationError,
		&i.CreatedAt,
	)
	return i, err
}

const createPriceAlert = `-- name: CreatePriceAlert :one
INSERT INTO price_alerts (
    user_id,
    source_currency,
    target_currency,
    alert_condition,
    alert_type,
    priority,
    target_rate,
    percentage_change,
    range_min,
    range_max,
    baseline_rate,
    trailing_distance,
    max_trailing_rate,
    min_trailing_rate,
    description,
    label,
    expires_at,
    notify_push,
    notify_in_app
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, user_id, source_currency, target_currency, alert_condition, alert_type, priority, target_rate, percentage_change, range_min, range_max, baseline_rate, trailing_distance, max_trailing_rate, min_trailing_rate, description, label, is_active, triggered_count, last_triggered_at, last_checked_at, expires_at, notify_push, notify_in_app, created_at, updated_at, deleted_at
`

type CreatePriceAlertParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	SourceCurrency   string         `json:"source_currency"`
	TargetCurrency   string         `json:"target_currency"`
	AlertCondition   string         `json:"alert_condition"`
	AlertType        string         `json:"alert_type"`
	Priority         string         `json:"priority"`
	TargetRate       sql.NullString `json:"target_rate"`
	PercentageChange sql.NullString `json:"percentage_change"`
	RangeMin         sql.NullString `json:"range_min"`
	RangeMax         sql.NullString `json:"range_max"`
	BaselineRate     sql.NullString `json:"baseline_rate"`
	TrailingDistance sql.NullString `json:"trailing_distance"`
	MaxTrailingRate  sql.NullString `json:"max_trailing_rate"`
	MinTrailingRate  sql.NullString `json:"min_trailing_rate"`
	Description      sql.NullString `json:"description"`
	Label            sql.NullString `json:"label"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	NotifyPush       bool           `json:"notify_push"`
	NotifyInApp      bool           `json:"notify_in_app"`
}

func (q *Queries) CreatePriceAlert(ctx context.Context, arg CreatePriceAlertParams) (PriceAlert, error) {
	row := q.db.QueryRowContext(ctx, createPriceAlert,
		arg.UserID,
		arg.SourceCurrency,
		arg.TargetCurrency,
		arg.AlertCondition,
		arg.AlertType,
		arg.Priority,
		arg.TargetRate,
		arg.PercentageChange,
		arg.RangeMin,
		arg.RangeMax,
		arg.BaselineRate,
		arg.TrailingDistance,
		arg.MaxTrailingRate,
		arg.MinTrailingRate,
		arg.Description,
		arg.Label,
		arg.ExpiresAt,
		arg.NotifyPush,
		arg.NotifyInApp,
	)
	var i PriceAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceCurrency,
		&i.TargetCurrency,
		&i.AlertCondition,
		&i.AlertType,
		&i.Priority,
		&i.TargetRate,
		&i.PercentageChange,
		&i.RangeMin,
		&i.RangeMax,
		&i.BaselineRate,
		&i.TrailingDistance,
		&i.MaxTrailingRate,
		&i.MinTrailingRate,
		&i.Description,
		&i.Label,
		&i.IsActive,
		&i.TriggeredCount,
		&i.LastTriggeredAt,
		&i.LastCheckedAt,
		&i.ExpiresAt,
		&i.NotifyPush,
		&i.NotifyInApp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteExpiredAlerts = `-- name: DeleteExpiredAlerts :one
WITH deleted AS (
    DELETE FROM price_alerts
    WHERE expires_at < $1
    AND is_active = false
    AND deleted_at IS NULL
    RETURNING id
)
SELECT COUNT(*) FROM deleted
`

func (q *Queries) DeleteExpiredAlerts(ctx context.Context, expiresAt sql.NullTime) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteExpiredAlerts, expiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePriceAlert = `-- name: DeletePriceAlert :exec
UPDATE price_alerts
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type DeletePriceAlertParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePriceAlert(ctx context.Context, arg DeletePriceAlertParams) error {
	_, err := q.db.ExecContext(ctx, deletePriceAlert, arg.ID, arg.UserID)
	return err
}

const getActiveAlertCount = `-- name: GetActiveAlertCount :one
SELECT COUNT(*) FROM price_alerts
WHERE is_active = true 
AND deleted_at IS NULL
AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) GetActiveAlertCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveAlertCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActivePriceAlerts = `-- name: GetActivePriceAlerts :many
SELECT id, user_id, source_currency, target_currency, alert_condition, alert_type, priority, target_rate, percentage_change, range_min, range_max, baseline_rate, trailing_distance, max_trailing_rate, min_trailing_rate, description, label, is_active, triggered_count, last_triggered_at, last_checked_at, expires_at, notify_push, notify_in_app, created_at, updated_at, deleted_at FROM price_alerts
WHERE is_active = true 
AND deleted_at IS NULL
AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY priority DESC, last_checked_at ASC NULLS FIRST
`

func (q *Queries) GetActivePriceAlerts(ctx context.Context) ([]PriceAlert, error) {
	rows, err := q.db.QueryContext(ctx, getActivePriceAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceAlert{}
	for rows.Next() {
		var i PriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceCurrency,
			&i.TargetCurrency,
			&i.AlertCondition,
			&i.AlertType,
			&i.Priority,
			&i.TargetRate,
			&i.PercentageChange,
			&i.RangeMin,
			&i.RangeMax,
			&i.BaselineRate,
			&i.TrailingDistance,
			&i.MaxTrailingRate,
			&i.MinTrailingRate,
			&i.Description,
			&i.Label,
			&i.IsActive,
			&i.TriggeredCount,
			&i.LastTriggeredAt,
			&i.LastCheckedAt,
			&i.ExpiresAt,
			&i.NotifyPush,
			&i.NotifyInApp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertTriggerHistory = `-- name: GetAlertTriggerHistory :many
SELECT id, alert_id, user_id, triggered_at, current_rate, previous_rate, change_percent, alert_condition, target_rate, push_notification_sent, in_app_notification_sent, notification_error, created_at FROM alert_trigger_history
WHERE alert_id = $1
ORDER BY triggered_at DESC
LIMIT $2 OFFSET $3
`

type GetAlertTriggerHistoryParams struct {
	AlertID uuid.UUID `json:"alert_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetAlertTriggerHistory(ctx context.Context, arg GetAlertTriggerHistoryParams) ([]AlertTriggerHistory, error) {
	rows, err := q.db.QueryContext(ctx, getAlertTriggerHistory, arg.AlertID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertTriggerHistory{}
	for rows.Next() {
		var i AlertTriggerHistory
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.UserID,
			&i.TriggeredAt,
			&i.CurrentRate,
			&i.PreviousRate,
			&i.ChangePercent,
			&i.AlertCondition,
			&i.TargetRate,
			&i.PushNotificationSent,
			&i.InAppNotificationSent,
			&i.NotificationError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPriceAlerts = `-- name: GetAllPriceAlerts :many
SELECT id, user_id, source_currency, target_currency, alert_condition, alert_type, priority, target_rate, percentage_change, range_min, range_max, baseline_rate, trailing_distance, max_trailing_rate, min_trailing_rate, description, label, is_active, triggered_count, last_triggered_at, last_checked_at, expires_at, notify_push, notify_in_app, created_at, updated_at, deleted_at FROM price_alerts
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllPriceAlertsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllPriceAlerts(ctx context.Context, arg GetAllPriceAlertsParams) ([]PriceAlert, error) {
	rows, err := q.db.QueryContext(ctx, getAllPriceAlerts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceAlert{}
	for rows.Next() {
		var i PriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceCurrency,
			&i.TargetCurrency,
			&i.AlertCondition,
			&i.AlertType,
			&i.Priority,
			&i.TargetRate,
			&i.PercentageChange,
			&i.RangeMin,
			&i.RangeMax,
			&i.BaselineRate,
			&i.TrailingDistance,
			&i.MaxTrailingRate,
			&i.MinTrailingRate,
			&i.Description,
			&i.Label,
			&i.IsActive,
			&i.TriggeredCount,
			&i.LastTriggeredAt,
			&i.LastCheckedAt,
			&i.ExpiresAt,
			&i.NotifyPush,
			&i.NotifyInApp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriceAlert = `-- name: GetPriceAlert :one
SELECT id, user_id, source_currency, target_currency, alert_condition, alert_type, priority, target_rate, percentage_change, range_min, range_max, baseline_rate, trailing_distance, max_trailing_rate, min_trailing_rate, description, label, is_active, triggered_count, last_triggered_at, last_checked_at, expires_at, notify_push, notify_in_app, created_at, updated_at, deleted_at FROM price_alerts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPriceAlert(ctx context.Context, id uuid.UUID) (PriceAlert, error) {
	row := q.db.QueryRowContext(ctx, getPriceAlert, id)
	var i PriceAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceCurrency,
		&i.TargetCurrency,
		&i.AlertCondition,
		&i.AlertType,
		&i.Priority,
		&i.TargetRate,
		&i.PercentageChange,
		&i.RangeMin,
		&i.RangeMax,
		&i.BaselineRate,
		&i.TrailingDistance,
		&i.MaxTrailingRate,
		&i.MinTrailingRate,
		&i.Description,
		&i.Label,
		&i.IsActive,
		&i.TriggeredCount,
		&i.LastTriggeredAt,
		&i.LastCheckedAt,
		&i.ExpiresAt,
		&i.NotifyPush,
		&i.NotifyInApp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserActiveAlerts = `-- name: GetUserActiveAlerts :many
SELECT id, user_id, source_currency, target_currency, alert_condition, alert_type, priority, target_rate, percentage_change, range_min, range_max, baseline_rate, trailing_distance, max_trailing_rate, min_trailing_rate, description, label, is_active, triggered_count, last_triggered_at, last_checked_at, expires_at, notify_push, notify_in_app, created_at, updated_at, deleted_at FROM price_alerts
WHERE user_id = $1 AND is_active = true AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetUserActiveAlerts(ctx context.Context, userID uuid.UUID) ([]PriceAlert, error) {
	rows, err := q.db.QueryContext(ctx, getUserActiveAlerts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceAlert{}
	for rows.Next() {
		var i PriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceCurrency,
			&i.TargetCurrency,
			&i.AlertCondition,
			&i.AlertType,
			&i.Priority,
			&i.TargetRate,
			&i.PercentageChange,
			&i.RangeMin,
			&i.RangeMax,
			&i.BaselineRate,
			&i.TrailingDistance,
			&i.MaxTrailingRate,
			&i.MinTrailingRate,
			&i.Description,
			&i.Label,
			&i.IsActive,
			&i.TriggeredCount,
			&i.LastTriggeredAt,
			&i.LastCheckedAt,
			&i.ExpiresAt,
			&i.NotifyPush,
			&i.NotifyInApp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAlertStats = `-- name: GetUserAlertStats :one
SELECT 
    COUNT(*) FILTER (WHERE deleted_at IS NULL) as total_alerts,
    COUNT(*) FILTER (WHERE is_active = true AND deleted_at IS NULL) as active_alerts,
    SUM(triggered_count) FILTER (WHERE deleted_at IS NULL) as triggered_count,
    jsonb_object_agg(
        alert_type,
        COUNT(*) FILTER (WHERE deleted_at IS NULL)
    ) as alerts_by_type,
    jsonb_object_agg(
        priority,
        COUNT(*) FILTER (WHERE deleted_at IS NULL)
    ) as alerts_by_priority
FROM price_alerts
WHERE user_id = $1
GROUP BY user_id
`

type GetUserAlertStatsRow struct {
	TotalAlerts      int64           `json:"total_alerts"`
	ActiveAlerts     int64           `json:"active_alerts"`
	TriggeredCount   int64           `json:"triggered_count"`
	AlertsByType     json.RawMessage `json:"alerts_by_type"`
	AlertsByPriority json.RawMessage `json:"alerts_by_priority"`
}

func (q *Queries) GetUserAlertStats(ctx context.Context, userID uuid.UUID) (GetUserAlertStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAlertStats, userID)
	var i GetUserAlertStatsRow
	err := row.Scan(
		&i.TotalAlerts,
		&i.ActiveAlerts,
		&i.TriggeredCount,
		&i.AlertsByType,
		&i.AlertsByPriority,
	)
	return i, err
}

const getUserAlerts = `-- name: GetUserAlerts :many
SELECT id, user_id, source_currency, target_currency, alert_condition, alert_type, priority, target_rate, percentage_change, range_min, range_max, baseline_rate, trailing_distance, max_trailing_rate, min_trailing_rate, description, label, is_active, triggered_count, last_triggered_at, last_checked_at, expires_at, notify_push, notify_in_app, created_at, updated_at, deleted_at FROM price_alerts
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetUserAlerts(ctx context.Context, userID uuid.UUID) ([]PriceAlert, error) {
	rows, err := q.db.QueryContext(ctx, getUserAlerts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PriceAlert{}
	for rows.Next() {
		var i PriceAlert
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceCurrency,
			&i.TargetCurrency,
			&i.AlertCondition,
			&i.AlertType,
			&i.Priority,
			&i.TargetRate,
			&i.PercentageChange,
			&i.RangeMin,
			&i.RangeMax,
			&i.BaselineRate,
			&i.TrailingDistance,
			&i.MaxTrailingRate,
			&i.MinTrailingRate,
			&i.Description,
			&i.Label,
			&i.IsActive,
			&i.TriggeredCount,
			&i.LastTriggeredAt,
			&i.LastCheckedAt,
			&i.ExpiresAt,
			&i.NotifyPush,
			&i.NotifyInApp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertBaseline = `-- name: UpdateAlertBaseline :exec
UPDATE price_alerts
SET baseline_rate = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateAlertBaselineParams struct {
	ID           uuid.UUID      `json:"id"`
	BaselineRate sql.NullString `json:"baseline_rate"`
}

func (q *Queries) UpdateAlertBaseline(ctx context.Context, arg UpdateAlertBaselineParams) error {
	_, err := q.db.ExecContext(ctx, updateAlertBaseline, arg.ID, arg.BaselineRate)
	return err
}

const updateAlertLastChecked = `-- name: UpdateAlertLastChecked :exec
UPDATE price_alerts
SET last_checked_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateAlertLastChecked(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateAlertLastChecked, id)
	return err
}

const updateAlertStatus = `-- name: UpdateAlertStatus :exec
UPDATE price_alerts
SET is_active = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateAlertStatusParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAlertStatus, arg.ID, arg.IsActive)
	return err
}

const updateAlertTrigger = `-- name: UpdateAlertTrigger :exec
UPDATE price_alerts
SET 
    triggered_count = $2,
    last_triggered_at = $3,
    last_checked_at = $4,
    is_active = COALESCE($5, is_active),
    baseline_rate = COALESCE($6, baseline_rate)
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateAlertTriggerParams struct {
	ID              uuid.UUID      `json:"id"`
	TriggeredCount  int32          `json:"triggered_count"`
	LastTriggeredAt sql.NullTime   `json:"last_triggered_at"`
	LastCheckedAt   sql.NullTime   `json:"last_checked_at"`
	IsActive        sql.NullBool   `json:"is_active"`
	BaselineRate    sql.NullString `json:"baseline_rate"`
}

func (q *Queries) UpdateAlertTrigger(ctx context.Context, arg UpdateAlertTriggerParams) error {
	_, err := q.db.ExecContext(ctx, updateAlertTrigger,
		arg.ID,
		arg.TriggeredCount,
		arg.LastTriggeredAt,
		arg.LastCheckedAt,
		arg.IsActive,
		arg.BaselineRate,
	)
	return err
}

const updatePriceAlert = `-- name: UpdatePriceAlert :one
UPDATE price_alerts
SET 
    target_rate = COALESCE($2, target_rate),
    percentage_change = COALESCE($3, percentage_change),
    range_min = COALESCE($4, range_min),
    range_max = COALESCE($5, range_max),
    description = COALESCE($6, description),
    label = COALESCE($7, label),
    expires_at = COALESCE($8, expires_at),
    notify_push = COALESCE($9, notify_push),
    notify_in_app = COALESCE($10, notify_in_app)
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, source_currency, target_currency, alert_condition, alert_type, priority, target_rate, percentage_change, range_min, range_max, baseline_rate, trailing_distance, max_trailing_rate, min_trailing_rate, description, label, is_active, triggered_count, last_triggered_at, last_checked_at, expires_at, notify_push, notify_in_app, created_at, updated_at, deleted_at
`

type UpdatePriceAlertParams struct {
	ID               uuid.UUID      `json:"id"`
	TargetRate       sql.NullString `json:"target_rate"`
	PercentageChange sql.NullString `json:"percentage_change"`
	RangeMin         sql.NullString `json:"range_min"`
	RangeMax         sql.NullString `json:"range_max"`
	Description      sql.NullString `json:"description"`
	Label            sql.NullString `json:"label"`
	ExpiresAt        sql.NullTime   `json:"expires_at"`
	NotifyPush       sql.NullBool   `json:"notify_push"`
	NotifyInApp      sql.NullBool   `json:"notify_in_app"`
}

func (q *Queries) UpdatePriceAlert(ctx context.Context, arg UpdatePriceAlertParams) (PriceAlert, error) {
	row := q.db.QueryRowContext(ctx, updatePriceAlert,
		arg.ID,
		arg.TargetRate,
		arg.PercentageChange,
		arg.RangeMin,
		arg.RangeMax,
		arg.Description,
		arg.Label,
		arg.ExpiresAt,
		arg.NotifyPush,
		arg.NotifyInApp,
	)
	var i PriceAlert
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceCurrency,
		&i.TargetCurrency,
		&i.AlertCondition,
		&i.AlertType,
		&i.Priority,
		&i.TargetRate,
		&i.PercentageChange,
		&i.RangeMin,
		&i.RangeMax,
		&i.BaselineRate,
		&i.TrailingDistance,
		&i.MaxTrailingRate,
		&i.MinTrailingRate,
		&i.Description,
		&i.Label,
		&i.IsActive,
		&i.TriggeredCount,
		&i.LastTriggeredAt,
		&i.LastCheckedAt,
		&i.ExpiresAt,
		&i.NotifyPush,
		&i.NotifyInApp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTrailingAlert = `-- name: UpdateTrailingAlert :exec
UPDATE price_alerts
SET 
    max_trailing_rate = COALESCE($2, max_trailing_rate),
    min_trailing_rate = COALESCE($3, min_trailing_rate),
    target_rate = COALESCE($4, target_rate)
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateTrailingAlertParams struct {
	ID              uuid.UUID      `json:"id"`
	MaxTrailingRate sql.NullString `json:"max_trailing_rate"`
	MinTrailingRate sql.NullString `json:"min_trailing_rate"`
	TargetRate      sql.NullString `json:"target_rate"`
}

func (q *Queries) UpdateTrailingAlert(ctx context.Context, arg UpdateTrailingAlertParams) error {
	_, err := q.db.ExecContext(ctx, updateTrailingAlert,
		arg.ID,
		arg.MaxTrailingRate,
		arg.MinTrailingRate,
		arg.TargetRate,
	)
	return err
}
