// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: referral_earnings.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createReferral = `-- name: CreateReferral :one
INSERT INTO user_referrals (referrer_id, referee_id, earned_amount, status)
VALUES ($1, $2, $3, $4)
    RETURNING id, referrer_id, referee_id, earned_amount, status, created_at
`

type CreateReferralParams struct {
	ReferrerID   int32  `json:"referrer_id"`
	RefereeID    int32  `json:"referee_id"`
	EarnedAmount string `json:"earned_amount"`
	Status       string `json:"status"`
}

type CreateReferralRow struct {
	ID           int32     `json:"id"`
	ReferrerID   int32     `json:"referrer_id"`
	RefereeID    int32     `json:"referee_id"`
	EarnedAmount string    `json:"earned_amount"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (CreateReferralRow, error) {
	row := q.db.QueryRowContext(ctx, createReferral,
		arg.ReferrerID,
		arg.RefereeID,
		arg.EarnedAmount,
		arg.Status,
	)
	var i CreateReferralRow
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.EarnedAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createReferralConfig = `-- name: CreateReferralConfig :one
INSERT INTO referral_configs (referral_amount, referral_percentage_earned_per_conversion)
VALUES ($1, $2)
    RETURNING id, referral_amount, referral_percentage_earned_per_conversion, singleton, created_at, updated_at
`

type CreateReferralConfigParams struct {
	ReferralAmount                        string `json:"referral_amount"`
	ReferralPercentageEarnedPerConversion string `json:"referral_percentage_earned_per_conversion"`
}

func (q *Queries) CreateReferralConfig(ctx context.Context, arg CreateReferralConfigParams) (ReferralConfig, error) {
	row := q.db.QueryRowContext(ctx, createReferralConfig, arg.ReferralAmount, arg.ReferralPercentageEarnedPerConversion)
	var i ReferralConfig
	err := row.Scan(
		&i.ID,
		&i.ReferralAmount,
		&i.ReferralPercentageEarnedPerConversion,
		&i.Singleton,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReferralEarnings = `-- name: CreateReferralEarnings :one
INSERT INTO referral_earnings (user_id)
VALUES ($1)
    RETURNING id, user_id, total_earned, available_balance, withdrawn_balance, created_at, updated_at
`

func (q *Queries) CreateReferralEarnings(ctx context.Context, userID int32) (ReferralEarning, error) {
	row := q.db.QueryRowContext(ctx, createReferralEarnings, userID)
	var i ReferralEarning
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalEarned,
		&i.AvailableBalance,
		&i.WithdrawnBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReferralTransaction = `-- name: CreateReferralTransaction :one
INSERT INTO referral_transactions (user_id, amount, transaction_id, transaction_type, status, reference)
VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING id, user_id, amount, transaction_id, transaction_type, reference, status, created_at, updated_at
`

type CreateReferralTransactionParams struct {
	UserID          int32         `json:"user_id"`
	Amount          string        `json:"amount"`
	TransactionID   uuid.NullUUID `json:"transaction_id"`
	TransactionType string        `json:"transaction_type"`
	Status          string        `json:"status"`
	Reference       string        `json:"reference"`
}

func (q *Queries) CreateReferralTransaction(ctx context.Context, arg CreateReferralTransactionParams) (ReferralTransaction, error) {
	row := q.db.QueryRowContext(ctx, createReferralTransaction,
		arg.UserID,
		arg.Amount,
		arg.TransactionID,
		arg.TransactionType,
		arg.Status,
		arg.Reference,
	)
	var i ReferralTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionID,
		&i.TransactionType,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReferralConfig = `-- name: DeleteReferralConfig :exec
DELETE FROM referral_configs WHERE id = $1
`

func (q *Queries) DeleteReferralConfig(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReferralConfig, id)
	return err
}

const getAllReferrals = `-- name: GetAllReferrals :many
SELECT id, referrer_id, referee_id, earned_amount, created_at, status FROM user_referrals
`

func (q *Queries) GetAllReferrals(ctx context.Context) ([]UserReferral, error) {
	rows, err := q.db.QueryContext(ctx, getAllReferrals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserReferral{}
	for rows.Next() {
		var i UserReferral
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerID,
			&i.RefereeID,
			&i.EarnedAmount,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReferralByRefereeID = `-- name: GetReferralByRefereeID :one
SELECT id, referrer_id, referee_id, earned_amount, created_at, status FROM user_referrals WHERE referee_id = $1
`

func (q *Queries) GetReferralByRefereeID(ctx context.Context, refereeID int32) (UserReferral, error) {
	row := q.db.QueryRowContext(ctx, getReferralByRefereeID, refereeID)
	var i UserReferral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.EarnedAmount,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getReferralConfig = `-- name: GetReferralConfig :one
SELECT id, referral_amount, referral_percentage_earned_per_conversion, singleton, created_at, updated_at FROM referral_configs
`

func (q *Queries) GetReferralConfig(ctx context.Context) (ReferralConfig, error) {
	row := q.db.QueryRowContext(ctx, getReferralConfig)
	var i ReferralConfig
	err := row.Scan(
		&i.ID,
		&i.ReferralAmount,
		&i.ReferralPercentageEarnedPerConversion,
		&i.Singleton,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferralEarnings = `-- name: GetReferralEarnings :one
SELECT id, user_id, total_earned, available_balance, withdrawn_balance, created_at, updated_at FROM referral_earnings WHERE user_id = $1
`

func (q *Queries) GetReferralEarnings(ctx context.Context, userID int32) (ReferralEarning, error) {
	row := q.db.QueryRowContext(ctx, getReferralEarnings, userID)
	var i ReferralEarning
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalEarned,
		&i.AvailableBalance,
		&i.WithdrawnBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferralTransaction = `-- name: GetReferralTransaction :one
SELECT id, user_id, amount, transaction_id, transaction_type, reference, status, created_at, updated_at FROM referral_transactions WHERE id = $1
`

func (q *Queries) GetReferralTransaction(ctx context.Context, id int64) (ReferralTransaction, error) {
	row := q.db.QueryRowContext(ctx, getReferralTransaction, id)
	var i ReferralTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionID,
		&i.TransactionType,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserReferrals = `-- name: GetUserReferrals :many
SELECT id, referrer_id, referee_id, earned_amount, created_at, status FROM user_referrals WHERE referrer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserReferrals(ctx context.Context, referrerID int32) ([]UserReferral, error) {
	rows, err := q.db.QueryContext(ctx, getUserReferrals, referrerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserReferral{}
	for rows.Next() {
		var i UserReferral
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerID,
			&i.RefereeID,
			&i.EarnedAmount,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvailableBalanceAfterWithdrawal = `-- name: UpdateAvailableBalanceAfterWithdrawal :one
UPDATE referral_earnings
SET
    available_balance = available_balance - $2,
    withdrawn_balance = withdrawn_balance + $2,
    total_earned = available_balance + withdrawn_balance,
    updated_at = NOW()
WHERE user_id = $1
  AND $2 > 0
  AND available_balance >= $2
RETURNING id, user_id, total_earned, available_balance, withdrawn_balance, created_at, updated_at
`

type UpdateAvailableBalanceAfterWithdrawalParams struct {
	UserID           int32  `json:"user_id"`
	AvailableBalance string `json:"available_balance"`
}

func (q *Queries) UpdateAvailableBalanceAfterWithdrawal(ctx context.Context, arg UpdateAvailableBalanceAfterWithdrawalParams) (ReferralEarning, error) {
	row := q.db.QueryRowContext(ctx, updateAvailableBalanceAfterWithdrawal, arg.UserID, arg.AvailableBalance)
	var i ReferralEarning
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalEarned,
		&i.AvailableBalance,
		&i.WithdrawnBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReferralConfig = `-- name: UpdateReferralConfig :one
UPDATE referral_configs
SET
    referral_amount = COALESCE($1, referral_amount),
    referral_percentage_earned_per_conversion =
        COALESCE($2, referral_percentage_earned_per_conversion),
    updated_at = NOW()
WHERE id = $3
RETURNING id, referral_amount, referral_percentage_earned_per_conversion, singleton, created_at, updated_at
`

type UpdateReferralConfigParams struct {
	ReferralAmount                        sql.NullString `json:"referral_amount"`
	ReferralPercentageEarnedPerConversion sql.NullString `json:"referral_percentage_earned_per_conversion"`
	ID                                    int64          `json:"id"`
}

func (q *Queries) UpdateReferralConfig(ctx context.Context, arg UpdateReferralConfigParams) (ReferralConfig, error) {
	row := q.db.QueryRowContext(ctx, updateReferralConfig, arg.ReferralAmount, arg.ReferralPercentageEarnedPerConversion, arg.ID)
	var i ReferralConfig
	err := row.Scan(
		&i.ID,
		&i.ReferralAmount,
		&i.ReferralPercentageEarnedPerConversion,
		&i.Singleton,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReferralEarnings = `-- name: UpdateReferralEarnings :one
UPDATE referral_earnings
SET
    total_earned = total_earned + $2,
    available_balance = available_balance + $2,
    updated_at = NOW()
WHERE user_id = $1
    RETURNING id, user_id, total_earned, available_balance, withdrawn_balance, created_at, updated_at
`

type UpdateReferralEarningsParams struct {
	UserID      int32  `json:"user_id"`
	TotalEarned string `json:"total_earned"`
}

func (q *Queries) UpdateReferralEarnings(ctx context.Context, arg UpdateReferralEarningsParams) (ReferralEarning, error) {
	row := q.db.QueryRowContext(ctx, updateReferralEarnings, arg.UserID, arg.TotalEarned)
	var i ReferralEarning
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalEarned,
		&i.AvailableBalance,
		&i.WithdrawnBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReferralStatus = `-- name: UpdateReferralStatus :exec
UPDATE user_referrals
SET status = $1
WHERE id = $2
`

type UpdateReferralStatusParams struct {
	Status string `json:"status"`
	ID     int32  `json:"id"`
}

func (q *Queries) UpdateReferralStatus(ctx context.Context, arg UpdateReferralStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReferralStatus, arg.Status, arg.ID)
	return err
}

const updateReferralTransactionStatus = `-- name: UpdateReferralTransactionStatus :exec
UPDATE referral_transactions
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateReferralTransactionStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateReferralTransactionStatus(ctx context.Context, arg UpdateReferralTransactionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReferralTransactionStatus, arg.ID, arg.Status)
	return err
}
