// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: referral_earnings.sql

package db

import (
	"context"
	"database/sql"
)

const createReferral = `-- name: CreateReferral :one
INSERT INTO user_referrals (referrer_id, referee_id, earned_amount, status)
VALUES ($1, $2, $3, $4)
    RETURNING id, referrer_id, referee_id, earned_amount, created_at, status
`

type CreateReferralParams struct {
	ReferrerID   int32  `json:"referrer_id"`
	RefereeID    int32  `json:"referee_id"`
	EarnedAmount string `json:"earned_amount"`
	Status       string `json:"status"`
}

func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (UserReferral, error) {
	row := q.db.QueryRowContext(ctx, createReferral,
		arg.ReferrerID,
		arg.RefereeID,
		arg.EarnedAmount,
		arg.Status,
	)
	var i UserReferral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.EarnedAmount,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const createReferralConfig = `-- name: CreateReferralConfig :one
INSERT INTO referral_configs (referral_amount, minimum_withdrawal_threshold)
VALUES ($1, $2)
    RETURNING id, referral_amount, minimum_withdrawal_threshold, singleton, created_at, updated_at
`

type CreateReferralConfigParams struct {
	ReferralAmount             string `json:"referral_amount"`
	MinimumWithdrawalThreshold string `json:"minimum_withdrawal_threshold"`
}

func (q *Queries) CreateReferralConfig(ctx context.Context, arg CreateReferralConfigParams) (ReferralConfig, error) {
	row := q.db.QueryRowContext(ctx, createReferralConfig, arg.ReferralAmount, arg.MinimumWithdrawalThreshold)
	var i ReferralConfig
	err := row.Scan(
		&i.ID,
		&i.ReferralAmount,
		&i.MinimumWithdrawalThreshold,
		&i.Singleton,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReferralEarnings = `-- name: CreateReferralEarnings :one
INSERT INTO referral_earnings (user_id)
VALUES ($1)
    RETURNING id, user_id, total_earned, available_balance, withdrawn_balance, created_at, updated_at
`

func (q *Queries) CreateReferralEarnings(ctx context.Context, userID int32) (ReferralEarning, error) {
	row := q.db.QueryRowContext(ctx, createReferralEarnings, userID)
	var i ReferralEarning
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalEarned,
		&i.AvailableBalance,
		&i.WithdrawnBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWithdrawalRequest = `-- name: CreateWithdrawalRequest :one
INSERT INTO withdrawal_requests (user_id, amount)
VALUES ($1, $2)
    RETURNING id, user_id, amount, status, created_at, updated_at
`

type CreateWithdrawalRequestParams struct {
	UserID int32  `json:"user_id"`
	Amount string `json:"amount"`
}

func (q *Queries) CreateWithdrawalRequest(ctx context.Context, arg CreateWithdrawalRequestParams) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, createWithdrawalRequest, arg.UserID, arg.Amount)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReferralConfig = `-- name: DeleteReferralConfig :exec
DELETE FROM referral_configs WHERE id = $1
`

func (q *Queries) DeleteReferralConfig(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReferralConfig, id)
	return err
}

const getReferralByRefereeID = `-- name: GetReferralByRefereeID :one
SELECT id, referrer_id, referee_id, earned_amount, created_at, status FROM user_referrals WHERE referee_id = $1
`

func (q *Queries) GetReferralByRefereeID(ctx context.Context, refereeID int32) (UserReferral, error) {
	row := q.db.QueryRowContext(ctx, getReferralByRefereeID, refereeID)
	var i UserReferral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.EarnedAmount,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getReferralConfig = `-- name: GetReferralConfig :one
SELECT id, referral_amount, minimum_withdrawal_threshold, singleton, created_at, updated_at FROM referral_configs
`

func (q *Queries) GetReferralConfig(ctx context.Context) (ReferralConfig, error) {
	row := q.db.QueryRowContext(ctx, getReferralConfig)
	var i ReferralConfig
	err := row.Scan(
		&i.ID,
		&i.ReferralAmount,
		&i.MinimumWithdrawalThreshold,
		&i.Singleton,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferralEarnings = `-- name: GetReferralEarnings :one
SELECT id, user_id, total_earned, available_balance, withdrawn_balance, created_at, updated_at FROM referral_earnings WHERE user_id = $1
`

func (q *Queries) GetReferralEarnings(ctx context.Context, userID int32) (ReferralEarning, error) {
	row := q.db.QueryRowContext(ctx, getReferralEarnings, userID)
	var i ReferralEarning
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalEarned,
		&i.AvailableBalance,
		&i.WithdrawnBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserReferrals = `-- name: GetUserReferrals :many
SELECT id, referrer_id, referee_id, earned_amount, created_at, status FROM user_referrals WHERE referrer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserReferrals(ctx context.Context, referrerID int32) ([]UserReferral, error) {
	rows, err := q.db.QueryContext(ctx, getUserReferrals, referrerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserReferral{}
	for rows.Next() {
		var i UserReferral
		if err := rows.Scan(
			&i.ID,
			&i.ReferrerID,
			&i.RefereeID,
			&i.EarnedAmount,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWithdrawalRequest = `-- name: GetWithdrawalRequest :one
SELECT id, user_id, amount, status, created_at, updated_at FROM withdrawal_requests WHERE id = $1
`

func (q *Queries) GetWithdrawalRequest(ctx context.Context, id int64) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, getWithdrawalRequest, id)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserWithdrawalRequests = `-- name: ListUserWithdrawalRequests :many
SELECT id, user_id, amount, status, created_at, updated_at FROM withdrawal_requests WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserWithdrawalRequests(ctx context.Context, userID int32) ([]WithdrawalRequest, error) {
	rows, err := q.db.QueryContext(ctx, listUserWithdrawalRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WithdrawalRequest{}
	for rows.Next() {
		var i WithdrawalRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithdrawalRequests = `-- name: ListWithdrawalRequests :many
SELECT id, user_id, amount, status, created_at, updated_at FROM withdrawal_requests
ORDER BY created_at DESC
`

func (q *Queries) ListWithdrawalRequests(ctx context.Context) ([]WithdrawalRequest, error) {
	rows, err := q.db.QueryContext(ctx, listWithdrawalRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WithdrawalRequest{}
	for rows.Next() {
		var i WithdrawalRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvailableBalanceAfterWithdrawal = `-- name: UpdateAvailableBalanceAfterWithdrawal :one
UPDATE referral_earnings
SET
    available_balance = available_balance - $2,
    withdrawn_balance = withdrawn_balance + $2,
    total_earned = available_balance + withdrawn_balance,
    updated_at = NOW()
WHERE user_id = $1
  AND $2 > 0
  AND available_balance >= $2
RETURNING id, user_id, total_earned, available_balance, withdrawn_balance, created_at, updated_at
`

type UpdateAvailableBalanceAfterWithdrawalParams struct {
	UserID           int32  `json:"user_id"`
	AvailableBalance string `json:"available_balance"`
}

func (q *Queries) UpdateAvailableBalanceAfterWithdrawal(ctx context.Context, arg UpdateAvailableBalanceAfterWithdrawalParams) (ReferralEarning, error) {
	row := q.db.QueryRowContext(ctx, updateAvailableBalanceAfterWithdrawal, arg.UserID, arg.AvailableBalance)
	var i ReferralEarning
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalEarned,
		&i.AvailableBalance,
		&i.WithdrawnBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReferralConfig = `-- name: UpdateReferralConfig :one
UPDATE referral_configs
SET
    referral_amount = COALESCE($1, referral_amount),
    minimum_withdrawal_threshold =
        COALESCE($2, minimum_withdrawal_threshold),
    updated_at = NOW()
WHERE id = $3
RETURNING id, referral_amount, minimum_withdrawal_threshold, singleton, created_at, updated_at
`

type UpdateReferralConfigParams struct {
	ReferralAmount             sql.NullString `json:"referral_amount"`
	MinimumWithdrawalThreshold sql.NullString `json:"minimum_withdrawal_threshold"`
	ID                         int64          `json:"id"`
}

func (q *Queries) UpdateReferralConfig(ctx context.Context, arg UpdateReferralConfigParams) (ReferralConfig, error) {
	row := q.db.QueryRowContext(ctx, updateReferralConfig, arg.ReferralAmount, arg.MinimumWithdrawalThreshold, arg.ID)
	var i ReferralConfig
	err := row.Scan(
		&i.ID,
		&i.ReferralAmount,
		&i.MinimumWithdrawalThreshold,
		&i.Singleton,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReferralEarnings = `-- name: UpdateReferralEarnings :one
UPDATE referral_earnings
SET
    total_earned = total_earned + $2,
    available_balance = available_balance + $2,
    updated_at = NOW()
WHERE user_id = $1
    RETURNING id, user_id, total_earned, available_balance, withdrawn_balance, created_at, updated_at
`

type UpdateReferralEarningsParams struct {
	UserID      int32  `json:"user_id"`
	TotalEarned string `json:"total_earned"`
}

func (q *Queries) UpdateReferralEarnings(ctx context.Context, arg UpdateReferralEarningsParams) (ReferralEarning, error) {
	row := q.db.QueryRowContext(ctx, updateReferralEarnings, arg.UserID, arg.TotalEarned)
	var i ReferralEarning
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalEarned,
		&i.AvailableBalance,
		&i.WithdrawnBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReferralStatus = `-- name: UpdateReferralStatus :exec
UPDATE user_referrals
SET status = $1
WHERE referee_id = $2
`

type UpdateReferralStatusParams struct {
	Status    string `json:"status"`
	RefereeID int32  `json:"referee_id"`
}

func (q *Queries) UpdateReferralStatus(ctx context.Context, arg UpdateReferralStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReferralStatus, arg.Status, arg.RefereeID)
	return err
}

const updateWithdrawalRequest = `-- name: UpdateWithdrawalRequest :one
UPDATE withdrawal_requests
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
    RETURNING id, user_id, amount, status, created_at, updated_at
`

type UpdateWithdrawalRequestParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateWithdrawalRequest(ctx context.Context, arg UpdateWithdrawalRequestParams) (WithdrawalRequest, error) {
	row := q.db.QueryRowContext(ctx, updateWithdrawalRequest, arg.ID, arg.Status)
	var i WithdrawalRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
