// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
	"database/sql"
)

const getSystemSettings = `-- name: GetSystemSettings :one
SELECT id, rewards_enabled, vaults_enabled, smart_conversions_enabled, rapid_ramp_enabled, created_at, updated_at FROM system_settings
`

func (q *Queries) GetSystemSettings(ctx context.Context) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSystemSettings)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.RewardsEnabled,
		&i.VaultsEnabled,
		&i.SmartConversionsEnabled,
		&i.RapidRampEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSystemSettings = `-- name: UpdateSystemSettings :exec
UPDATE system_settings 
SET 
    rewards_enabled = COALESCE($1, rewards_enabled), 
    vaults_enabled = COALESCE($2, vaults_enabled), 
    smart_conversions_enabled = COALESCE($3, smart_conversions_enabled), 
    rapid_ramp_enabled = COALESCE($4, rapid_ramp_enabled) 
WHERE id = 1
`

type UpdateSystemSettingsParams struct {
	RewardsEnabled          sql.NullBool `json:"rewards_enabled"`
	VaultsEnabled           sql.NullBool `json:"vaults_enabled"`
	SmartConversionsEnabled sql.NullBool `json:"smart_conversions_enabled"`
	RapidRampEnabled        sql.NullBool `json:"rapid_ramp_enabled"`
}

func (q *Queries) UpdateSystemSettings(ctx context.Context, arg UpdateSystemSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSystemSettings,
		arg.RewardsEnabled,
		arg.VaultsEnabled,
		arg.SmartConversionsEnabled,
		arg.RapidRampEnabled,
	)
	return err
}
