// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const activateUser = `-- name: ActivateUser :one
UPDATE "users"
SET "is_active" = TRUE,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

func (q *Queries) ActivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, activateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const adminUpdateUser = `-- name: AdminUpdateUser :one
UPDATE users
SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    email = COALESCE($4, email),
    phone_number = COALESCE($5, phone_number),
    role = COALESCE($6, role),
    updated_at = NOW()
WHERE id = $1
RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type AdminUpdateUserParams struct {
	ID          uuid.UUID      `json:"id"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	Email       string         `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Role        string         `json:"role"`
}

func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, adminUpdateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const checkUserTag = `-- name: CheckUserTag :one
SELECT EXISTS (
    SELECT 1
    FROM users WHERE user_tag = $1
) AS exists
`

func (q *Queries) CheckUserTag(ctx context.Context, userTag sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserTag, userTag)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countNewUsersToday = `-- name: CountNewUsersToday :one
SELECT COUNT(*)
FROM users
WHERE created_at::date = CURRENT_DATE
  AND deleted_at IS NULL
`

func (q *Queries) CountNewUsersToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNewUsersToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name,
    last_name,
    email,
    hashed_password,
    role
) VALUES ($1, $2, $3, $4, $5) RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type CreateUserParams struct {
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	Email          string         `json:"email"`
	HashedPassword sql.NullString `json:"hashed_password"`
	Role           string         `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.HashedPassword,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE "users"
SET "is_active" = FALSE,
    "updated_at" = NOW()
WHERE "id" = $1
RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deactivateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}

const deleteUser = `-- name: DeleteUser :one
UPDATE users
SET phone_number = $1,
    email = $2,
    first_name = $3,
    deleted_at = NOW()
WHERE id = $4
RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type DeleteUserParams struct {
	PhoneNumber sql.NullString `json:"phone_number"`
	Email       string         `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUser,
		arg.PhoneNumber,
		arg.Email,
		arg.FirstName,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const disableRapidRamp = `-- name: DisableRapidRamp :exec
UPDATE users
SET
  is_rapid_ramp_on = FALSE,
  updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DisableRapidRamp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, disableRapidRamp, id)
	return err
}

const enableRapidRamp = `-- name: EnableRapidRamp :exec
UPDATE users
SET
  is_rapid_ramp_on = TRUE,
  updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) EnableRapidRamp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, enableRapidRamp, id)
	return err
}

const getBridgeCardCardholderByUserID = `-- name: GetBridgeCardCardholderByUserID :one
SELECT bridgecard_cardholder_id FROM users WHERE id = $1
`

func (q *Queries) GetBridgeCardCardholderByUserID(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getBridgeCardCardholderByUserID, id)
	var bridgecard_cardholder_id sql.NullString
	err := row.Scan(&bridgecard_cardholder_id)
	return bridgecard_cardholder_id, err
}

const getPendingCardholderVerifications = `-- name: GetPendingCardholderVerifications :many
SELECT 
    id,
    email,
    bridgecard_cardholder_id,
    bridgecard_verification_status,
    created_at,
    updated_at
FROM users
WHERE 
    bridgecard_cardholder_id IS NOT NULL
    AND (bridgecard_verification_status IS NULL OR bridgecard_verification_status = 'pending')
ORDER BY created_at DESC
`

type GetPendingCardholderVerificationsRow struct {
	ID                           uuid.UUID      `json:"id"`
	Email                        string         `json:"email"`
	BridgecardCardholderID       sql.NullString `json:"bridgecard_cardholder_id"`
	BridgecardVerificationStatus sql.NullString `json:"bridgecard_verification_status"`
	CreatedAt                    time.Time      `json:"created_at"`
	UpdatedAt                    time.Time      `json:"updated_at"`
}

// Get all users awaiting cardholder verification
// Useful for monitoring and retry logic
func (q *Queries) GetPendingCardholderVerifications(ctx context.Context) ([]GetPendingCardholderVerificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingCardholderVerifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingCardholderVerificationsRow{}
	for rows.Next() {
		var i GetPendingCardholderVerificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.BridgecardCardholderID,
			&i.BridgecardVerificationStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRapidRampStatus = `-- name: GetRapidRampStatus :one
SELECT is_rapid_ramp_on
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetRapidRampStatus(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, getRapidRampStatus, id)
	var is_rapid_ramp_on bool
	err := row.Scan(&is_rapid_ramp_on)
	return is_rapid_ramp_on, err
}

const getUserAvatar = `-- name: GetUserAvatar :one
SELECT avatar_url, avatar_blob FROM users WHERE avatar_url = $1
`

type GetUserAvatarRow struct {
	AvatarUrl  sql.NullString `json:"avatar_url"`
	AvatarBlob []byte         `json:"avatar_blob"`
}

func (q *Queries) GetUserAvatar(ctx context.Context, avatarUrl sql.NullString) (GetUserAvatarRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAvatar, avatarUrl)
	var i GetUserAvatarRow
	err := row.Scan(&i.AvatarUrl, &i.AvatarBlob)
	return i, err
}

const getUserByBridgeCardCardholderID = `-- name: GetUserByBridgeCardCardholderID :one
SELECT id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id FROM users 
WHERE bridgecard_cardholder_id = $1
LIMIT 1
`

// Get user by their BridgeCard cardholder ID
// This is the KEY query that links webhook cardholder_id back to your user
func (q *Queries) GetUserByBridgeCardCardholderID(ctx context.Context, bridgecardCardholderID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByBridgeCardCardholderID, bridgecardCardholderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id FROM users WHERE email = $1 and deleted_at is null
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id FROM users WHERE phone_number = $1 and deleted_at is null
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const getUserByTag = `-- name: GetUserByTag :one
SELECT id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id FROM users WHERE user_tag = $1
`

func (q *Queries) GetUserByTag(ctx context.Context, userTag sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTag, userTag)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const getUserHasCompletedFirstConversion = `-- name: GetUserHasCompletedFirstConversion :one
SELECT has_completed_first_conversion
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserHasCompletedFirstConversion(ctx context.Context, id uuid.UUID) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, getUserHasCompletedFirstConversion, id)
	var has_completed_first_conversion sql.NullBool
	err := row.Scan(&has_completed_first_conversion)
	return has_completed_first_conversion, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id FROM users WHERE role=$1 ORDER BY id
LIMIT $2 OFFSET $3
`

type ListAdminsParams struct {
	Role   string `json:"role"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAdmins, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AvatarUrl,
			&i.AvatarBlob,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.HashedPassword,
			&i.HashedPasscode,
			&i.HashedPin,
			&i.PhoneNumber,
			&i.Role,
			&i.Verified,
			&i.Biometric,
			&i.IsKycVerified,
			&i.BridgecardVerificationStatus,
			&i.BridgecardCardholderID,
			&i.IsRapidRampOn,
			&i.HasCompletedFirstConversion,
			&i.FirstConversionID,
			&i.FirstConversionAt,
			&i.Frozen,
			&i.FrozenReason,
			&i.FrozenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HasWallets,
			&i.UserTag,
			&i.FreshChatID,
			&i.IsActive,
			&i.TwofaSecret,
			&i.TwofaEnabled,
			&i.RewardBalance,
			&i.TotalRewardEarned,
			&i.TotalRewardRedeemed,
			&i.TotalConversionVolume,
			&i.TotalTransactionVolume,
			&i.CurrentVipLevelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AvatarUrl,
			&i.AvatarBlob,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.HashedPassword,
			&i.HashedPasscode,
			&i.HashedPin,
			&i.PhoneNumber,
			&i.Role,
			&i.Verified,
			&i.Biometric,
			&i.IsKycVerified,
			&i.BridgecardVerificationStatus,
			&i.BridgecardCardholderID,
			&i.IsRapidRampOn,
			&i.HasCompletedFirstConversion,
			&i.FirstConversionID,
			&i.FirstConversionAt,
			&i.Frozen,
			&i.FrozenReason,
			&i.FrozenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HasWallets,
			&i.UserTag,
			&i.FreshChatID,
			&i.IsActive,
			&i.TwofaSecret,
			&i.TwofaEnabled,
			&i.RewardBalance,
			&i.TotalRewardEarned,
			&i.TotalRewardRedeemed,
			&i.TotalConversionVolume,
			&i.TotalTransactionVolume,
			&i.CurrentVipLevelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRapidRampUsers = `-- name: ListRapidRampUsers :many
SELECT id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
FROM users
WHERE is_rapid_ramp_on = TRUE
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListRapidRampUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listRapidRampUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AvatarUrl,
			&i.AvatarBlob,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.HashedPassword,
			&i.HashedPasscode,
			&i.HashedPin,
			&i.PhoneNumber,
			&i.Role,
			&i.Verified,
			&i.Biometric,
			&i.IsKycVerified,
			&i.BridgecardVerificationStatus,
			&i.BridgecardCardholderID,
			&i.IsRapidRampOn,
			&i.HasCompletedFirstConversion,
			&i.FirstConversionID,
			&i.FirstConversionAt,
			&i.Frozen,
			&i.FrozenReason,
			&i.FrozenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HasWallets,
			&i.UserTag,
			&i.FreshChatID,
			&i.IsActive,
			&i.TwofaSecret,
			&i.TwofaEnabled,
			&i.RewardBalance,
			&i.TotalRewardEarned,
			&i.TotalRewardRedeemed,
			&i.TotalConversionVolume,
			&i.TotalTransactionVolume,
			&i.CurrentVipLevelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id FROM users WHERE deleted_at IS NULL ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AvatarUrl,
			&i.AvatarBlob,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.HashedPassword,
			&i.HashedPasscode,
			&i.HashedPin,
			&i.PhoneNumber,
			&i.Role,
			&i.Verified,
			&i.Biometric,
			&i.IsKycVerified,
			&i.BridgecardVerificationStatus,
			&i.BridgecardCardholderID,
			&i.IsRapidRampOn,
			&i.HasCompletedFirstConversion,
			&i.FirstConversionID,
			&i.FirstConversionAt,
			&i.Frozen,
			&i.FrozenReason,
			&i.FrozenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HasWallets,
			&i.UserTag,
			&i.FreshChatID,
			&i.IsActive,
			&i.TwofaSecret,
			&i.TwofaEnabled,
			&i.RewardBalance,
			&i.TotalRewardEarned,
			&i.TotalRewardRedeemed,
			&i.TotalConversionVolume,
			&i.TotalTransactionVolume,
			&i.CurrentVipLevelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBridgeCardCardholderID = `-- name: SetBridgeCardCardholderID :exec
UPDATE users SET bridgecard_cardholder_id = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type SetBridgeCardCardholderIDParams struct {
	BridgecardCardholderID sql.NullString `json:"bridgecard_cardholder_id"`
	UpdatedAt              time.Time      `json:"updated_at"`
	ID                     uuid.UUID      `json:"id"`
}

func (q *Queries) SetBridgeCardCardholderID(ctx context.Context, arg SetBridgeCardCardholderIDParams) error {
	_, err := q.db.ExecContext(ctx, setBridgeCardCardholderID, arg.BridgecardCardholderID, arg.UpdatedAt, arg.ID)
	return err
}

const setUserTwoFA = `-- name: SetUserTwoFA :one
UPDATE users SET twofa_secret = $1, twofa_enabled = $2, updated_at = $3
WHERE id = $4 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type SetUserTwoFAParams struct {
	TwofaSecret  sql.NullString `json:"twofa_secret"`
	TwofaEnabled sql.NullBool   `json:"twofa_enabled"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) SetUserTwoFA(ctx context.Context, arg SetUserTwoFAParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserTwoFA,
		arg.TwofaSecret,
		arg.TwofaEnabled,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const toggleRapidRamp = `-- name: ToggleRapidRamp :one
UPDATE users
SET
  is_rapid_ramp_on = NOT is_rapid_ramp_on,
  updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING is_rapid_ramp_on
`

func (q *Queries) ToggleRapidRamp(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, toggleRapidRamp, id)
	var is_rapid_ramp_on bool
	err := row.Scan(&is_rapid_ramp_on)
	return is_rapid_ramp_on, err
}

const updateCardholderVerificationStatus = `-- name: UpdateCardholderVerificationStatus :exec
UPDATE users SET bridgecard_verification_status = $1, updated_at = $2
WHERE id = $3
`

type UpdateCardholderVerificationStatusParams struct {
	BridgecardVerificationStatus sql.NullString `json:"bridgecard_verification_status"`
	UpdatedAt                    time.Time      `json:"updated_at"`
	ID                           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateCardholderVerificationStatus(ctx context.Context, arg UpdateCardholderVerificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCardholderVerificationStatus, arg.BridgecardVerificationStatus, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users SET avatar_url = $1, avatar_blob = $2, updated_at = $3
WHERE id = $4 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserAvatarParams struct {
	AvatarUrl  sql.NullString `json:"avatar_url"`
	AvatarBlob []byte         `json:"avatar_blob"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ID         uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAvatar,
		arg.AvatarUrl,
		arg.AvatarBlob,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserBiometric = `-- name: UpdateUserBiometric :exec

UPDATE users
SET biometric = $1
WHERE id = $2
`

type UpdateUserBiometricParams struct {
	Biometric bool      `json:"biometric"`
	ID        uuid.UUID `json:"id"`
}

// -- name: UpdateUserTransactionVolume :exec
// UPDATE users
// SET total_transaction_volume = total_transaction_volume + $1, updated_at = NOW()
// WHERE id = $2;
func (q *Queries) UpdateUserBiometric(ctx context.Context, arg UpdateUserBiometricParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBiometric, arg.Biometric, arg.ID)
	return err
}

const updateUserFirstConversionAt = `-- name: UpdateUserFirstConversionAt :exec
UPDATE users
SET
  first_conversion_at = $1,
  updated_at = NOW()
WHERE id = $2
  AND deleted_at IS NULL
`

type UpdateUserFirstConversionAtParams struct {
	FirstConversionAt sql.NullTime `json:"first_conversion_at"`
	ID                uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateUserFirstConversionAt(ctx context.Context, arg UpdateUserFirstConversionAtParams) error {
	_, err := q.db.ExecContext(ctx, updateUserFirstConversionAt, arg.FirstConversionAt, arg.ID)
	return err
}

const updateUserFirstConversionID = `-- name: UpdateUserFirstConversionID :exec
UPDATE users
SET
  first_conversion_id = $1,
  updated_at = NOW()
WHERE id = $2
  AND deleted_at IS NULL
`

type UpdateUserFirstConversionIDParams struct {
	FirstConversionID uuid.NullUUID `json:"first_conversion_id"`
	ID                uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateUserFirstConversionID(ctx context.Context, arg UpdateUserFirstConversionIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserFirstConversionID, arg.FirstConversionID, arg.ID)
	return err
}

const updateUserFirstName = `-- name: UpdateUserFirstName :one
UPDATE users SET first_name = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserFirstNameParams struct {
	FirstName sql.NullString `json:"first_name"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserFirstName(ctx context.Context, arg UpdateUserFirstNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserFirstName, arg.FirstName, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserFreshChatID = `-- name: UpdateUserFreshChatID :one
UPDATE users SET fresh_chat_id = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserFreshChatIDParams struct {
	FreshChatID sql.NullString `json:"fresh_chat_id"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserFreshChatID(ctx context.Context, arg UpdateUserFreshChatIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserFreshChatID, arg.FreshChatID, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserHasCompletedFirstConversion = `-- name: UpdateUserHasCompletedFirstConversion :exec
UPDATE users
SET
  has_completed_first_conversion = TRUE,
  updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) UpdateUserHasCompletedFirstConversion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserHasCompletedFirstConversion, id)
	return err
}

const updateUserLastName = `-- name: UpdateUserLastName :one
UPDATE users SET last_name = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserLastNameParams struct {
	LastName  sql.NullString `json:"last_name"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserLastName(ctx context.Context, arg UpdateUserLastNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserLastName, arg.LastName, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserNames = `-- name: UpdateUserNames :one
UPDATE users SET first_name = $1, last_name = $2, updated_at = $3
WHERE id = $4 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserNamesParams struct {
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserNames(ctx context.Context, arg UpdateUserNamesParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserNames,
		arg.FirstName,
		arg.LastName,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserPasscodee = `-- name: UpdateUserPasscodee :one
UPDATE users SET hashed_passcode = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserPasscodeeParams struct {
	HashedPasscode sql.NullString `json:"hashed_passcode"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserPasscodee(ctx context.Context, arg UpdateUserPasscodeeParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPasscodee, arg.HashedPasscode, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET hashed_password = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserPasswordParams struct {
	HashedPassword sql.NullString `json:"hashed_password"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.HashedPassword, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserPhone = `-- name: UpdateUserPhone :one
UPDATE users SET phone_number = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserPhoneParams struct {
	PhoneNumber sql.NullString `json:"phone_number"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPhone, arg.PhoneNumber, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserPin = `-- name: UpdateUserPin :one
UPDATE users SET hashed_pin = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserPinParams struct {
	HashedPin sql.NullString `json:"hashed_pin"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserPin(ctx context.Context, arg UpdateUserPinParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPin, arg.HashedPin, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserTag = `-- name: UpdateUserTag :one
UPDATE users SET user_tag = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserTagParams struct {
	UserTag   sql.NullString `json:"user_tag"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUserTag(ctx context.Context, arg UpdateUserTagParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserTag, arg.UserTag, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserVerification = `-- name: UpdateUserVerification :one
UPDATE users SET verified = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserVerificationParams struct {
	Verified  bool      `json:"verified"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserVerification, arg.Verified, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}

const updateUserWalletStatus = `-- name: UpdateUserWalletStatus :one

UPDATE users SET has_wallets = $1, updated_at = $2
WHERE id = $3 RETURNING id, avatar_url, avatar_blob, first_name, last_name, email, hashed_password, hashed_passcode, hashed_pin, phone_number, role, verified, biometric, is_kyc_verified, bridgecard_verification_status, bridgecard_cardholder_id, is_rapid_ramp_on, has_completed_first_conversion, first_conversion_id, first_conversion_at, frozen, frozen_reason, frozen_at, created_at, updated_at, deleted_at, has_wallets, user_tag, fresh_chat_id, is_active, twofa_secret, twofa_enabled, reward_balance, total_reward_earned, total_reward_redeemed, total_conversion_volume, total_transaction_volume, current_vip_level_id
`

type UpdateUserWalletStatusParams struct {
	HasWallets bool      `json:"has_wallets"`
	UpdatedAt  time.Time `json:"updated_at"`
	ID         uuid.UUID `json:"id"`
}

// -- name: UpdateUserKYCVerificationStatus :one
// UPDATE users SET is_kyc_verified = $1, updated_at = $2
// WHERE id = $3 RETURNING *;
func (q *Queries) UpdateUserWalletStatus(ctx context.Context, arg UpdateUserWalletStatusParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserWalletStatus, arg.HasWallets, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AvatarUrl,
		&i.AvatarBlob,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.HashedPasscode,
		&i.HashedPin,
		&i.PhoneNumber,
		&i.Role,
		&i.Verified,
		&i.Biometric,
		&i.IsKycVerified,
		&i.BridgecardVerificationStatus,
		&i.BridgecardCardholderID,
		&i.IsRapidRampOn,
		&i.HasCompletedFirstConversion,
		&i.FirstConversionID,
		&i.FirstConversionAt,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HasWallets,
		&i.UserTag,
		&i.FreshChatID,
		&i.IsActive,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.RewardBalance,
		&i.TotalRewardEarned,
		&i.TotalRewardRedeemed,
		&i.TotalConversionVolume,
		&i.TotalTransactionVolume,
		&i.CurrentVipLevelID,
	)
	return i, err
}
