// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vault_savings.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const approveTransactionByAdmin = `-- name: ApproveTransactionByAdmin :exec
UPDATE vault_transactions
SET admin_approved_by = $2,
    admin_approved_at = NOW(),
    approval_notes = $3,
    status = 'completed',
    completed_at = NOW()
WHERE id = $1 AND requires_admin_approval = TRUE
`

type ApproveTransactionByAdminParams struct {
	ID              uuid.UUID      `json:"id"`
	AdminApprovedBy sql.NullInt64  `json:"admin_approved_by"`
	ApprovalNotes   sql.NullString `json:"approval_notes"`
}

func (q *Queries) ApproveTransactionByAdmin(ctx context.Context, arg ApproveTransactionByAdminParams) error {
	_, err := q.db.ExecContext(ctx, approveTransactionByAdmin, arg.ID, arg.AdminApprovedBy, arg.ApprovalNotes)
	return err
}

const batchUpdateVaultBalances = `-- name: BatchUpdateVaultBalances :exec

UPDATE vault_savings
SET current_balance = v.new_balance,
    updated_at = NOW()
FROM (SELECT unnest($1::uuid[]) as vault_id, unnest($2::decimal[]) as new_balance) as v
WHERE vault_savings.id = v.vault_id
`

type BatchUpdateVaultBalancesParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []string    `json:"column_2"`
}

// ============================================================================
// BATCH OPERATIONS
// ============================================================================
func (q *Queries) BatchUpdateVaultBalances(ctx context.Context, arg BatchUpdateVaultBalancesParams) error {
	_, err := q.db.ExecContext(ctx, batchUpdateVaultBalances, pq.Array(arg.Column1), pq.Array(arg.Column2))
	return err
}

const checkVaultBalance = `-- name: CheckVaultBalance :one
SELECT current_balance, currency
FROM vault_savings
WHERE id = $1
FOR UPDATE
`

type CheckVaultBalanceRow struct {
	CurrentBalance sql.NullString `json:"current_balance"`
	Currency       string         `json:"currency"`
}

func (q *Queries) CheckVaultBalance(ctx context.Context, id uuid.UUID) (CheckVaultBalanceRow, error) {
	row := q.db.QueryRowContext(ctx, checkVaultBalance, id)
	var i CheckVaultBalanceRow
	err := row.Scan(&i.CurrentBalance, &i.Currency)
	return i, err
}

const createVaultGoal = `-- name: CreateVaultGoal :one

INSERT INTO vault_savings (
    user_id,
    vault_name,
    description,
    goal_amount,
    current_balance,
    currency,
    auto_save_enabled,
    auto_save_frequency,
    auto_save_amount,
    next_auto_save,
    recurring_rule,
    status,
    vault_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at
`

type CreateVaultGoalParams struct {
	UserID            int64                 `json:"user_id"`
	VaultName         string                `json:"vault_name"`
	Description       sql.NullString        `json:"description"`
	GoalAmount        sql.NullString        `json:"goal_amount"`
	CurrentBalance    sql.NullString        `json:"current_balance"`
	Currency          string                `json:"currency"`
	AutoSaveEnabled   bool                  `json:"auto_save_enabled"`
	AutoSaveFrequency sql.NullString        `json:"auto_save_frequency"`
	AutoSaveAmount    sql.NullString        `json:"auto_save_amount"`
	NextAutoSave      sql.NullTime          `json:"next_auto_save"`
	RecurringRule     pqtype.NullRawMessage `json:"recurring_rule"`
	Status            string                `json:"status"`
	VaultType         string                `json:"vault_type"`
}

// ============================================================================
// VAULT SAVINGS QUERIES
// ============================================================================
func (q *Queries) CreateVaultGoal(ctx context.Context, arg CreateVaultGoalParams) (VaultSaving, error) {
	row := q.db.QueryRowContext(ctx, createVaultGoal,
		arg.UserID,
		arg.VaultName,
		arg.Description,
		arg.GoalAmount,
		arg.CurrentBalance,
		arg.Currency,
		arg.AutoSaveEnabled,
		arg.AutoSaveFrequency,
		arg.AutoSaveAmount,
		arg.NextAutoSave,
		arg.RecurringRule,
		arg.Status,
		arg.VaultType,
	)
	var i VaultSaving
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VaultName,
		&i.Description,
		&i.GoalAmount,
		&i.CurrentBalance,
		&i.Currency,
		&i.AutoSaveEnabled,
		&i.AutoSaveFrequency,
		&i.AutoSaveAmount,
		&i.NextAutoSave,
		&i.RecurringRule,
		&i.TotalYieldEarned,
		&i.NextYieldCalculation,
		&i.LastYieldCalculation,
		&i.Status,
		&i.VaultType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createVaultTransaction = `-- name: CreateVaultTransaction :one

INSERT INTO vault_transactions (
    user_id,
    vault_id,
    transaction_type,
    amount,
    currency,
    source_wallet,
    destination_wallet,
    balance_before,
    balance_after,
    reference,
    description,
    metadata,
    status,
    requires_2fa,
    requires_admin_approval
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, user_id, vault_id, transaction_type, amount, currency, source_wallet, destination_wallet, balance_before, balance_after, reference, description, metadata, status, requires_2fa, two_fa_verified_at, requires_admin_approval, admin_approved_by, admin_approved_at, approval_notes, completed_at, created_at
`

type CreateVaultTransactionParams struct {
	UserID                int64                 `json:"user_id"`
	VaultID               uuid.UUID             `json:"vault_id"`
	TransactionType       string                `json:"transaction_type"`
	Amount                string                `json:"amount"`
	Currency              string                `json:"currency"`
	SourceWallet          uuid.NullUUID         `json:"source_wallet"`
	DestinationWallet     uuid.NullUUID         `json:"destination_wallet"`
	BalanceBefore         string                `json:"balance_before"`
	BalanceAfter          string                `json:"balance_after"`
	Reference             sql.NullString        `json:"reference"`
	Description           sql.NullString        `json:"description"`
	Metadata              pqtype.NullRawMessage `json:"metadata"`
	Status                sql.NullString        `json:"status"`
	Requires2fa           sql.NullBool          `json:"requires_2fa"`
	RequiresAdminApproval sql.NullBool          `json:"requires_admin_approval"`
}

// ============================================================================
// VAULT TRANSACTIONS QUERIES
// ============================================================================
func (q *Queries) CreateVaultTransaction(ctx context.Context, arg CreateVaultTransactionParams) (VaultTransaction, error) {
	row := q.db.QueryRowContext(ctx, createVaultTransaction,
		arg.UserID,
		arg.VaultID,
		arg.TransactionType,
		arg.Amount,
		arg.Currency,
		arg.SourceWallet,
		arg.DestinationWallet,
		arg.BalanceBefore,
		arg.BalanceAfter,
		arg.Reference,
		arg.Description,
		arg.Metadata,
		arg.Status,
		arg.Requires2fa,
		arg.RequiresAdminApproval,
	)
	var i VaultTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VaultID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.SourceWallet,
		&i.DestinationWallet,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.Reference,
		&i.Description,
		&i.Metadata,
		&i.Status,
		&i.Requires2fa,
		&i.TwoFaVerifiedAt,
		&i.RequiresAdminApproval,
		&i.AdminApprovedBy,
		&i.AdminApprovedAt,
		&i.ApprovalNotes,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createVaultYield = `-- name: CreateVaultYield :one

INSERT INTO vault_yields (
    user_id,
    vault_id,
    yield_amount,
    yield_rate,
    calculation_period_start,
    calculation_period_end,
    vault_balance_snapshot,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, vault_id, yield_amount, yield_rate, calculation_period_start, calculation_period_end, vault_balance_snapshot, status, credited_at, created_at
`

type CreateVaultYieldParams struct {
	UserID                 int64          `json:"user_id"`
	VaultID                uuid.UUID      `json:"vault_id"`
	YieldAmount            string         `json:"yield_amount"`
	YieldRate              string         `json:"yield_rate"`
	CalculationPeriodStart time.Time      `json:"calculation_period_start"`
	CalculationPeriodEnd   time.Time      `json:"calculation_period_end"`
	VaultBalanceSnapshot   string         `json:"vault_balance_snapshot"`
	Status                 sql.NullString `json:"status"`
}

// ============================================================================
// VAULT YIELDS QUERIES
// ============================================================================
func (q *Queries) CreateVaultYield(ctx context.Context, arg CreateVaultYieldParams) (VaultYield, error) {
	row := q.db.QueryRowContext(ctx, createVaultYield,
		arg.UserID,
		arg.VaultID,
		arg.YieldAmount,
		arg.YieldRate,
		arg.CalculationPeriodStart,
		arg.CalculationPeriodEnd,
		arg.VaultBalanceSnapshot,
		arg.Status,
	)
	var i VaultYield
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VaultID,
		&i.YieldAmount,
		&i.YieldRate,
		&i.CalculationPeriodStart,
		&i.CalculationPeriodEnd,
		&i.VaultBalanceSnapshot,
		&i.Status,
		&i.CreditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createYieldConfig = `-- name: CreateYieldConfig :one

INSERT INTO vault_yield_configs (
    currency,
    apy_rate,
    min_balance_for_yield,
    compound_frequency,
    is_active,
    effective_from,
    effective_until,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, currency, apy_rate, min_balance_for_yield, compound_frequency, is_active, effective_from, effective_until, notes, created_at, updated_at
`

type CreateYieldConfigParams struct {
	Currency           string         `json:"currency"`
	ApyRate            string         `json:"apy_rate"`
	MinBalanceForYield string         `json:"min_balance_for_yield"`
	CompoundFrequency  sql.NullString `json:"compound_frequency"`
	IsActive           bool           `json:"is_active"`
	EffectiveFrom      time.Time      `json:"effective_from"`
	EffectiveUntil     sql.NullTime   `json:"effective_until"`
	Notes              sql.NullString `json:"notes"`
}

// ============================================================================
// VAULT YIELD CONFIGS QUERIES
// ============================================================================
func (q *Queries) CreateYieldConfig(ctx context.Context, arg CreateYieldConfigParams) (VaultYieldConfig, error) {
	row := q.db.QueryRowContext(ctx, createYieldConfig,
		arg.Currency,
		arg.ApyRate,
		arg.MinBalanceForYield,
		arg.CompoundFrequency,
		arg.IsActive,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.Notes,
	)
	var i VaultYieldConfig
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.ApyRate,
		&i.MinBalanceForYield,
		&i.CompoundFrequency,
		&i.IsActive,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateYieldConfig = `-- name: DeactivateYieldConfig :exec
UPDATE vault_yield_configs
SET is_active = FALSE,
    effective_until = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateYieldConfig(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateYieldConfig, id)
	return err
}

const decrementVaultBalance = `-- name: DecrementVaultBalance :exec
UPDATE vault_savings
SET current_balance = current_balance - $2,
    updated_at = NOW()
WHERE id = $1 AND current_balance >= $2
`

type DecrementVaultBalanceParams struct {
	ID             uuid.UUID      `json:"id"`
	CurrentBalance sql.NullString `json:"current_balance"`
}

func (q *Queries) DecrementVaultBalance(ctx context.Context, arg DecrementVaultBalanceParams) error {
	_, err := q.db.ExecContext(ctx, decrementVaultBalance, arg.ID, arg.CurrentBalance)
	return err
}

const deleteVaultGoal = `-- name: DeleteVaultGoal :exec
UPDATE vault_savings
SET status = 'cancelled',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteVaultGoal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVaultGoal, id)
	return err
}

const disableAutoSave = `-- name: DisableAutoSave :exec
UPDATE vault_savings
SET auto_save_enabled = FALSE,
    next_auto_save = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DisableAutoSave(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, disableAutoSave, id)
	return err
}

const enableAutoSave = `-- name: EnableAutoSave :exec
UPDATE vault_savings
SET auto_save_enabled = TRUE,
    auto_save_frequency = $2,
    auto_save_amount = $3,
    next_auto_save = $4,
    updated_at = NOW()
WHERE id = $1
`

type EnableAutoSaveParams struct {
	ID                uuid.UUID      `json:"id"`
	AutoSaveFrequency sql.NullString `json:"auto_save_frequency"`
	AutoSaveAmount    sql.NullString `json:"auto_save_amount"`
	NextAutoSave      sql.NullTime   `json:"next_auto_save"`
}

func (q *Queries) EnableAutoSave(ctx context.Context, arg EnableAutoSaveParams) error {
	_, err := q.db.ExecContext(ctx, enableAutoSave,
		arg.ID,
		arg.AutoSaveFrequency,
		arg.AutoSaveAmount,
		arg.NextAutoSave,
	)
	return err
}

const filterVaultsByStatus = `-- name: FilterVaultsByStatus :many
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE user_id = $1 
  AND status = ANY($2::text[])
ORDER BY created_at DESC
`

type FilterVaultsByStatusParams struct {
	UserID  int64    `json:"user_id"`
	Column2 []string `json:"column_2"`
}

func (q *Queries) FilterVaultsByStatus(ctx context.Context, arg FilterVaultsByStatusParams) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, filterVaultsByStatus, arg.UserID, pq.Array(arg.Column2))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveVaultGoalsByUserID = `-- name: GetActiveVaultGoalsByUserID :many
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE user_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) GetActiveVaultGoalsByUserID(ctx context.Context, userID int64) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, getActiveVaultGoalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveYieldConfigByCurrency = `-- name: GetActiveYieldConfigByCurrency :one
SELECT id, currency, apy_rate, min_balance_for_yield, compound_frequency, is_active, effective_from, effective_until, notes, created_at, updated_at FROM vault_yield_configs
WHERE currency = $1
  AND is_active = TRUE
  AND effective_from <= NOW()
  AND (effective_until IS NULL OR effective_until > NOW())
ORDER BY effective_from DESC
LIMIT 1
`

func (q *Queries) GetActiveYieldConfigByCurrency(ctx context.Context, currency string) (VaultYieldConfig, error) {
	row := q.db.QueryRowContext(ctx, getActiveYieldConfigByCurrency, currency)
	var i VaultYieldConfig
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.ApyRate,
		&i.MinBalanceForYield,
		&i.CompoundFrequency,
		&i.IsActive,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllActiveYieldConfigs = `-- name: GetAllActiveYieldConfigs :many
SELECT id, currency, apy_rate, min_balance_for_yield, compound_frequency, is_active, effective_from, effective_until, notes, created_at, updated_at FROM vault_yield_configs
WHERE is_active = TRUE
  AND effective_from <= NOW()
  AND (effective_until IS NULL OR effective_until > NOW())
ORDER BY currency, effective_from DESC
`

func (q *Queries) GetAllActiveYieldConfigs(ctx context.Context) ([]VaultYieldConfig, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveYieldConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultYieldConfig{}
	for rows.Next() {
		var i VaultYieldConfig
		if err := rows.Scan(
			&i.ID,
			&i.Currency,
			&i.ApyRate,
			&i.MinBalanceForYield,
			&i.CompoundFrequency,
			&i.IsActive,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingVaultTransactions = `-- name: GetPendingVaultTransactions :many
SELECT id, user_id, vault_id, transaction_type, amount, currency, source_wallet, destination_wallet, balance_before, balance_after, reference, description, metadata, status, requires_2fa, two_fa_verified_at, requires_admin_approval, admin_approved_by, admin_approved_at, approval_notes, completed_at, created_at FROM vault_transactions
WHERE status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) GetPendingVaultTransactions(ctx context.Context) ([]VaultTransaction, error) {
	rows, err := q.db.QueryContext(ctx, getPendingVaultTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultTransaction{}
	for rows.Next() {
		var i VaultTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.SourceWallet,
			&i.DestinationWallet,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Reference,
			&i.Description,
			&i.Metadata,
			&i.Status,
			&i.Requires2fa,
			&i.TwoFaVerifiedAt,
			&i.RequiresAdminApproval,
			&i.AdminApprovedBy,
			&i.AdminApprovedAt,
			&i.ApprovalNotes,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingYields = `-- name: GetPendingYields :many
SELECT id, user_id, vault_id, yield_amount, yield_rate, calculation_period_start, calculation_period_end, vault_balance_snapshot, status, credited_at, created_at FROM vault_yields
WHERE status = 'calculated'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingYields(ctx context.Context, limit int32) ([]VaultYield, error) {
	rows, err := q.db.QueryContext(ctx, getPendingYields, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultYield{}
	for rows.Next() {
		var i VaultYield
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.YieldAmount,
			&i.YieldRate,
			&i.CalculationPeriodStart,
			&i.CalculationPeriodEnd,
			&i.VaultBalanceSnapshot,
			&i.Status,
			&i.CreditedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentVaultActivity = `-- name: GetRecentVaultActivity :many
SELECT 
    vt.id,
    vt.transaction_type,
    vt.amount,
    vt.currency,
    vt.status,
    vt.created_at,
    vs.vault_name
FROM vault_transactions vt
JOIN vault_savings vs ON vt.vault_id = vs.id
WHERE vt.user_id = $1
ORDER BY vt.created_at DESC
LIMIT $2
`

type GetRecentVaultActivityParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type GetRecentVaultActivityRow struct {
	ID              uuid.UUID      `json:"id"`
	TransactionType string         `json:"transaction_type"`
	Amount          string         `json:"amount"`
	Currency        string         `json:"currency"`
	Status          sql.NullString `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	VaultName       string         `json:"vault_name"`
}

func (q *Queries) GetRecentVaultActivity(ctx context.Context, arg GetRecentVaultActivityParams) ([]GetRecentVaultActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentVaultActivity, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentVaultActivityRow{}
	for rows.Next() {
		var i GetRecentVaultActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.VaultName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecurringDepositMetrics = `-- name: GetRecurringDepositMetrics :one
SELECT 
    COUNT(*) FILTER (WHERE auto_save_enabled = TRUE OR recurring_rule IS NOT NULL) as vaults_with_auto_save,
    COUNT(*) FILTER (WHERE (recurring_rule->>'interval')::text = 'daily') as daily_auto_saves,
    COUNT(*) FILTER (WHERE (recurring_rule->>'interval')::text = 'weekly') as weekly_auto_saves,
    COUNT(*) FILTER (WHERE (recurring_rule->>'interval')::text = 'monthly') as monthly_auto_saves,
    COALESCE(SUM((recurring_rule->>'amount')::decimal), 0) as total_scheduled_amount
FROM vault_savings
WHERE status = 'active'
  AND (auto_save_enabled = TRUE OR (recurring_rule->>'enabled')::boolean = TRUE)
`

type GetRecurringDepositMetricsRow struct {
	VaultsWithAutoSave   int64       `json:"vaults_with_auto_save"`
	DailyAutoSaves       int64       `json:"daily_auto_saves"`
	WeeklyAutoSaves      int64       `json:"weekly_auto_saves"`
	MonthlyAutoSaves     int64       `json:"monthly_auto_saves"`
	TotalScheduledAmount interface{} `json:"total_scheduled_amount"`
}

func (q *Queries) GetRecurringDepositMetrics(ctx context.Context) (GetRecurringDepositMetricsRow, error) {
	row := q.db.QueryRowContext(ctx, getRecurringDepositMetrics)
	var i GetRecurringDepositMetricsRow
	err := row.Scan(
		&i.VaultsWithAutoSave,
		&i.DailyAutoSaves,
		&i.WeeklyAutoSaves,
		&i.MonthlyAutoSaves,
		&i.TotalScheduledAmount,
	)
	return i, err
}

const getTopSavers = `-- name: GetTopSavers :many
SELECT 
    vs.user_id,
    COUNT(vs.id) as total_vaults,
    COALESCE(SUM(vs.current_balance), 0) as total_saved,
    COALESCE(SUM(vs.total_yield_earned), 0) as total_yield_earned,
    COUNT(*) FILTER (WHERE vs.status = 'completed') as completed_goals
FROM vault_savings vs
WHERE vs.status IN ('active', 'completed')
GROUP BY vs.user_id
ORDER BY total_saved DESC
LIMIT $1
`

type GetTopSaversRow struct {
	UserID           int64       `json:"user_id"`
	TotalVaults      int64       `json:"total_vaults"`
	TotalSaved       interface{} `json:"total_saved"`
	TotalYieldEarned interface{} `json:"total_yield_earned"`
	CompletedGoals   int64       `json:"completed_goals"`
}

func (q *Queries) GetTopSavers(ctx context.Context, limit int32) ([]GetTopSaversRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopSavers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopSaversRow{}
	for rows.Next() {
		var i GetTopSaversRow
		if err := rows.Scan(
			&i.UserID,
			&i.TotalVaults,
			&i.TotalSaved,
			&i.TotalYieldEarned,
			&i.CompletedGoals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalYieldEarned = `-- name: GetTotalYieldEarned :one
SELECT COALESCE(SUM(yield_amount), 0) as total_yield
FROM vault_yields
WHERE vault_id = $1 AND status = 'credited'
`

func (q *Queries) GetTotalYieldEarned(ctx context.Context, vaultID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalYieldEarned, vaultID)
	var total_yield interface{}
	err := row.Scan(&total_yield)
	return total_yield, err
}

const getTransactionsRequiring2FA = `-- name: GetTransactionsRequiring2FA :many
SELECT id, user_id, vault_id, transaction_type, amount, currency, source_wallet, destination_wallet, balance_before, balance_after, reference, description, metadata, status, requires_2fa, two_fa_verified_at, requires_admin_approval, admin_approved_by, admin_approved_at, approval_notes, completed_at, created_at FROM vault_transactions
WHERE requires_2fa = TRUE
  AND two_fa_verified_at IS NULL
  AND status = 'pending'
  AND user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTransactionsRequiring2FA(ctx context.Context, userID int64) ([]VaultTransaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsRequiring2FA, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultTransaction{}
	for rows.Next() {
		var i VaultTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.SourceWallet,
			&i.DestinationWallet,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Reference,
			&i.Description,
			&i.Metadata,
			&i.Status,
			&i.Requires2fa,
			&i.TwoFaVerifiedAt,
			&i.RequiresAdminApproval,
			&i.AdminApprovedBy,
			&i.AdminApprovedAt,
			&i.ApprovalNotes,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsRequiringAdminApproval = `-- name: GetTransactionsRequiringAdminApproval :many
SELECT vt.id, vt.user_id, vt.vault_id, vt.transaction_type, vt.amount, vt.currency, vt.source_wallet, vt.destination_wallet, vt.balance_before, vt.balance_after, vt.reference, vt.description, vt.metadata, vt.status, vt.requires_2fa, vt.two_fa_verified_at, vt.requires_admin_approval, vt.admin_approved_by, vt.admin_approved_at, vt.approval_notes, vt.completed_at, vt.created_at, vs.vault_name, vs.currency
FROM vault_transactions vt
JOIN vault_savings vs ON vt.vault_id = vs.id
WHERE vt.requires_admin_approval = TRUE
  AND vt.admin_approved_at IS NULL
  AND vt.status = 'pending'
ORDER BY vt.created_at ASC
`

type GetTransactionsRequiringAdminApprovalRow struct {
	ID                    uuid.UUID             `json:"id"`
	UserID                int64                 `json:"user_id"`
	VaultID               uuid.UUID             `json:"vault_id"`
	TransactionType       string                `json:"transaction_type"`
	Amount                string                `json:"amount"`
	Currency              string                `json:"currency"`
	SourceWallet          uuid.NullUUID         `json:"source_wallet"`
	DestinationWallet     uuid.NullUUID         `json:"destination_wallet"`
	BalanceBefore         string                `json:"balance_before"`
	BalanceAfter          string                `json:"balance_after"`
	Reference             sql.NullString        `json:"reference"`
	Description           sql.NullString        `json:"description"`
	Metadata              pqtype.NullRawMessage `json:"metadata"`
	Status                sql.NullString        `json:"status"`
	Requires2fa           sql.NullBool          `json:"requires_2fa"`
	TwoFaVerifiedAt       sql.NullTime          `json:"two_fa_verified_at"`
	RequiresAdminApproval sql.NullBool          `json:"requires_admin_approval"`
	AdminApprovedBy       sql.NullInt64         `json:"admin_approved_by"`
	AdminApprovedAt       sql.NullTime          `json:"admin_approved_at"`
	ApprovalNotes         sql.NullString        `json:"approval_notes"`
	CompletedAt           sql.NullTime          `json:"completed_at"`
	CreatedAt             time.Time             `json:"created_at"`
	VaultName             string                `json:"vault_name"`
	Currency_2            string                `json:"currency_2"`
}

func (q *Queries) GetTransactionsRequiringAdminApproval(ctx context.Context) ([]GetTransactionsRequiringAdminApprovalRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsRequiringAdminApproval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsRequiringAdminApprovalRow{}
	for rows.Next() {
		var i GetTransactionsRequiringAdminApprovalRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.SourceWallet,
			&i.DestinationWallet,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Reference,
			&i.Description,
			&i.Metadata,
			&i.Status,
			&i.Requires2fa,
			&i.TwoFaVerifiedAt,
			&i.RequiresAdminApproval,
			&i.AdminApprovedBy,
			&i.AdminApprovedAt,
			&i.ApprovalNotes,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.VaultName,
			&i.Currency_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRetentionMetrics = `-- name: GetUserRetentionMetrics :many
SELECT 
    DATE_TRUNC('day', vs.created_at) as cohort_date,
    COUNT(DISTINCT vs.user_id) as users_created,
    COUNT(DISTINCT CASE 
        WHEN vt.created_at >= vs.created_at + INTERVAL '30 days' 
        THEN vs.user_id 
    END) as users_active_after_30_days,
    CASE 
        WHEN COUNT(DISTINCT vs.user_id) > 0 
        THEN (COUNT(DISTINCT CASE 
            WHEN vt.created_at >= vs.created_at + INTERVAL '30 days' 
            THEN vs.user_id 
        END)::float / COUNT(DISTINCT vs.user_id)::float * 100)
        ELSE 0
    END as retention_rate_30_days
FROM vault_savings vs
LEFT JOIN vault_transactions vt ON vs.user_id = vt.user_id
WHERE vs.created_at >= $1 AND vs.created_at <= $2
GROUP BY DATE_TRUNC('day', vs.created_at)
ORDER BY cohort_date DESC
`

type GetUserRetentionMetricsParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetUserRetentionMetricsRow struct {
	CohortDate             int64 `json:"cohort_date"`
	UsersCreated           int64 `json:"users_created"`
	UsersActiveAfter30Days int64 `json:"users_active_after_30_days"`
	RetentionRate30Days    int32 `json:"retention_rate_30_days"`
}

func (q *Queries) GetUserRetentionMetrics(ctx context.Context, arg GetUserRetentionMetricsParams) ([]GetUserRetentionMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserRetentionMetrics, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRetentionMetricsRow{}
	for rows.Next() {
		var i GetUserRetentionMetricsRow
		if err := rows.Scan(
			&i.CohortDate,
			&i.UsersCreated,
			&i.UsersActiveAfter30Days,
			&i.RetentionRate30Days,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVaultsSummary = `-- name: GetUserVaultsSummary :one
SELECT 
    COUNT(*) as total_vaults,
    COUNT(*) FILTER (WHERE status = 'active') as active_vaults,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_vaults,
    COALESCE(SUM(current_balance) FILTER (WHERE currency = 'USDT'), 0) as total_usdt,
    COALESCE(SUM(current_balance) FILTER (WHERE currency = 'USDC'), 0) as total_usdc,
    COALESCE(SUM(current_balance) FILTER (WHERE currency = 'NGN'), 0) as total_ngn,
    COALESCE(SUM(current_balance) FILTER (WHERE currency = 'USD'), 0) as total_usd,
    COALESCE(SUM(total_yield_earned), 0) as total_yield_earned
FROM vault_savings
WHERE user_id = $1 AND status != 'cancelled'
`

type GetUserVaultsSummaryRow struct {
	TotalVaults      int64       `json:"total_vaults"`
	ActiveVaults     int64       `json:"active_vaults"`
	CompletedVaults  int64       `json:"completed_vaults"`
	TotalUsdt        interface{} `json:"total_usdt"`
	TotalUsdc        interface{} `json:"total_usdc"`
	TotalNgn         interface{} `json:"total_ngn"`
	TotalUsd         interface{} `json:"total_usd"`
	TotalYieldEarned interface{} `json:"total_yield_earned"`
}

func (q *Queries) GetUserVaultsSummary(ctx context.Context, userID int64) (GetUserVaultsSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getUserVaultsSummary, userID)
	var i GetUserVaultsSummaryRow
	err := row.Scan(
		&i.TotalVaults,
		&i.ActiveVaults,
		&i.CompletedVaults,
		&i.TotalUsdt,
		&i.TotalUsdc,
		&i.TotalNgn,
		&i.TotalUsd,
		&i.TotalYieldEarned,
	)
	return i, err
}

const getVaultCompletionStats = `-- name: GetVaultCompletionStats :many
SELECT 
    currency,
    COUNT(*) as total_completed,
    COALESCE(AVG(EXTRACT(EPOCH FROM (completed_at - created_at)) / 86400), 0) as avg_days_to_complete,
    COALESCE(AVG(goal_amount), 0) as avg_goal_amount
FROM vault_savings
WHERE status = 'completed'
  AND completed_at IS NOT NULL
  AND created_at >= $1
GROUP BY currency
ORDER BY total_completed DESC
`

type GetVaultCompletionStatsRow struct {
	Currency          string      `json:"currency"`
	TotalCompleted    int64       `json:"total_completed"`
	AvgDaysToComplete interface{} `json:"avg_days_to_complete"`
	AvgGoalAmount     interface{} `json:"avg_goal_amount"`
}

func (q *Queries) GetVaultCompletionStats(ctx context.Context, createdAt time.Time) ([]GetVaultCompletionStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getVaultCompletionStats, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVaultCompletionStatsRow{}
	for rows.Next() {
		var i GetVaultCompletionStatsRow
		if err := rows.Scan(
			&i.Currency,
			&i.TotalCompleted,
			&i.AvgDaysToComplete,
			&i.AvgGoalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultGoalByID = `-- name: GetVaultGoalByID :one
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE id = $1 AND status != 'cancelled'
`

func (q *Queries) GetVaultGoalByID(ctx context.Context, id uuid.UUID) (VaultSaving, error) {
	row := q.db.QueryRowContext(ctx, getVaultGoalByID, id)
	var i VaultSaving
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VaultName,
		&i.Description,
		&i.GoalAmount,
		&i.CurrentBalance,
		&i.Currency,
		&i.AutoSaveEnabled,
		&i.AutoSaveFrequency,
		&i.AutoSaveAmount,
		&i.NextAutoSave,
		&i.RecurringRule,
		&i.TotalYieldEarned,
		&i.NextYieldCalculation,
		&i.LastYieldCalculation,
		&i.Status,
		&i.VaultType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getVaultGoalProgress = `-- name: GetVaultGoalProgress :one
SELECT 
    id,
    vault_name,
    current_balance,
    goal_amount,
    CASE 
        WHEN goal_amount > 0 THEN (current_balance / goal_amount * 100)
        ELSE 0
    END as progress_percentage,
    CASE 
        WHEN current_balance >= goal_amount THEN true
        ELSE false
    END as goal_reached
FROM vault_savings
WHERE id = $1
`

type GetVaultGoalProgressRow struct {
	ID                 uuid.UUID      `json:"id"`
	VaultName          string         `json:"vault_name"`
	CurrentBalance     sql.NullString `json:"current_balance"`
	GoalAmount         sql.NullString `json:"goal_amount"`
	ProgressPercentage int32          `json:"progress_percentage"`
	GoalReached        bool           `json:"goal_reached"`
}

func (q *Queries) GetVaultGoalProgress(ctx context.Context, id uuid.UUID) (GetVaultGoalProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultGoalProgress, id)
	var i GetVaultGoalProgressRow
	err := row.Scan(
		&i.ID,
		&i.VaultName,
		&i.CurrentBalance,
		&i.GoalAmount,
		&i.ProgressPercentage,
		&i.GoalReached,
	)
	return i, err
}

const getVaultGoalsByUserID = `-- name: GetVaultGoalsByUserID :many
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE user_id = $1 AND status != 'cancelled'
ORDER BY created_at DESC
`

func (q *Queries) GetVaultGoalsByUserID(ctx context.Context, userID int64) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, getVaultGoalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultGoalsByUserIDAndCurrency = `-- name: GetVaultGoalsByUserIDAndCurrency :many
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE user_id = $1 AND currency = $2 AND status != 'cancelled'
ORDER BY created_at DESC
`

type GetVaultGoalsByUserIDAndCurrencyParams struct {
	UserID   int64  `json:"user_id"`
	Currency string `json:"currency"`
}

func (q *Queries) GetVaultGoalsByUserIDAndCurrency(ctx context.Context, arg GetVaultGoalsByUserIDAndCurrencyParams) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, getVaultGoalsByUserIDAndCurrency, arg.UserID, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultHealthCheck = `-- name: GetVaultHealthCheck :many
SELECT 
    vs.id,
    vs.vault_name,
    vs.user_id,
    vs.current_balance,
    vs.goal_amount,
    vs.status,
    CASE 
        WHEN vs.current_balance >= vs.goal_amount THEN 'goal_reached'
        WHEN vs.current_balance = 0 AND vs.created_at < NOW() - INTERVAL '30 days' THEN 'inactive'
        WHEN vs.auto_save_enabled = TRUE AND vs.next_auto_save < NOW() - INTERVAL '7 days' THEN 'auto_save_failed'
        ELSE 'healthy'
    END as health_status
FROM vault_savings vs
WHERE vs.status = 'active'
ORDER BY 
    CASE 
        WHEN vs.current_balance >= vs.goal_amount THEN 1
        WHEN vs.current_balance = 0 AND vs.created_at < NOW() - INTERVAL '30 days' THEN 2
        WHEN vs.auto_save_enabled = TRUE AND vs.next_auto_save < NOW() - INTERVAL '7 days' THEN 3
        ELSE 4
    END
`

type GetVaultHealthCheckRow struct {
	ID             uuid.UUID      `json:"id"`
	VaultName      string         `json:"vault_name"`
	UserID         int64          `json:"user_id"`
	CurrentBalance sql.NullString `json:"current_balance"`
	GoalAmount     sql.NullString `json:"goal_amount"`
	Status         string         `json:"status"`
	HealthStatus   string         `json:"health_status"`
}

func (q *Queries) GetVaultHealthCheck(ctx context.Context) ([]GetVaultHealthCheckRow, error) {
	rows, err := q.db.QueryContext(ctx, getVaultHealthCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVaultHealthCheckRow{}
	for rows.Next() {
		var i GetVaultHealthCheckRow
		if err := rows.Scan(
			&i.ID,
			&i.VaultName,
			&i.UserID,
			&i.CurrentBalance,
			&i.GoalAmount,
			&i.Status,
			&i.HealthStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultTransactionByID = `-- name: GetVaultTransactionByID :one
SELECT id, user_id, vault_id, transaction_type, amount, currency, source_wallet, destination_wallet, balance_before, balance_after, reference, description, metadata, status, requires_2fa, two_fa_verified_at, requires_admin_approval, admin_approved_by, admin_approved_at, approval_notes, completed_at, created_at FROM vault_transactions
WHERE id = $1
`

func (q *Queries) GetVaultTransactionByID(ctx context.Context, id uuid.UUID) (VaultTransaction, error) {
	row := q.db.QueryRowContext(ctx, getVaultTransactionByID, id)
	var i VaultTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VaultID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.SourceWallet,
		&i.DestinationWallet,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.Reference,
		&i.Description,
		&i.Metadata,
		&i.Status,
		&i.Requires2fa,
		&i.TwoFaVerifiedAt,
		&i.RequiresAdminApproval,
		&i.AdminApprovedBy,
		&i.AdminApprovedAt,
		&i.ApprovalNotes,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVaultTransactionByReference = `-- name: GetVaultTransactionByReference :one
SELECT id, user_id, vault_id, transaction_type, amount, currency, source_wallet, destination_wallet, balance_before, balance_after, reference, description, metadata, status, requires_2fa, two_fa_verified_at, requires_admin_approval, admin_approved_by, admin_approved_at, approval_notes, completed_at, created_at FROM vault_transactions
WHERE reference = $1
`

func (q *Queries) GetVaultTransactionByReference(ctx context.Context, reference sql.NullString) (VaultTransaction, error) {
	row := q.db.QueryRowContext(ctx, getVaultTransactionByReference, reference)
	var i VaultTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VaultID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.SourceWallet,
		&i.DestinationWallet,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.Reference,
		&i.Description,
		&i.Metadata,
		&i.Status,
		&i.Requires2fa,
		&i.TwoFaVerifiedAt,
		&i.RequiresAdminApproval,
		&i.AdminApprovedBy,
		&i.AdminApprovedAt,
		&i.ApprovalNotes,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVaultTransactionStats = `-- name: GetVaultTransactionStats :one
SELECT 
    COUNT(*) as total_transactions,
    COUNT(*) FILTER (WHERE transaction_type = 'deposit') as total_deposits,
    COUNT(*) FILTER (WHERE transaction_type = 'withdrawal') as total_withdrawals,
    COUNT(*) FILTER (WHERE transaction_type = 'auto_save') as total_auto_saves,
    COUNT(*) FILTER (WHERE transaction_type = 'yield_credit') as total_yield_credits,
    COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'deposit' AND status = 'completed'), 0) as total_deposited,
    COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'withdrawal' AND status = 'completed'), 0) as total_withdrawn,
    COALESCE(SUM(amount) FILTER (WHERE transaction_type = 'yield_credit' AND status = 'completed'), 0) as total_yield
FROM vault_transactions
WHERE vault_id = $1
`

type GetVaultTransactionStatsRow struct {
	TotalTransactions int64       `json:"total_transactions"`
	TotalDeposits     int64       `json:"total_deposits"`
	TotalWithdrawals  int64       `json:"total_withdrawals"`
	TotalAutoSaves    int64       `json:"total_auto_saves"`
	TotalYieldCredits int64       `json:"total_yield_credits"`
	TotalDeposited    interface{} `json:"total_deposited"`
	TotalWithdrawn    interface{} `json:"total_withdrawn"`
	TotalYield        interface{} `json:"total_yield"`
}

func (q *Queries) GetVaultTransactionStats(ctx context.Context, vaultID uuid.UUID) (GetVaultTransactionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultTransactionStats, vaultID)
	var i GetVaultTransactionStatsRow
	err := row.Scan(
		&i.TotalTransactions,
		&i.TotalDeposits,
		&i.TotalWithdrawals,
		&i.TotalAutoSaves,
		&i.TotalYieldCredits,
		&i.TotalDeposited,
		&i.TotalWithdrawn,
		&i.TotalYield,
	)
	return i, err
}

const getVaultTransactionsByDateRange = `-- name: GetVaultTransactionsByDateRange :many
SELECT id, user_id, vault_id, transaction_type, amount, currency, source_wallet, destination_wallet, balance_before, balance_after, reference, description, metadata, status, requires_2fa, two_fa_verified_at, requires_admin_approval, admin_approved_by, admin_approved_at, approval_notes, completed_at, created_at FROM vault_transactions
WHERE vault_id = $1
  AND created_at BETWEEN $2 AND $3
ORDER BY created_at DESC
`

type GetVaultTransactionsByDateRangeParams struct {
	VaultID     uuid.UUID `json:"vault_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) GetVaultTransactionsByDateRange(ctx context.Context, arg GetVaultTransactionsByDateRangeParams) ([]VaultTransaction, error) {
	rows, err := q.db.QueryContext(ctx, getVaultTransactionsByDateRange, arg.VaultID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultTransaction{}
	for rows.Next() {
		var i VaultTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.SourceWallet,
			&i.DestinationWallet,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Reference,
			&i.Description,
			&i.Metadata,
			&i.Status,
			&i.Requires2fa,
			&i.TwoFaVerifiedAt,
			&i.RequiresAdminApproval,
			&i.AdminApprovedBy,
			&i.AdminApprovedAt,
			&i.ApprovalNotes,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultTransactionsByType = `-- name: GetVaultTransactionsByType :many
SELECT id, user_id, vault_id, transaction_type, amount, currency, source_wallet, destination_wallet, balance_before, balance_after, reference, description, metadata, status, requires_2fa, two_fa_verified_at, requires_admin_approval, admin_approved_by, admin_approved_at, approval_notes, completed_at, created_at FROM vault_transactions
WHERE vault_id = $1 AND transaction_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetVaultTransactionsByTypeParams struct {
	VaultID         uuid.UUID `json:"vault_id"`
	TransactionType string    `json:"transaction_type"`
	Limit           int32     `json:"limit"`
	Offset          int32     `json:"offset"`
}

func (q *Queries) GetVaultTransactionsByType(ctx context.Context, arg GetVaultTransactionsByTypeParams) ([]VaultTransaction, error) {
	rows, err := q.db.QueryContext(ctx, getVaultTransactionsByType,
		arg.VaultID,
		arg.TransactionType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultTransaction{}
	for rows.Next() {
		var i VaultTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.SourceWallet,
			&i.DestinationWallet,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Reference,
			&i.Description,
			&i.Metadata,
			&i.Status,
			&i.Requires2fa,
			&i.TwoFaVerifiedAt,
			&i.RequiresAdminApproval,
			&i.AdminApprovedBy,
			&i.AdminApprovedAt,
			&i.ApprovalNotes,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultTransactionsByUserID = `-- name: GetVaultTransactionsByUserID :many
SELECT id, user_id, vault_id, transaction_type, amount, currency, source_wallet, destination_wallet, balance_before, balance_after, reference, description, metadata, status, requires_2fa, two_fa_verified_at, requires_admin_approval, admin_approved_by, admin_approved_at, approval_notes, completed_at, created_at FROM vault_transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetVaultTransactionsByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetVaultTransactionsByUserID(ctx context.Context, arg GetVaultTransactionsByUserIDParams) ([]VaultTransaction, error) {
	rows, err := q.db.QueryContext(ctx, getVaultTransactionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultTransaction{}
	for rows.Next() {
		var i VaultTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.SourceWallet,
			&i.DestinationWallet,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Reference,
			&i.Description,
			&i.Metadata,
			&i.Status,
			&i.Requires2fa,
			&i.TwoFaVerifiedAt,
			&i.RequiresAdminApproval,
			&i.AdminApprovedBy,
			&i.AdminApprovedAt,
			&i.ApprovalNotes,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultTransactionsByVaultID = `-- name: GetVaultTransactionsByVaultID :many
SELECT id, user_id, vault_id, transaction_type, amount, currency, source_wallet, destination_wallet, balance_before, balance_after, reference, description, metadata, status, requires_2fa, two_fa_verified_at, requires_admin_approval, admin_approved_by, admin_approved_at, approval_notes, completed_at, created_at FROM vault_transactions
WHERE vault_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetVaultTransactionsByVaultIDParams struct {
	VaultID uuid.UUID `json:"vault_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetVaultTransactionsByVaultID(ctx context.Context, arg GetVaultTransactionsByVaultIDParams) ([]VaultTransaction, error) {
	rows, err := q.db.QueryContext(ctx, getVaultTransactionsByVaultID, arg.VaultID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultTransaction{}
	for rows.Next() {
		var i VaultTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.SourceWallet,
			&i.DestinationWallet,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Reference,
			&i.Description,
			&i.Metadata,
			&i.Status,
			&i.Requires2fa,
			&i.TwoFaVerifiedAt,
			&i.RequiresAdminApproval,
			&i.AdminApprovedBy,
			&i.AdminApprovedAt,
			&i.ApprovalNotes,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultYieldByID = `-- name: GetVaultYieldByID :one
SELECT id, user_id, vault_id, yield_amount, yield_rate, calculation_period_start, calculation_period_end, vault_balance_snapshot, status, credited_at, created_at FROM vault_yields
WHERE id = $1
`

func (q *Queries) GetVaultYieldByID(ctx context.Context, id uuid.UUID) (VaultYield, error) {
	row := q.db.QueryRowContext(ctx, getVaultYieldByID, id)
	var i VaultYield
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VaultID,
		&i.YieldAmount,
		&i.YieldRate,
		&i.CalculationPeriodStart,
		&i.CalculationPeriodEnd,
		&i.VaultBalanceSnapshot,
		&i.Status,
		&i.CreditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVaultYieldSummary = `-- name: GetVaultYieldSummary :one
SELECT 
    COUNT(*) as total_yield_periods,
    COALESCE(SUM(yield_amount), 0) as total_yield_earned,
    COALESCE(AVG(yield_rate), 0) as average_yield_rate,
    MAX(calculation_period_end) as last_yield_date
FROM vault_yields
WHERE vault_id = $1 AND status = 'credited'
`

type GetVaultYieldSummaryRow struct {
	TotalYieldPeriods int64       `json:"total_yield_periods"`
	TotalYieldEarned  interface{} `json:"total_yield_earned"`
	AverageYieldRate  interface{} `json:"average_yield_rate"`
	LastYieldDate     interface{} `json:"last_yield_date"`
}

func (q *Queries) GetVaultYieldSummary(ctx context.Context, vaultID uuid.UUID) (GetVaultYieldSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultYieldSummary, vaultID)
	var i GetVaultYieldSummaryRow
	err := row.Scan(
		&i.TotalYieldPeriods,
		&i.TotalYieldEarned,
		&i.AverageYieldRate,
		&i.LastYieldDate,
	)
	return i, err
}

const getVaultYieldsByUserID = `-- name: GetVaultYieldsByUserID :many
SELECT vy.id, vy.user_id, vy.vault_id, vy.yield_amount, vy.yield_rate, vy.calculation_period_start, vy.calculation_period_end, vy.vault_balance_snapshot, vy.status, vy.credited_at, vy.created_at, vs.vault_name
FROM vault_yields vy
JOIN vault_savings vs ON vy.vault_id = vs.id
WHERE vy.user_id = $1
ORDER BY vy.created_at DESC
LIMIT $2 OFFSET $3
`

type GetVaultYieldsByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetVaultYieldsByUserIDRow struct {
	ID                     uuid.UUID      `json:"id"`
	UserID                 int64          `json:"user_id"`
	VaultID                uuid.UUID      `json:"vault_id"`
	YieldAmount            string         `json:"yield_amount"`
	YieldRate              string         `json:"yield_rate"`
	CalculationPeriodStart time.Time      `json:"calculation_period_start"`
	CalculationPeriodEnd   time.Time      `json:"calculation_period_end"`
	VaultBalanceSnapshot   string         `json:"vault_balance_snapshot"`
	Status                 sql.NullString `json:"status"`
	CreditedAt             sql.NullTime   `json:"credited_at"`
	CreatedAt              time.Time      `json:"created_at"`
	VaultName              string         `json:"vault_name"`
}

func (q *Queries) GetVaultYieldsByUserID(ctx context.Context, arg GetVaultYieldsByUserIDParams) ([]GetVaultYieldsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getVaultYieldsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVaultYieldsByUserIDRow{}
	for rows.Next() {
		var i GetVaultYieldsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.YieldAmount,
			&i.YieldRate,
			&i.CalculationPeriodStart,
			&i.CalculationPeriodEnd,
			&i.VaultBalanceSnapshot,
			&i.Status,
			&i.CreditedAt,
			&i.CreatedAt,
			&i.VaultName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultYieldsByVaultID = `-- name: GetVaultYieldsByVaultID :many
SELECT id, user_id, vault_id, yield_amount, yield_rate, calculation_period_start, calculation_period_end, vault_balance_snapshot, status, credited_at, created_at FROM vault_yields
WHERE vault_id = $1
ORDER BY calculation_period_end DESC
LIMIT $2 OFFSET $3
`

type GetVaultYieldsByVaultIDParams struct {
	VaultID uuid.UUID `json:"vault_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetVaultYieldsByVaultID(ctx context.Context, arg GetVaultYieldsByVaultIDParams) ([]VaultYield, error) {
	rows, err := q.db.QueryContext(ctx, getVaultYieldsByVaultID, arg.VaultID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultYield{}
	for rows.Next() {
		var i VaultYield
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.YieldAmount,
			&i.YieldRate,
			&i.CalculationPeriodStart,
			&i.CalculationPeriodEnd,
			&i.VaultBalanceSnapshot,
			&i.Status,
			&i.CreditedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultsDashboardMetrics = `-- name: GetVaultsDashboardMetrics :one

SELECT 
    COUNT(DISTINCT vs.id) as total_active_vaults,
    COUNT(DISTINCT vs.user_id) as unique_users,
    COALESCE(SUM(vs.current_balance) FILTER (WHERE vs.currency = 'USDT'), 0) as total_usdt_locked,
    COALESCE(SUM(vs.current_balance) FILTER (WHERE vs.currency = 'USDC'), 0) as total_usdc_locked,
    COALESCE(SUM(vs.current_balance) FILTER (WHERE vs.currency = 'NGN'), 0) as total_ngn_locked,
    COALESCE(SUM(vs.current_balance) FILTER (WHERE vs.currency = 'USD'), 0) as total_usd_locked,
    COALESCE(SUM(vt.amount) FILTER (WHERE vt.transaction_type = 'deposit' AND vt.created_at >= NOW() - INTERVAL '30 days'), 0) as deposits_last_30_days,
    COALESCE(SUM(vt.amount) FILTER (WHERE vt.transaction_type = 'withdrawal' AND vt.created_at >= NOW() - INTERVAL '30 days'), 0) as withdrawals_last_30_days,
    COUNT(DISTINCT vs.user_id) FILTER (WHERE vs.created_at >= NOW() - INTERVAL '30 days') as new_users_last_30_days,
    COALESCE(AVG(vs.current_balance), 0) as average_vault_balance
FROM vault_savings vs
LEFT JOIN vault_transactions vt ON vs.id = vt.vault_id
WHERE vs.status = 'active'
`

type GetVaultsDashboardMetricsRow struct {
	TotalActiveVaults     int64       `json:"total_active_vaults"`
	UniqueUsers           int64       `json:"unique_users"`
	TotalUsdtLocked       interface{} `json:"total_usdt_locked"`
	TotalUsdcLocked       interface{} `json:"total_usdc_locked"`
	TotalNgnLocked        interface{} `json:"total_ngn_locked"`
	TotalUsdLocked        interface{} `json:"total_usd_locked"`
	DepositsLast30Days    interface{} `json:"deposits_last_30_days"`
	WithdrawalsLast30Days interface{} `json:"withdrawals_last_30_days"`
	NewUsersLast30Days    int64       `json:"new_users_last_30_days"`
	AverageVaultBalance   interface{} `json:"average_vault_balance"`
}

// ============================================================================
// COMPLEX ANALYTICAL QUERIES
// ============================================================================
func (q *Queries) GetVaultsDashboardMetrics(ctx context.Context) (GetVaultsDashboardMetricsRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultsDashboardMetrics)
	var i GetVaultsDashboardMetricsRow
	err := row.Scan(
		&i.TotalActiveVaults,
		&i.UniqueUsers,
		&i.TotalUsdtLocked,
		&i.TotalUsdcLocked,
		&i.TotalNgnLocked,
		&i.TotalUsdLocked,
		&i.DepositsLast30Days,
		&i.WithdrawalsLast30Days,
		&i.NewUsersLast30Days,
		&i.AverageVaultBalance,
	)
	return i, err
}

const getVaultsDueForAutoSave = `-- name: GetVaultsDueForAutoSave :many
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE auto_save_enabled = TRUE
  AND status = 'active'
  AND next_auto_save <= NOW()
ORDER BY next_auto_save ASC
`

func (q *Queries) GetVaultsDueForAutoSave(ctx context.Context) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, getVaultsDueForAutoSave)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultsDueForYieldCalculation = `-- name: GetVaultsDueForYieldCalculation :many
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE status = 'active'
  AND current_balance > 0
  AND (next_yield_calculation IS NULL OR next_yield_calculation <= NOW())
ORDER BY next_yield_calculation ASC NULLS FIRST
LIMIT $1
`

func (q *Queries) GetVaultsDueForYieldCalculation(ctx context.Context, limit int32) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, getVaultsDueForYieldCalculation, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultsWithActiveRecurringRules = `-- name: GetVaultsWithActiveRecurringRules :many
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at
FROM vault_savings
WHERE recurring_rule IS NOT NULL
  AND recurring_rule->>'enabled' = 'true'
  AND status = 'active'
`

// Get all vaults that have active recurring rules (for stats)
func (q *Queries) GetVaultsWithActiveRecurringRules(ctx context.Context) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, getVaultsWithActiveRecurringRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultsWithDueRecurringDeposits = `-- name: GetVaultsWithDueRecurringDeposits :many
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at
FROM vault_savings
WHERE recurring_rule IS NOT NULL
  AND recurring_rule->>'enabled' = 'true'
  AND (recurring_rule->>'next_execution_at')::timestamptz <= $1::timestamptz
  AND status = 'active'
ORDER BY (recurring_rule->>'next_execution_at')::timestamptz ASC
`

// Get all vaults with recurring deposits that are due for execution
func (q *Queries) GetVaultsWithDueRecurringDeposits(ctx context.Context, dollar_1 time.Time) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, getVaultsWithDueRecurringDeposits, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultsWithLowBalance = `-- name: GetVaultsWithLowBalance :many
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE status = 'active'
  AND current_balance > 0
  AND current_balance < goal_amount * 0.1  -- Less than 10% of goal
ORDER BY (current_balance / NULLIF(goal_amount, 0)) ASC
LIMIT $1
`

func (q *Queries) GetVaultsWithLowBalance(ctx context.Context, limit int32) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, getVaultsWithLowBalance, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVaultsWithRecurringRules = `-- name: GetVaultsWithRecurringRules :many
SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE recurring_rule IS NOT NULL
  AND status = 'active'
  AND (recurring_rule->>'enabled')::boolean = true
  AND (recurring_rule->>'next_execution_at')::timestamptz <= NOW()
ORDER BY (recurring_rule->>'next_execution_at')::timestamptz ASC
LIMIT $1
`

func (q *Queries) GetVaultsWithRecurringRules(ctx context.Context, limit int32) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, getVaultsWithRecurringRules, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYieldConfigByID = `-- name: GetYieldConfigByID :one
SELECT id, currency, apy_rate, min_balance_for_yield, compound_frequency, is_active, effective_from, effective_until, notes, created_at, updated_at FROM vault_yield_configs
WHERE id = $1
`

func (q *Queries) GetYieldConfigByID(ctx context.Context, id uuid.UUID) (VaultYieldConfig, error) {
	row := q.db.QueryRowContext(ctx, getYieldConfigByID, id)
	var i VaultYieldConfig
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.ApyRate,
		&i.MinBalanceForYield,
		&i.CompoundFrequency,
		&i.IsActive,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getYieldConfigHistory = `-- name: GetYieldConfigHistory :many
SELECT id, currency, apy_rate, min_balance_for_yield, compound_frequency, is_active, effective_from, effective_until, notes, created_at, updated_at FROM vault_yield_configs
WHERE currency = $1
ORDER BY effective_from DESC
LIMIT $2 OFFSET $3
`

type GetYieldConfigHistoryParams struct {
	Currency string `json:"currency"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) GetYieldConfigHistory(ctx context.Context, arg GetYieldConfigHistoryParams) ([]VaultYieldConfig, error) {
	rows, err := q.db.QueryContext(ctx, getYieldConfigHistory, arg.Currency, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultYieldConfig{}
	for rows.Next() {
		var i VaultYieldConfig
		if err := rows.Scan(
			&i.ID,
			&i.Currency,
			&i.ApyRate,
			&i.MinBalanceForYield,
			&i.CompoundFrequency,
			&i.IsActive,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYieldConfigsByCurrency = `-- name: GetYieldConfigsByCurrency :many
SELECT id, currency, apy_rate, min_balance_for_yield, compound_frequency, is_active, effective_from, effective_until, notes, created_at, updated_at FROM vault_yield_configs
WHERE currency = $1
ORDER BY effective_from DESC
`

func (q *Queries) GetYieldConfigsByCurrency(ctx context.Context, currency string) ([]VaultYieldConfig, error) {
	rows, err := q.db.QueryContext(ctx, getYieldConfigsByCurrency, currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultYieldConfig{}
	for rows.Next() {
		var i VaultYieldConfig
		if err := rows.Scan(
			&i.ID,
			&i.Currency,
			&i.ApyRate,
			&i.MinBalanceForYield,
			&i.CompoundFrequency,
			&i.IsActive,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYieldsByPeriod = `-- name: GetYieldsByPeriod :many
SELECT id, user_id, vault_id, yield_amount, yield_rate, calculation_period_start, calculation_period_end, vault_balance_snapshot, status, credited_at, created_at FROM vault_yields
WHERE vault_id = $1
  AND calculation_period_start >= $2
  AND calculation_period_end <= $3
ORDER BY calculation_period_start ASC
`

type GetYieldsByPeriodParams struct {
	VaultID                uuid.UUID `json:"vault_id"`
	CalculationPeriodStart time.Time `json:"calculation_period_start"`
	CalculationPeriodEnd   time.Time `json:"calculation_period_end"`
}

func (q *Queries) GetYieldsByPeriod(ctx context.Context, arg GetYieldsByPeriodParams) ([]VaultYield, error) {
	rows, err := q.db.QueryContext(ctx, getYieldsByPeriod, arg.VaultID, arg.CalculationPeriodStart, arg.CalculationPeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultYield{}
	for rows.Next() {
		var i VaultYield
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultID,
			&i.YieldAmount,
			&i.YieldRate,
			&i.CalculationPeriodStart,
			&i.CalculationPeriodEnd,
			&i.VaultBalanceSnapshot,
			&i.Status,
			&i.CreditedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementVaultBalance = `-- name: IncrementVaultBalance :exec
UPDATE vault_savings
SET current_balance = current_balance + $2,
    updated_at = NOW()
WHERE id = $1
`

type IncrementVaultBalanceParams struct {
	ID             uuid.UUID      `json:"id"`
	CurrentBalance sql.NullString `json:"current_balance"`
}

func (q *Queries) IncrementVaultBalance(ctx context.Context, arg IncrementVaultBalanceParams) error {
	_, err := q.db.ExecContext(ctx, incrementVaultBalance, arg.ID, arg.CurrentBalance)
	return err
}

const lockVaultForUpdate = `-- name: LockVaultForUpdate :one

SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE id = $1
FOR UPDATE
`

// Lock row for transaction
func (q *Queries) LockVaultForUpdate(ctx context.Context, id uuid.UUID) (VaultSaving, error) {
	row := q.db.QueryRowContext(ctx, lockVaultForUpdate, id)
	var i VaultSaving
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VaultName,
		&i.Description,
		&i.GoalAmount,
		&i.CurrentBalance,
		&i.Currency,
		&i.AutoSaveEnabled,
		&i.AutoSaveFrequency,
		&i.AutoSaveAmount,
		&i.NextAutoSave,
		&i.RecurringRule,
		&i.TotalYieldEarned,
		&i.NextYieldCalculation,
		&i.LastYieldCalculation,
		&i.Status,
		&i.VaultType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markTransaction2FAVerified = `-- name: MarkTransaction2FAVerified :exec
UPDATE vault_transactions
SET two_fa_verified_at = NOW()
WHERE id = $1 AND requires_2fa = TRUE
`

func (q *Queries) MarkTransaction2FAVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markTransaction2FAVerified, id)
	return err
}

const processVaultDeposit = `-- name: ProcessVaultDeposit :exec

UPDATE vault_savings
SET current_balance = current_balance + $2,
    updated_at = NOW()
WHERE id = $1
`

type ProcessVaultDepositParams struct {
	ID             uuid.UUID      `json:"id"`
	CurrentBalance sql.NullString `json:"current_balance"`
}

// ============================================================================
// TRANSACTION MANAGEMENT QUERIES (FOR USE WITH SQLC TRANSACTIONS)
// ============================================================================
// This should be called within a transaction
func (q *Queries) ProcessVaultDeposit(ctx context.Context, arg ProcessVaultDepositParams) error {
	_, err := q.db.ExecContext(ctx, processVaultDeposit, arg.ID, arg.CurrentBalance)
	return err
}

const processVaultWithdrawal = `-- name: ProcessVaultWithdrawal :exec
UPDATE vault_savings
SET current_balance = current_balance - $2,
    updated_at = NOW()
WHERE id = $1 
  AND current_balance >= $2
`

type ProcessVaultWithdrawalParams struct {
	ID             uuid.UUID      `json:"id"`
	CurrentBalance sql.NullString `json:"current_balance"`
}

// This should be called within a transaction
// Will fail if insufficient balance
func (q *Queries) ProcessVaultWithdrawal(ctx context.Context, arg ProcessVaultWithdrawalParams) error {
	_, err := q.db.ExecContext(ctx, processVaultWithdrawal, arg.ID, arg.CurrentBalance)
	return err
}

const searchVaultsByName = `-- name: SearchVaultsByName :many


SELECT id, user_id, vault_name, description, goal_amount, current_balance, currency, auto_save_enabled, auto_save_frequency, auto_save_amount, next_auto_save, recurring_rule, total_yield_earned, next_yield_calculation, last_yield_calculation, status, vault_type, created_at, updated_at, completed_at FROM vault_savings
WHERE user_id = $1 
  AND vault_name ILIKE '%' || $2 || '%'
  AND status != 'cancelled'
ORDER BY created_at DESC
`

type SearchVaultsByNameParams struct {
	UserID  int64          `json:"user_id"`
	Column2 sql.NullString `json:"column_2"`
}

// -- name: BatchCreateTransactions :copyfrom
// INSERT INTO vault_transactions (
//
//	user_id,
//	vault_id,
//	transaction_type,
//	amount,
//	currency,
//	balance_before,
//	balance_after,
//	reference,
//	description,
//	status
//
// ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10);
// ============================================================================
// SEARCH AND FILTER QUERIES
// ============================================================================
func (q *Queries) SearchVaultsByName(ctx context.Context, arg SearchVaultsByNameParams) ([]VaultSaving, error) {
	rows, err := q.db.QueryContext(ctx, searchVaultsByName, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VaultSaving{}
	for rows.Next() {
		var i VaultSaving
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VaultName,
			&i.Description,
			&i.GoalAmount,
			&i.CurrentBalance,
			&i.Currency,
			&i.AutoSaveEnabled,
			&i.AutoSaveFrequency,
			&i.AutoSaveAmount,
			&i.NextAutoSave,
			&i.RecurringRule,
			&i.TotalYieldEarned,
			&i.NextYieldCalculation,
			&i.LastYieldCalculation,
			&i.Status,
			&i.VaultType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringRule = `-- name: UpdateRecurringRule :exec
UPDATE vault_savings
SET recurring_rule = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateRecurringRuleParams struct {
	ID            uuid.UUID             `json:"id"`
	RecurringRule pqtype.NullRawMessage `json:"recurring_rule"`
}

func (q *Queries) UpdateRecurringRule(ctx context.Context, arg UpdateRecurringRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateRecurringRule, arg.ID, arg.RecurringRule)
	return err
}

const updateVaultBalance = `-- name: UpdateVaultBalance :exec
UPDATE vault_savings
SET current_balance = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateVaultBalanceParams struct {
	ID             uuid.UUID      `json:"id"`
	CurrentBalance sql.NullString `json:"current_balance"`
}

func (q *Queries) UpdateVaultBalance(ctx context.Context, arg UpdateVaultBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultBalance, arg.ID, arg.CurrentBalance)
	return err
}

const updateVaultGoalDetails = `-- name: UpdateVaultGoalDetails :exec
UPDATE vault_savings
SET vault_name = COALESCE($2, vault_name),
    description = COALESCE($3, description),
    goal_amount = COALESCE($4, goal_amount),
    updated_at = NOW()
WHERE id = $1
`

type UpdateVaultGoalDetailsParams struct {
	ID          uuid.UUID      `json:"id"`
	VaultName   sql.NullString `json:"vault_name"`
	Description sql.NullString `json:"description"`
	GoalAmount  sql.NullString `json:"goal_amount"`
}

func (q *Queries) UpdateVaultGoalDetails(ctx context.Context, arg UpdateVaultGoalDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultGoalDetails,
		arg.ID,
		arg.VaultName,
		arg.Description,
		arg.GoalAmount,
	)
	return err
}

const updateVaultRecurringRule = `-- name: UpdateVaultRecurringRule :exec
UPDATE vault_savings
SET recurring_rule = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateVaultRecurringRuleParams struct {
	ID            uuid.UUID             `json:"id"`
	RecurringRule pqtype.NullRawMessage `json:"recurring_rule"`
}

// Update the recurring rule for a vault
func (q *Queries) UpdateVaultRecurringRule(ctx context.Context, arg UpdateVaultRecurringRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultRecurringRule, arg.ID, arg.RecurringRule)
	return err
}

const updateVaultStatus = `-- name: UpdateVaultStatus :exec
UPDATE vault_savings
SET status = $2,
    updated_at = NOW(),
    completed_at = CASE 
        WHEN $2 = 'completed' THEN NOW()
        ELSE completed_at
    END
WHERE id = $1
`

type UpdateVaultStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateVaultStatus(ctx context.Context, arg UpdateVaultStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultStatus, arg.ID, arg.Status)
	return err
}

const updateVaultTransactionStatus = `-- name: UpdateVaultTransactionStatus :exec
UPDATE vault_transactions
SET status = $2,
    completed_at = CASE 
        WHEN $2 = 'completed' THEN NOW()
        ELSE completed_at
    END
WHERE id = $1
`

type UpdateVaultTransactionStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) UpdateVaultTransactionStatus(ctx context.Context, arg UpdateVaultTransactionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVaultTransactionStatus, arg.ID, arg.Status)
	return err
}

const updateYieldConfig = `-- name: UpdateYieldConfig :exec
UPDATE vault_yield_configs
SET apy_rate = COALESCE($2, apy_rate),
    min_balance_for_yield = COALESCE($3, min_balance_for_yield),
    compound_frequency = COALESCE($4, compound_frequency),
    is_active = COALESCE($5, is_active),
    effective_until = COALESCE($6, effective_until),
    notes = COALESCE($7, notes),
    updated_at = NOW()
WHERE id = $1
`

type UpdateYieldConfigParams struct {
	ID                 uuid.UUID      `json:"id"`
	ApyRate            sql.NullString `json:"apy_rate"`
	MinBalanceForYield sql.NullString `json:"min_balance_for_yield"`
	CompoundFrequency  sql.NullString `json:"compound_frequency"`
	IsActive           sql.NullBool   `json:"is_active"`
	EffectiveUntil     sql.NullTime   `json:"effective_until"`
	Notes              sql.NullString `json:"notes"`
}

func (q *Queries) UpdateYieldConfig(ctx context.Context, arg UpdateYieldConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateYieldConfig,
		arg.ID,
		arg.ApyRate,
		arg.MinBalanceForYield,
		arg.CompoundFrequency,
		arg.IsActive,
		arg.EffectiveUntil,
		arg.Notes,
	)
	return err
}

const updateYieldStatus = `-- name: UpdateYieldStatus :exec
UPDATE vault_yields
SET status = $2,
    credited_at = CASE 
        WHEN $2 = 'credited' THEN NOW()
        ELSE credited_at
    END
WHERE id = $1
`

type UpdateYieldStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) UpdateYieldStatus(ctx context.Context, arg UpdateYieldStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateYieldStatus, arg.ID, arg.Status)
	return err
}

const updateYieldTracking = `-- name: UpdateYieldTracking :exec
UPDATE vault_savings
SET total_yield_earned = $2,
    last_yield_calculation = $3,
    next_yield_calculation = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateYieldTrackingParams struct {
	ID                   uuid.UUID      `json:"id"`
	TotalYieldEarned     sql.NullString `json:"total_yield_earned"`
	LastYieldCalculation sql.NullTime   `json:"last_yield_calculation"`
	NextYieldCalculation sql.NullTime   `json:"next_yield_calculation"`
}

func (q *Queries) UpdateYieldTracking(ctx context.Context, arg UpdateYieldTrackingParams) error {
	_, err := q.db.ExecContext(ctx, updateYieldTracking,
		arg.ID,
		arg.TotalYieldEarned,
		arg.LastYieldCalculation,
		arg.NextYieldCalculation,
	)
	return err
}
