name: Deploy to Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
         role-session-name: GitHub_to_AWS_via_FederatedOIDC
         aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
           registry-type: public

    - name: Creating env file and make build
      run: |
        echo "${{ secrets.ENV }}" > .env   
        cat .env

    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: q0v6o6u9
          REPOSITORY: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: latest
      run: |
        docker build -f Dockerfile -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG


  deploy:
    needs: Build
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove old containers
        run: |
          sudo docker-compose -f docker-compose.yml down

      - name: Start services with Docker Compose
        run: |
          sudo docker-compose up -d --build

      - name: Clean up unused Docker images and containers
        run: |
          sudo docker system prune -a -f