name: Deploy to Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
         role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
         role-session-name: GitHub_to_AWS_via_FederatedOIDC
         aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
           registry-type: public

    - name: Creating env file and make build
      run: |
        echo "${{ secrets.ENV }}" > .env   

    - name: Build, tag, and push image to AWS ECR public
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV


  deploy:
    needs: Build
    runs-on: self-hosted 
    steps:
      - name: Pull docker image
        run: sudo docker pull public.ecr.aws/q0v6o6u9/swiftfiat-backend

      - name: Delete old container
        run: sudo docker rm -f swiftfiat-backend 

      - name: Run docker container          
        run: sudo docker run -d -p 9000:9000 --name swiftfiat-backend public.ecr.aws/q0v6o6u9/swiftfiat-backend