name: Deploy to staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    #needs: Build
    runs-on: [self-hosted, staging]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Creating env file and make build
        run: |
          echo "${{ secrets.ENV }}" > .env   
          cat .env
    

      - name: Remove old containers
        run: |
          sudo docker-compose -f docker-compose.yml down

      - name: Start services with Docker Compose
        run: |
          sudo docker-compose up -d --build

      - name: Clean up unused Docker images and containers
        run: |
          sudo docker system prune -a -f