name: Deploy to Dev

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    #needs: Build
    runs-on: [self-hosted, staging]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Creating env file and json file
        run: |
          echo "${{ secrets.STAGING_ENV }}" > .env  
         

      - name: Save JSON Content to a File
        env:
          JSON_CONTENT: ${{ secrets.GOOGLE_CRED }}
        run: |
          echo "$JSON_CONTENT" > swift-dev-be547-firebase-adminsdk-xs6po-33bfff6f7d.json
          echo "JSON file created: $(cat swift-dev-be547-firebase-adminsdk-xs6po-33bfff6f7d.json)"     
          

      - name: Remove old containers
        run: |
          sudo docker-compose -f docker-compose.yml down

      - name: Start services with Docker Compose
        run: |
          sudo docker-compose up -d --build

      - name: Clean up unused Docker images and containers
        run: |
          sudo docker system prune -a -f